### ISSUE TITLE
Headers

### ISSUE THREAD

**Issue by ahmah11** [smartrics/RestFixture#106]
I am trying a simple request on my rest but it seems that the headers are not taken into account:

|!-Table:smartrics.rest.fitnesse.fixture.RestFixture-! |http:/rest-s03.mtl.mnubo.com:8081|
| setHeader |Authorization : Bearer 221c125c2110fc4697f208a92add68a|
| setHeader |Accept-Encoding : application/json|
| setHeader |Content-Type : application/json|
|GET|/rest/users/user1@mnubo.com|200|||

It is returning:

{"error":"unauthorized_client","error_description":"Header Authorization: Bearer <access-token> mandatory.","timestamp":"2015-01-15T21:55:46.701Z"}

The answer says that the bearer header is mandatory although i specified it in the header.

Am i using the right syntax to pass the header ?

**Comment by smartrics** [comment]
you may try 

| setHeaders | !-h1 : v1
h2:v2
h3:v3-! |

**Comment by ahmah11** [comment]
Great it worked !
