### ISSUE TITLE
Process for converting 3.0 to 3.1?

### ISSUE THREAD

**Issue by sadams3180** [smartrics/RestFixture#108]
Hi,
Forgive me for asking a simple question. So I'm excited to try your new changes in 3.1 to better work with some of my JSON outputs in the newer versions of Fitnesse. However the overall Master file setup of 3.1 is so much more different from it's previous 3.0 predecessor. Jar files under the lib folder for example in 3.0 are not available in 3.1. What file changes/additions would I need to make the 3.1 changes work? Or would I need to compile a new jar file called "smartrics-RestFixture-3.1" (if so which files should I include)? Are there any major classpath references in Fitnesse I would need to add/update in order to start using the new 3.1 files? I have enjoyed and heavily used 3.0 but a little fuzzy on how to update things to 3.1

Thanks.

**Comment by smartrics** [comment]
Hi

you can download the zip with all dependencies from http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22smartrics.restfixture%22%20AND%20a%3A%22smartrics-RestFixture%22

there really is nothing different between 3.0 and 3.1 regarding the way you install it.
simply replace the jars of 3.1 where you had the jars on 3.0 and it "should work"

if not please paste here the error you may get

**Comment by sadams3180** [comment]
Thanks Fabrizio, I looked at this briefly (and the link) when you replied. But I didn't have time to download the new 3.1 zip file. Now I click on the Central repository link and it's missing. Is there a reason the 3.1 went away?

**Comment by smartrics** [comment]
Hi you can also download it from mvnrepository
http://mvnrepository.com/artifact/smartrics.restfixture

**Comment by smartrics** [comment]
I am not sure why it's not currently displaying in th maven central site
but this link seems to work

http://search.maven.org/remotecontent?filepath=smartrics/restfixture/smartrics-RestFixture/3.1/smartrics-RestFixture-3.1-bin.zip

**Comment by smartrics** [comment]
Please re-open if you have still problems
