### ISSUE TITLE
test title

### ISSUE THREAD

**Issue by ahmah11** [smartrics/RestFixture#109]
Is there a way to give a title for each test, because i will have a long list of tests and if somebody want to search for a specific test it will be very hard.
Thanks

**Comment by ahmah11** [comment]
any help ?

**Comment by smartrics** [comment]
Hi - maybe you could

* use fitnesse wiki markup to provide some structure to the page or
* split one test per page - the page name is your test or
* a mix of the above: group fixtures testing the same feature in pages
* use |comment| to add comments to your test. check the doc: https://cloud.github.com/downloads/smartrics/RestFixture/RestFixture-3.0.pdf

Other than that you'll have to extend the RestFixture class and add a title cell yourself

**Comment by ahmah11** [comment]
In your RestFixture class i incremented getcell calls index by 1 which leaves an empty cell in the beginning. It works fine
