### ISSUE TITLE
store whole json response to a variable

### ISSUE THREAD

**Issue by alvillaflor** [smartrics/RestFixture#111]
Is there a way to store the whole POST response to a variable?

something like this?
|Table: Rest Fixture | http://...|
|set Header | Content-Type: ... |
|set Body| {...} |
|POST| /uri | 200 | Content-Length : [\d]+ | $store_whole_response_here |

**Comment by jplambert** [comment]
You can use "let" lines.

However there is some issues as seen in issues #52 and #110. I am trying to see how to get a solution there.

**Comment by smartrics** [comment]
Yes, please use 

| let | body | js | response.jsonbody  | | 

you can then use body in other RestFixtures.

if you need to pass body to other fixtures, follow #52

**Comment by alvillaflor** [comment]
Hi. I did try using

| let | body | js | response.jsonbody | | 

but the result that I got was [object [object]] instead of the json string.  Is there a way to get the string instead of the object?

**Comment by jplambert** [comment]
@alvillaflor I had the same experience, but got what I wanted by using:

| let | body | js | JSON.parse(response.body) | | 

From there I can navigate in the JSON content as an object:

| let | id | js | JSON.parse(response.body).id | |

**Comment by alvillaflor** [comment]
Thanks JP.

I found one that works.
| let | body | js | response.body | | 

instead of response.jsonbody.

Q: where can I find information on the difference between jsonbody and json. and the methods I can use. such as response.statusCode, etc ....  or jsonbody.<assume this is the xpath dotted?>

**Comment by smartrics** [comment]
@alvillaflor https://cloud.github.com/downloads/smartrics/RestFixture/RestFixture-3.0.pdf which has been generated from https://github.com/smartrics/RestFixtureLiveDoc
