### ISSUE TITLE
Bad URL constucted when embedded question marks

### ISSUE THREAD

**Issue by jplambert** [smartrics/RestFixture#112]
I found out that using some convoluted URLs, RestFixture shows some very strange behaviors.

| Table: Rest Fixture | http://localhost:8070 | hopconf|
| GET | /abc/xyz?url=http://host/ws?g | | | |

=> Will make the request go on http://localhost:8070/abc/xyz

I found where is located the issue in the code, it is in RestFixture#doMethod(String, String, Map<String, String>, String): the url is split by the "?" character, the first part being taken as the base URL and the second part as the query part. However if there is more than two parts, the remaining is left out and things go wrong...

It is very easy to fix. One can concatenate all the remaining split parts when building up the query part. Or even more simple, just add the '2' value as a second parameter of the String.split(String, int) call so that it guarantees not to create more than two chunks.

I will gladly make a Pull Request as soon as I managed to use GitHub... Unless I am beaten by somebody else on this :-)

Note: I *do* need this fix for the project I'm working on.

**Comment by smartrics** [comment]
can you send me a patch file with the fix?

**Comment by smartrics** [comment]
that's interesting - should you not url encode the value?

| GET | /abc/xyz?url=http%3A%2F%2Fhost%2Fws%3Fg | | | |

**Comment by smartrics** [comment]
Fix available in RestFixture-3.2

**Comment by jplambert** [comment]
Thanks a lot for the fix! I'll test it ASAP.

I agree with you about the encoding in the URL.

Fact is, the webservice I am calling will make some computation based on the URI provided as an argument (thus the second "?" being there, part of the embedded URI), and the webservice does not return the same value if I encode the characters... I tried this obviously :-)

I agree that we may consider this as a lack of the webservice: it should URI-decode the embedded URI and perform the same computation either way. However in my case, this webservice is not part of the SUT but belongs to another team so the change may not be easy to make -- at the very least, I would not expect the change to be available immediately. I'll talk with them, just to make sure what is the expected behavior...

So, thanks again!

**Comment by jplambert** [comment]
Just a final comment to confirm that the fix works. Re-building RestFixture from the sources, I have been able to use the webservice embedding an URL in its request parameters. Great!
