### ISSUE TITLE
Unit test error because of error message localization

### ISSUE THREAD

**Issue by jplambert** [smartrics/RestFixture#113]
Hello,

Depending on the system on which I build RestFixture, one test can fail.

--

Failed tests:   shouldTrapJavascriptErrorAndWrapThemInErrors(smartrics.rest.fitnesse.fixture.support.JavascriptWrapperTest): 

--

From what I saw in the code, this is because the unit test checks the message of the JavaScript exception. Unfortunately this message is localized and the test will fail if the message do not come up in english.

The easiest solution would be not to check the message itself and only check that the exception is thrown.

Alternatively, we should set the locale either in the build system or in the test itself. I tried the latter, but could not get it work. (that does not mean it is not possible)

In any case I find it a bit tedious to check the content of the exception message... Is it important to make sure the proper exception is raised?

Thanks in advance,

JP

**Comment by smartrics** [comment]
Hey JP, no - you can just check for the exception and not the message

**Comment by jplambert** [comment]
Thanks a lot, I'll check it works now.

**Comment by jplambert** [comment]
... and I confirm it works :-)
