### ISSUE TITLE
using restfixture in a scenario/script tables

### ISSUE THREAD

**Issue by darthwangusa** [smartrics/RestFixture#115]
I have been looking and couldn't find any examples on how to use the restfixture in a scenario or script tables.  I have tried different ways to put it in a scenario table but have no luck and just keeps getting errors.  Is it possible to make the restfixture into a scenario? If so, can you please provide an example?
thanks.

**Comment by smartrics** [comment]
I am not familiar with scenarios (and I can't support it - see #79) but this may help

http://stackoverflow.com/questions/21190780/can-i-make-a-scenario-of-restfixture-table-in-fitnesse-or-is-there-another-way
