### ISSUE TITLE
 Execution of Post caused exception 'Http call failed for IO failure'. Problem with RestFixture

### ISSUE THREAD

**Issue by pradeepkumar1306** [smartrics/RestFixture#116]
Hi, 

Can some expert in RestFixture help me?
When i call the webservice and if the client takes more than 3seconds to return the result the fixture fails with the below error.

 Execution of Post caused exception 'Http call failed for IO failure' 
 TypeError: Cannot read property "body" from null (unnamed script#1)

Otherwise, if the results is mocked and the response comes in less than 3 seconds, the page is green.

Its a weird situation. Please help.

**Comment by pradeepkumar1306** [comment]
However, it the webservice works well with the curl command.

**Comment by jplambert** [comment]
You can override the default HTTP connection timeout using a RestFixtureConfig fixture.

Try something like that:

| Import |
| smartrics.rest.fitnesse.fixture |

|Table: Rest Fixture Config|longtimeoutconfig|
|http.client.connection.timeout|10000|

10 seconds = 10000 milliseconds
1 minute = 60000 milliseconds

|Table: Rest Fixture|http://localhost|longtimeoutconfig|
... your test ...

**Comment by smartrics** [comment]
Thanks JP - @pradeepkumar1306 please re-open if the issue still persists
