### ISSUE TITLE
How to escape &nbsp; in fitnesse results

### ISSUE THREAD

**Issue by pradeepkumar1306** [smartrics/RestFixture#117]
Dear expert

Date&nbsp;:&nbsp;Thu,&nbsp;19&nbsp;Mar&nbsp;2015&nbsp;07:57:18&nbsp;GMT<br/>Content-Type&nbsp;:&nbsp;application/json<br/>Transfer-Encoding&nbsp;:&nbsp;chunked

Fitnesse results are displayed with a lot of &nbsp; and asserting becomes very dirty and not readable.

Can you please suggest how to get rid of this &nbsp;

THanks Pradeep

**Comment by pradeepkumar1306** [comment]
{{{
{"cause":"Return&nbsp;Status&nbsp;Received&nbsp;for&nbsp;Booking&nbsp;ID:&nbsp;[&nbsp;ff27d02b3c9d&nbsp;]&nbsp;with&nbsp;Code:&nbsp;[&nbsp;65&nbsp;]&nbsp;,&nbsp;Description:&nbsp;[&nbsp;Fatal&nbsp;Error.&nbsp;Check&nbsp;GMI&nbsp;log.&nbsp;]","header":{"messageId":"Message-1","sentBy":"CDT-AME","createdAt":1420070400000},"movementId":"7de3ac34-f863-44c3-8150-37d1f95daone"}}}}

**Comment by pradeepkumar1306** [comment]
&ampnbsp; is to be avoided

**Comment by pradeepkumar1306** [comment]
{{{ how to remove &nbsp; in fitnesse assertion }}}

**Comment by pradeepkumar1306** [comment]
how to remove !-&nbsp;-! in fitnesse assertion

**Comment by smartrics** [comment]
can you please share what version of fitnesse and rest fixture you are using?

**Comment by pradeepkumar1306** [comment]
<dependency>
      <groupId>org.fitnesse</groupId>
      <artifactId>fitnesse</artifactId>
      <version>20140630</version>
    </dependency>
    <dependency>
      <groupId>org.fitnesse</groupId>
      <artifactId>fitlibrary</artifactId>
      <version>20110301</version>
    </dependency>

this is the dependency?

Please let me how to escape them. The output when i demo to clients looks very dirty with these characters.

Thanks fitnesse expert for your help

**Comment by smartrics** [comment]
hi - what version of the RestFixture?

On 27 March 2015 at 03:20, pradeepkumar1306 <notifications@github.com>
wrote:

>
> org.fitnesse
> fitnesse
> 20140630
>
>
> org.fitnesse
> fitlibrary
> 20110301
>
> this is the dependency?
>
> Please let me how to escape them. The output when i demo to clients looks
> very dirty with these characters.
>
> Thanks fitnesse expert for your help
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/smartrics/RestFixture/issues/117#issuecomment-86806179>
> .
>



-- 
Regards,

 Fabrizio

**Comment by smartrics** [comment]
can you please attach an example showing your test and its execution
response

On 27 March 2015 at 09:41, Fabrizio Cannizzo <smartrics@gmail.com> wrote:

> hi - what version of the RestFixture?
>
> On 27 March 2015 at 03:20, pradeepkumar1306 <notifications@github.com>
> wrote:
>
>>
>> org.fitnesse
>> fitnesse
>> 20140630
>>
>>
>> org.fitnesse
>> fitlibrary
>> 20110301
>>
>> this is the dependency?
>>
>> Please let me how to escape them. The output when i demo to clients looks
>> very dirty with these characters.
>>
>> Thanks fitnesse expert for your help
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/smartrics/RestFixture/issues/117#issuecomment-86806179>
>> .
>>
>
>
>
> --
> Regards,
>
>  Fabrizio
>



-- 
Regards,

 Fabrizio

**Comment by pradeepkumar1306** [comment]
Rest Fixture:
<dependency>
        <groupId>smartrics.restfixture</groupId>
        <artifactId>smartrics-RestFixture</artifactId>
        <version>3.0</version>
      </dependency>

**Comment by smartrics** [comment]
Hi,  can you please try update to 3.1 and see if the error persists?

http://mvnrepository.com/artifact/smartrics.restfixture/smartrics-RestFixture/3.1

On 31 March 2015 at 08:45, pradeepkumar1306 <notifications@github.com>
wrote:

> Rest Fixture:
>
> smartrics.restfixture
> smartrics-RestFixture
> 3.0
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/smartrics/RestFixture/issues/117#issuecomment-87981244>
> .
>



-- 
Regards,

 Fabrizio

**Comment by pradeepkumar1306** [comment]
![capture](https://cloud.githubusercontent.com/assets/11454872/6914822/43bde5c6-d7c1-11e4-990a-408ee37a852e.JPG)

**Comment by pradeepkumar1306** [comment]
Expert,
We have a firmwide repo which does not have 3.1 version yet, so i may not be able to download from external repo. Any other suggestion pls

**Comment by smartrics** [comment]
the fix you're looking for is in 3.1
can you download the fixture by hand and set it as provided dependency?

On 31 March 2015 at 09:25, pradeepkumar1306 <notifications@github.com>
wrote:

> Expert,
> We have a firmwide repo which does not have 3.1 version yet, so i may not
> be able to download from external repo. Any other suggestion pls
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/smartrics/RestFixture/issues/117#issuecomment-87993212>
> .
>



-- 
Regards,

 Fabrizio

**Comment by pradeepkumar1306** [comment]
Thank you my friend. Much appreciated for your support. I will try.
