### ISSUE TITLE
How can I measure response time

### ISSUE THREAD

**Issue by timbog** [smartrics/RestFixture#122]
Hi!
Is there any way to check server response time, for example, I want to make sure that it is less than some period of time?
Thanks.

**Comment by smartrics** [comment]
hello - there's no support for measuring and checking response time

On 26 May 2015 at 07:32, timbog <notifications@github.com> wrote:

> Hi!
> Is there any way to check server response time, for example, I want to
> make sure that it is less than some period of time?
> Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/smartrics/RestFixture/issues/122>.
>



-- 
Regards,

 Fabrizio
