### ISSUE TITLE
Does REST Fixture support HTTPS

### ISSUE THREAD

**Issue by abelyaevskiy** [smartrics/RestFixture#127]
Hi!

Does REST Fixture support HTTPS at the moment?

**Comment by smartrics** [comment]
hello - not entirely. The RestClient (a tiny wrapper of Apache httpclient-3.1) should be extended as described here http://hc.apache.org/httpclient-3.x/sslguide.html
then any config option should be exposed via RestFixture config and presented to  the end user for setup.
