### ISSUE TITLE
Check JSON array

### ISSUE THREAD

**Issue by Thaoden** [smartrics/RestFixture#128]
I want to check a JSON array like
```
[
    {
        "Id": 1,
        "Host": {
            "Id": 1,
            "LoginId": "abc"
        }
    },
    {
        "Id": 2,
        "Host": {
            "Id": 3,
            "LoginId": "def"
        }
    }
]
```
If the order of the elements was fixed, I would check for the host loginID like this: `jsonbody[0].Host.LoginId=="abc"`. However, the order isn't fixed (meaning element with ID 1 could appear at 2nd position).
How can I check for an occurrence anywhere in the array?

**Comment by smartrics** [comment]
Hello

the expectation cell can be interpreted as a javascript block if the first line is 

/* javascript */

The block must return a boolean that will be interpreted as pass or fail

In the block you will have to search the array and return true if you find the expected item

Something like

| GET | URL | | | /* javascript */
for (var x in jsonbody) {
 // if found return true
} 
return false;|

**Comment by Thaoden** [comment]
Hi,
thanks for the help.
With my basic knowledge of JavaScript, I'm trying

```| GET | URL | 200 | | /* javascript */ for(var x in jsonbody){if (x.LoginId=="abc") {return true;}  } return false; | ```

but an exception gets thrown:

```smartrics.rest.fitnesse.fixture.support.JavascriptException: invalid return (unnamed script#1)
    at smartrics.rest.fitnesse.fixture.support.JavascriptWrapper.evaluateExpression(JavascriptWrapper.java:133)
    at smartrics.rest.fitnesse.fixture.support.JavascriptWrapper.evaluateExpression(JavascriptWrapper.java:104)
    at smartrics.rest.fitnesse.fixture.support.JSONBodyTypeAdapter.eval(JSONBodyTypeAdapter.java:51)
    at smartrics.rest.fitnesse.fixture.support.JSONBodyTypeAdapter.equals(JSONBodyTypeAdapter.java:82) ```

Any ideas?

**Comment by smartrics** [comment]
no idea right now

The err suggests that the block is evaluated as it should. Maybe try first
with a simpler javascript like always return true.

you should find some working code via Google.

**Comment by tigerqiu712** [comment]
hi ,
  i am using fitnesse in mac but when i running the default case it's show below error
slim:fitnesse.slim.SlimService
Date:	6:38:01 PM (CST) on Thursday, August 27, 2015
Test Page:	.RestFixtureInstallTest
Command:	java -cp fitnesse.jar:fitnesse.jar fitnesse.slim.SlimService 8087
Exit code:	1
Time elapsed:	10.613 seconds


Standard Error:
Error: Could not find or load main class fitnesse.slim.SlimService

!define TEST_SYSTEM {slim}

!path fitnesse.jar

| import |
| smartrics.rest.fitnesse.fixture |

| Table:smartrics.rest.fitnesse.fixture.RestFixture | http://www.w3school.com.cn |
| GET | /example/xmle/note.xml | 200 | Content-Type: text/xml | //body[text()="Don't forget the meeting!"]|

| Table:smartrics.rest.fitnesse.fixture.RestFixture | http://www.w3school.com.cn |
| GET | /example/xmle/note.xml | 200 | Content-Type: text/xml | /note/body[text()="Don't forget the meeting!"]|

how setting the path in mac OS

**Comment by smartrics** [comment]
Try put the absolute path to fitnesse.jar

!path /path/to/fitnesse/dot/jar

You will also need the path to the other rest fixture dependencies

**Comment by smartrics** [comment]
Not sure about macs but I usually start fitnesse like

java -jar fitnesse.jar

**Comment by tigerqiu712** [comment]
i am using below code
!define TEST_SYSTEM {slim}

!path fitnesse.jar

| import |
| smartrics.rest.fitnesse.fixture |

| Table:smartrics.rest.fitnesse.fixture.RestFixture | http://www.w3school.com.cn |
| GET | /example/xmle/note.xml | 200 | Content-Type: text/xml | //body[text()="Don't forget the meeting!"]|

| Table:smartrics.rest.fitnesse.fixture.RestFixture | http://www.w3school.com.cn |
| GET | /example/xmle/note.xml | 200 | Content-Type: text/xml | /note/body[text()="Don't forget the meeting!"]|

**Comment by tigerqiu712** [comment]
can you share your skype and check this?

**Comment by tigerqiu712** [comment]
even i change into below remain failed
slim:fitnesse.slim.SlimService
Date:	7:08:43 PM (CST) on Thursday, August 27, 2015
Test Page:	.RestFixtureInstallTest
Command:	java -cp fitnesse.jar:~/Users/tyler/git/FitnesseKit/RestFixture/target/dependencies/*:~/Users/tyler/git/FitnesseKit/RestFixture/target/smartrics-RestFixture-3.1-SNAPSHOT.jar:~/Users/tyler/git/FitnesseKit/RestFixture/slf4j-simple-1.6.6.jar fitnesse.slim.SlimService 8086
Exit code:	1
Time elapsed:	10.547 seconds


Standard Error:
Error: Could not find or load main class fitnesse.slim.SlimService

**Comment by tigerqiu712** [comment]
[java] SlimTable.SlimTable table:[[Table:Rest Fixture, <a href="http://localhost:8001">http://localhost:8001</a>], [let, spend, js, (%end% - %begin%) / 1000, ]]
     [java] SlimTable.SlimTable table:[[Table:smartrics.rest.fitnesse.fixture.RestFixture, <a href="http://www.w3school.com.cn">http://www.w3school.com.cn</a>], [GET, /example/xmle/note.xml, 200, Content-Type: text/xml, //body[text()="Don't forget the meeting!"]]]
     [java] SlimTable.SlimTable table:[[Table:smartrics.rest.fitnesse.fixture.RestFixture, <a href="http://www.w3school.com.cn">http://www.w3school.com.cn</a>], [GET, /example/xmle/note.xml, 200, Content-Type: text/xml, /note/body[text()="Don't forget the meeting!"]]]
     [java] WARNING: error registered in test system [null]
     [java] java.lang.NullPointerException
     [java] 	at fitnesse.testsystems.slim.SlimCommandRunningClient.writeString(SlimCommandRunningClient.java:205)
     [java] 	at fitnesse.testsystems.slim.SlimCommandRunningClient.invokeAndGetResponse(SlimCommandRunningClient.java:134)
     [java] 	at fitnesse.testsystems.slim.SlimTestSystem.processTable(SlimTestSystem.java:123)
     [java] 	at fitnesse.testsystems.slim.HtmlSlimTestSystem.processAllTablesOnPage(HtmlSlimTestSystem.java:51)
     [java] 	at fitnesse.testsystems.slim.SlimTestSystem.runTests(SlimTestSystem.java:100)
     [java] 	at fitnesse.testrunner.MultipleTestsRunner.executeTestSystemPages(MultipleTestsRunner.java:173)
     [java] 	at fitnesse.testrunner.MultipleTestsRunner.startTestSystemAndExecutePages(MultipleTestsRunner.java:101)
     [java] 	at fitnesse.testrunner.MultipleTestsRunner.internalExecuteTestPages(MultipleTestsRunner.java:86)
     [java] 	at fitnesse.testrunner.MultipleTestsRunner.executeTestPages(MultipleTestsRunner.java:68)
     [java] 	at fitnesse.responders.run.TestResponder.performExecution(TestResponder.java:273)
     [java] 	at fitnesse.responders.run.TestResponder.doExecuteTests(TestResponder.java:121)
     [java] 	at fitnesse.responders.run.TestResponder$TestExecutor.execute(TestResponder.java:205)
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
     [java] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [java] 	at java.lang.reflect.Method.invoke(Method.java:606)
     [java] 	at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.doInvoke(UberspectImpl.java:395)
     [java] 	at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.invoke(UberspectImpl.java:384)
     [java] 	at org.apache.velocity.runtime.parser.node.ASTMethod.execute(ASTMethod.java:173)
     [java] 	at org.apache.velocity.runtime.parser.node.ASTReference.execute(ASTReference.java:280)
     [java] 	at org.apache.velocity.runtime.parser.node.ASTReference.render(ASTReference.java:369)
     [java] 	at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:342)
     [java] 	at org.apache.velocity.runtime.directive.Parse.render(Parse.java:260)
     [java] 	at org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirective.java:207)
     [java] 	at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:342)
     [java] 	at org.apache.velocity.Template.merge(Template.java:356)
     [java] 	at org.apache.velocity.Template.merge(Template.java:260)
     [java] 	at fitnesse.html.template.HtmlPage.render(HtmlPage.java:81)
     [java] 	at fitnesse.responders.run.TestResponder.doSending(TestResponder.java:107)
     [java] 	at fitnesse.responders.ChunkingResponder.startSending(ChunkingResponder.java:70)
     [java] 	at fitnesse.http.ChunkedResponse.sendTo(ChunkedResponse.java:25)
     [java] 	at fitnesse.FitNesseExpediter.sendResponse(FitNesseExpediter.java:100)
     [java] 	at fitnesse.FitNesseExpediter.start(FitNesseExpediter.java:51)
     [java] 	at fitnesse.FitNesseServer.serve(FitNesseServer.java:28)
     [java] 	at fitnesse.FitNesseServer.serve(FitNesseServer.java:21)
     [java] 	at fitnesse.socketservice.SocketService$ServerRunner.run(SocketService.java:110)
     [java] 	at java.lang.Thread.run(Thread.java:745)
     [java] WARNING: error registered in test system [null]
     [java] java.lang.NullPointerException
     [java] 	at fitnesse.testsystems.slim.SlimCommandRunningClient.writeString(SlimCommandRunningClient.java:205)
     [java] 	at fitnesse.testsystems.slim.SlimCommandRunningClient.invokeAndGetResponse(SlimCommandRunningClient.java:134)
     [java] 	at fitnesse.testsystems.slim.SlimTestSystem.processTable(SlimTestSystem.java:123)
     [java] 	at fitnesse.testsystems.slim.HtmlSlimTestSystem.processAllTablesOnPage(HtmlSlimTestSystem.java:51)
     [java] 	at fitnesse.testsystems.slim.SlimTestSystem.runTests(SlimTestSystem.java:100)
     [java] SlimTable.SlimTable table:[[Table:smartrics.rest.fitnesse.fixture.RestFixture, <a href="http://www.w3school.com.cn">http://www.w3school.com.cn</a>], [GET, /example/xmle/note.xml, 200, Content-Type: text/xml, //body[text()="Don't forget the meeting!"]]]
     [java] 	at fitnesse.testrunner.MultipleTestsRunner.executeTestSystemPages(MultipleTestsRunner.java:173)
     [java] 	at fitnesse.testrunner.MultipleTestsRunner.startTestSystemAndExecutePages(MultipleTestsRunner.java:101)
     [java] 	at fitnesse.testrunner.MultipleTestsRunner.internalExecuteTestPages(MultipleTestsRunner.java:86)
     [java] SlimTable.SlimTable table:[[Table:smartrics.rest.fitnesse.fixture.RestFixture, <a href="http://www.w3school.com.cn">http://www.w3school.com.cn</a>], [GET, /example/xmle/note.xml, 200, Content-Type: text/xml, /note/body[text()="Don't forget the meeting!"]]]
     [java] 	at fitnesse.testrunner.MultipleTestsRunner.executeTestPages(MultipleTestsRunner.java:68)
     [java] 	at fitnesse.responders.run.TestResponder.performExecution(TestResponder.java:273)
     [java] 	at fitnesse.responders.run.TestResponder.doExecuteTests(TestResponder.java:121)
     [java] 	at fitnesse.responders.run.TestResponder$TestExecutor.execute(TestResponder.java:205)
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
     [java] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [java] 	at java.lang.reflect.Method.invoke(Method.java:606)
     [java] 	at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.doInvoke(UberspectImpl.java:395)
     [java] 	at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.invoke(UberspectImpl.java:384)
     [java] 	at org.apache.velocity.runtime.parser.node.ASTMethod.execute(ASTMethod.java:173)
     [java] 	at org.apache.velocity.runtime.parser.node.ASTReference.execute(ASTReference.java:280)
     [java] 	at org.apache.velocity.runtime.parser.node.ASTReference.render(ASTReference.java:369)
     [java] 	at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:342)
     [java] 	at org.apache.velocity.runtime.directive.Parse.render(Parse.java:260)
     [java] 	at org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirective.java:207)
     [java] 	at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:342)
     [java] 	at org.apache.velocity.Template.merge(Template.java:356)
     [java] 	at org.apache.velocity.Template.merge(Template.java:260)
     [java] 	at fitnesse.html.template.HtmlPage.render(HtmlPage.java:81)
     [java] 	at fitnesse.responders.run.TestResponder.doSending(TestResponder.java:107)
     [java] 	at fitnesse.responders.ChunkingResponder.startSending(ChunkingResponder.java:70)
     [java] 	at fitnesse.http.ChunkedResponse.sendTo(ChunkedResponse.java:25)
     [java] 	at fitnesse.FitNesseExpediter.sendResponse(FitNesseExpediter.java:100)
     [java] 	at fitnesse.FitNesseExpediter.start(FitNesseExpediter.java:51)
     [java] 	at fitnesse.FitNesseServer.serve(FitNesseServer.java:28)
     [java] 	at fitnesse.FitNesseServer.serve(FitNesseServer.java:21)
     [java] 	at fitnesse.socketservice.SocketService$ServerRunner.run(SocketService.java:110)
     [java] 	at java.lang.Thread.run(Thread.java:745)

**Comment by Thaoden** [comment]
Is it possible to seperate these into two different issues?

Even using `/* javascript */ return true; `, the same exception is thrown. Is it a Firefox thingie, maybe?

**Comment by tigerqiu712** [comment]
sorry for that , the issue was solved, that's path issue ,should be use  below in MAC 
!define TEST_SYSTEM {slim}


!path /Users/tyler/git/FitnesseKit/RestFixture/target/dependencies/*
!path /Users/tyler/git/FitnesseKit/RestFixture/target/smartrics-RestFixture-3.1-SNAPSHOT.jar
!path /Users/tyler/git/FitnesseKit/RestFixture/slf4j-simple-1.6.6.jar


| Table:smartrics.rest.fitnesse.fixture.RestFixture | http://www.w3school.com.cn |
| GET | /example/xmle/note.xml | 200 | Content-Type: text/xml | //body[text()="Don't forget the meeting!"]|

| Table:smartrics.rest.fitnesse.fixture.RestFixture | http://www.w3school.com.cn |
| GET | /example/xmle/note.xml | 200 | Content-Type: text/xml | /note/body[text()="Don't forget the meeting!"]|

**Comment by Thaoden** [comment]
As it turns out, I have to leave out the `return` statements. The following code block is working fine:

```
/* javascript */ var found = false; for(var x in jsonbody){if (jsonbody[x].Host.LoginId=="abc") {found = true;} } found;
```

**Comment by smartrics** [comment]
@thaoden Well spot
