### ISSUE TITLE
Problem verifying headers

### ISSUE THREAD

**Issue by Thaoden** [smartrics/RestFixture#129]
Hi,

I'm trying to verify some headers after a POST operation. This is the result:
```
Location:http://localhost:8484/api/Guests/Of/abc?guestLoginId=el.bs01
expected

Cache-Control : no-cache
Pragma : no-cache
Content-Type : application/json; charset=utf-8
Expires : -1
Location : http://localhost:8484/api/Guests/Of/abc?guestLoginId=el.bs01
Server : Microsoft-IIS/7.5
X-AspNet-Version : 4.0.30319
X-Powered-By : ASP.NET
Date : Mon, 31 Aug 2015 10:02:55 GMT
Content-Length : 96
actual

not found: [Location : http://localhost:8484/api/Guests/Of/abc?guestLoginId=el.bs01]
```

Obviously, `expected` can be found in `actual`, so why is it `not found`?

**Comment by smartrics** [comment]
the expectation cell is interpreted as a regex, but there's an issue in the parsing so the ? is misinterpreted

try use this instead

!- Location:http://localhost:8484/api/Guests/Of/abc.guestLoginId=el.bs01 -!

eg replace the '?' with a '.'

**Comment by Thaoden** [comment]
This worked. Many thanks.
As a side note, your hint it was the "?" throwing led me to escaping it:
`!- Location:http://localhost:8484/api/Guests/Of/abc\?guestLoginId=el.bs01 -!`. This worked too
