### ISSUE TITLE
RestFixture can support Access_control_CORS?

### ISSUE THREAD

**Issue by tigerqiu712** [smartrics/RestFixture#132]
the RestFixture can supportAccess_control_CORS? 
Refer webiste
 https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS

**Comment by smartrics** [comment]
CORS applies to browser sessions only for HTTP requests to a domain different than the one where the original page was loaded from.

RestFixture is not a browser, rather an HTTP client, where each request is independent from the other. So basically yes, you can run any query to any resource irrespective of the domain
