### ISSUE TITLE
How Smartrics work with "Soap header WS-security" ?

### ISSUE THREAD

**Issue by diansu** [smartrics/RestFixture#133]
I am new in Smartrics. I know Smartrics is able to use below setting to work with "Http Header authentication basic". I am wondering how Smartrics work with "Soap header WS-security" by using "username/password".  Could you provide an example? 

| Table: Rest Fixture Config  |
| http.basicauth.username | user |
| http.basicauth.password | abcd |

Thanks in advance,
-Dian

**Comment by smartrics** [comment]
Hello - what are you trying to do?

**Comment by diansu** [comment]
I have a Soap API to test.This API exposed as web service WS-security(WSS) policy is applied by default. I have to  include SOAP header with WSS info(username, password, password type) in it. So how can I set these info in Smartrics "setHeader" section? 

Thanks,
-Dian

**Comment by smartrics** [comment]
Hi RestFixture doesn't support SOAP services

You have to build your Fitnesse extension or use another tool like SoapUI

**Comment by diansu** [comment]
Thanks for your clarification.
