### ISSUE TITLE
want to add extra header ,but seem not not work

### ISSUE THREAD

**Issue by tigerqiu712** [smartrics/RestFixture#135]
Hi , 
   i want to add extra header in get method ,like
 | setHeader |X-Requested-With: XMLHttpRequest|	,but it's can not work

| Table:smartrics.rest.fitnesse.fixture.RestFixture | http://**/ | 
| setHeader |Host:*
| setHeader |User-Agent:Mozilla/5.0 (Windows NT 6.1; rv:6.0.2) Gecko/20100101 Firefox/6.0.2|  			
| setHeader |Accept: application/json, text/javascript, */*; q=0.01|        
| setHeader |Accept-Language: zh-CN,zh;q=0.8,en-US;q=0.5,en;q=0.3|
| setHeader |Accept-Encoding: gzip, deflate|	 
| setHeader |refer: "http:/*   	  
| setHeader |Connection:keep-alive| 
| setHeader |TOKEN: *
| setHeader |X-Requested-With: XMLHttpRequest|	
| GET | !-/*!| 200 | Content-Type: application/json ||{"code":"200","msg":"ok","data":"unlogin"}|

the server can not get the token form set header,  are we supports  this function

**Comment by smartrics** [comment]
Hi 
multiple headers must be set in the same cell. for example

| setHeaders |!--
User-Agent:Mozilla/5.0 (Windows NT 6.1; rv:6.0.2) Gecko/20100101 Firefox/6.0.2
Accept: application/json, text/javascript, /; q=0.01
Accept-Language: zh-CN,zh;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate
refer: "http:/*
Connection:keep-alive
TOKEN: *
X-Requested-With: XMLHttpReques
--!|

all the above headers will be sent with the next request

A setHeader (or setHeaders) will override the previous setHeader (note it's setHeader, not addHeader)

**Comment by tigerqiu712** [comment]
the problem is  TOKEN is order,it's must at position 6, HashMap will not keep the order , so we need change HashMap to LinkedHashMap

**Comment by smartrics** [comment]
Why is it important for you to keep order in headers?

**Comment by jplambert** [comment]
Indeed the ordering should not be meaningful in headers.

But maybe @tigerqiu712 wants to check this map thereafter and so it would make his like easier to have a consistent order.

One way to work around that might be to define some Slim custom comparators that checks elements in a set, independently of the order. That's something I have already done in the past.
