### ISSUE TITLE
Could not invoke constructor for "smartrics.rest.test.fitnesse.fixture.LetTestActionFixture[0]"

### ISSUE THREAD

**Issue by diansu** [smartrics/RestFixture#136]
Hi @smartrics,
I suppose to use Smartrics V4.0 new feature "proper support of Slim Symbols as described in Issue #52".      Below is my test case:

!define TEST_SYSTEM {slim}
!path C:\smartrics-RestFixture-4.0\target\smartrics-RestFixture-4.0.jar
!path C:\smartrics-RestFixture-4.0\target\dependencies\*
!|import          |
|slim             |
!| Import |
| smartrics.rest.fitnesse.fixture |

|Table:smartrics.rest.fitnesse.fixture.RestFixture | http://localhost:9595 |
| GET | /RestFixtureInstallTest?rss | | | //title[text()='FitNesse:']|
| let | title | body |//title/text()||

|script|smartrics.rest.test.fitnesse.fixture.LetTestActionFixture|
|symbolName|title| 
|check|symbolValue|FitNesse:|

I am able to successfully receive the GET response and assign value to title by "let" in the first table.  But encountered issue "Could not invoke constructor for smartrics.rest.test.fitnesse.fixture.LetTestActionFixture[0]" in the second table. Seems can not find the "LetTestActionFixture" class. So is above code the proper scenario to pass the RestFixture symbol to Fitneese ? if not, what is the correct scenario? please indicate.

Thanks in advance,
-Philip

**Comment by smartrics** [comment]
Hello - LetTestActionFixture is in RestFixtureLiveDocs project https://github.com/smartrics/RestFixtureLiveDoc

it;s a very basic fixture you can reuse by copy/paste - but its use is unnecessary. 

Once the |let| command has executed correctly, the "title" symbol is mapped to the result of xpath.
you can access in any subsequent RestFixture fia %title% or in any generic fixture using the ${title} syntax.

**Comment by diansu** [comment]
Hi @smartrics ,

Thank for your response! Currently I am able to use %title% in subsequent RestFixture. My question in my other Fitnesse fixtures, if I want to use the value of %title%, what should I do? for example:

|Table:smartrics.rest.fitnesse.fixture.RestFixture | http://localhost:9595 |
| GET | /RestFixtureInstallTest?rss | | | //title[text()='FitNesse:']|
| let | title | body |//title/text()||

!|com.mycopany.application.testrun|
|my title|show my title?|
|%title%||

But above code doesn't work. because my fixture "com.mycopany.application.testrun" can't get value of %title% properly. So what is the correct way to pass the RestFixture symbol "%title%" value to other fitnesse fixtrue?

Thanks,
-Philip

**Comment by diansu** [comment]
I think my question is similar as  Issue #52.

Thanks,
-Philip

**Comment by jplambert** [comment]
Hi @diansu it is indeed similar to issue #52 and you should be able to use the same fix.

When using "let", it puts the value in a Slim symbol.

The %...% syntax is only supported by RestFixture. In other fixtures, you should use the $... syntax like with any Slim symbol. Have a look at FitNesse doc: http://www.fitnesse.org/FitNesse.UserGuide.WritingAcceptanceTests.SliM.SymbolsInTables

Please note that this is not to be mistaken with the ${...} syntax, which is used to reference *variables*, which are statically defined and replaced in the FitNesse pages at the time of HTML generation. Whereas *symbols* are dynamic variables assigned at run-time by the SUT.

**Comment by smartrics** [comment]
I see - it should be, all things working,

${title}

**Comment by jplambert** [comment]
@smartrics you mix up FitNesse variables and Slim symbols ;-)

Must be $title

**Comment by jplambert** [comment]
This is one of the things I don't like about FitNesse: two sets of programming variables, not the same syntax to use them, but the two syntax are so slightly similar that you can easilly mix them up.

In addition, the syntax looks like the well-known shell variables, but in shell the two syntaxes describe the same thing. So the FitNesse syntax is just familiar enough to make sure you'll be mistaken.

**Comment by smartrics** [comment]
Thanks @jplambert - I agree, it's confusing...

**Comment by diansu** [comment]
It resolved my question! Much thanks to @smartrics and @jplambert !

-Philip

**Comment by nuggit32** [comment]
I'm using fit and do not seem to be about to use the let symbols in my fixture using $symbol for my column fixture.  It passes the literal $symbol instead of the value.  Any suggestions?
Example.
|let|status_code|js|response.statusCode||

!|com.job.fixture.SomeColumnFixture|
|originalString|=dowork()|
|$status_code|returnedValue|
