### ISSUE TITLE
 Could not invoke constructor for smartrics.rest.fitnesse.fixture.RestFixture[1]

### ISSUE THREAD

**Issue by alexmasselot** [smartrics/RestFixture#137]
Hi 
I'm trying  Rest Fixture 3.1 + fitnesse 20150814, with the most basic example.
And tried  java 7 and 8

    !define TEST_SYSTEM {slim}

    !path /Users/alex/local/fitnesse/fixtures/RestFixture-4.0/dependencies/*.jar
    !path /Users/alex/local/fitnesse/fixtures/RestFixture-4.0/smartrics-RestFixture-4.0.jar 
    !path /Users/alex/local/fitnesse/fixtures/RestFixture-4.0/slf4j-simple-1.6.6.jar

    !|import|
    |smartrics.rest.fitnesse.fixture|

    !|Table:smartrics.rest.fitnesse.fixture.RestFixture | http://localhost:8070 |
    | GET | /RestFixtureInstallTest?rss | | | //title[text()='RestFixtureInstallTest']|

But I consistently get: Could not invoke constructor for smartrics.rest.fitnesse.fixture.RestFixture[1].
I cannot find a detailed stack trace and looks to me that the files are present (see below).
But I still mut be missing something big.

Thanks for the help
Alex

    ls /Users/alex/local/fitnesse/fixtures/RestFixture-4.0/dependencies/*.jar
    /Users/alex/local/fitnesse/fixtures/RestFixture-4.0/dependencies/JavaEWAH-0.7.9.jar
    /Users/alex/local/fitnesse/fixtures/RestFixture-4.0/dependencies/commons-codec-1.2.jar
    /Users/alex/local/fitnesse/fixtures/RestFixture-4.0/dependencies/commons-collections-3.2.1.jar
    /Users/alex/local/fitnesse/fixtures/RestFixture-4.0/dependencies/commons-httpclient-3.1.jar
    /Users/alex/local/fitnesse/fixtures/RestFixture-4.0/dependencies/commons-lang-2.6.jar
    /Users/alex/local/fitnesse/fixtures/RestFixture-4.0/dependencies/commons-logging-1.0.4.jar
    /Users/alex/local/fitnesse/fixtures/RestFixture-4.0/dependencies/diffutils-1.3.0.jar
    /Users/alex/local/fitnesse/fixtures/RestFixture-4.0/dependencies/hamcrest-all-1.3.jar
    /Users/alex/local/fitnesse/fixtures/RestFixture-4.0/dependencies/hamcrest-core-1.1.jar
    /Users/alex/local/fitnesse/fixtures/RestFixture-4.0/dependencies/htmllexer-2.1.jar
    /Users/alex/local/fitnesse/fixtures/RestFixture-4.0/dependencies/htmlparser-2.1.jar
    /Users/alex/local/fitnesse/fixtures/RestFixture-4.0/dependencies/httpclient-4.1.3.jar
    /Users/alex/local/fitnesse/fixtures/RestFixture-4.0/dependencies/httpcore-4.1.4.jar
    /Users/alex/local/fitnesse/fixtures/RestFixture-4.0/dependencies/jettison-1.3.2.jar
    /Users/alex/local/fitnesse/fixtures/RestFixture-4.0/dependencies/jsch-0.1.50.jar
    /Users/alex/local/fitnesse/fixtures/RestFixture-4.0/dependencies/json-20140107.jar
    /Users/alex/local/fitnesse/fixtures/RestFixture-4.0/dependencies/junit-4.10.jar
    /Users/alex/local/fitnesse/fixtures/RestFixture-4.0/dependencies/mockito-all-1.9.0.jar
    /Users/alex/local/fitnesse/fixtures/RestFixture-4.0/dependencies/org.eclipse.jgit-3.6.2.201501210735-r.jar
    /Users/alex/local/fitnesse/fixtures/RestFixture-4.0/dependencies/rhino-1.7R3.jar
    /Users/alex/local/fitnesse/fixtures/RestFixture-4.0/dependencies/slf4j-api-1.6.6.jar
    /Users/alex/local/fitnesse/fixtures/RestFixture-4.0/dependencies/smartrics-RestClient-2.1.jar
    /Users/alex/local/fitnesse/fixtures/RestFixture-4.0/dependencies/stax-api-1.0.1.jar
    /Users/alex/local/fitnesse/fixtures/RestFixture-4.0/dependencies/velocity-1.7.jar
    /Users/alex/local/fitnesse/fixtures/RestFixture-4.0/dependencies/xmlpull-1.1.3.1.jar
    /Users/alex/local/fitnesse/fixtures/RestFixture-4.0/dependencies/xpp3_min-1.1.4c.jar
    /Users/alex/local/fitnesse/fixtures/RestFixture-4.0/dependencies/xstream-1.4.2.jar

    ls /Users/alex/local/fitnesse/fixtures/RestFixture-4.0/smartrics-RestFixture-4.0.jar 
    /Users/alex/local/fitnesse/fixtures/RestFixture-4.0/smartrics-RestFixture-4.0.jar

    ls /Users/alex/local/fitnesse/fixtures/RestFixture-4.0/slf4j-simple-1.6.6.jar
    /Users/alex/local/fitnesse/fixtures/RestFixture-4.0/slf4j-simple-1.6.6.jar

**Comment by smartrics** [comment]
hi - I think you mean RestFixture 4.0 (as your paths show).

Anyway - it works for me. Not sure why its not working for you (you seem to be running in a mac - never tried in that OS myself)

I have downloaded fitnesse http://www.fitnesse.org/FitNesseDownload (fitnesse-standalone.jar), executed it via 

java -jar fitnesse-standalone.jar

then added the page as you did above and run it correctly.

One thing you could do it past the Command being executed. you can find it by clicking on the "Test executed OK" green button at the top of the page after the test has completed its execution.

moreover you should be able to paste that command in the console and run it manually.

**Comment by alexmasselot** [comment]
Hei

Thanks for you answer. I was just about to answer that I already tried all that twenty times DOH.
But, I redid exactly everything an 21time.

And in the command,  we can spot a space after smartrics-RestFixture-4.0.jar and the following colon.

    xstream-1.4.2.jar:/Users/alex/local/fitnesse/fixtures/RestFixture-4.0/smartrics-RestFixture-4.0.jar :/Users/a

And this was the culprit. In fact, there was a trailing space at the line

    !path /Users/alex/local/fitnesse/fixtures/RestFixture-4.0/smartrics-RestFixture-4.0.jar 

Thanks again fo the time, and I guess that should deserve a issue on the Fitnesse thread.
Have a good one,
Alex
