### ISSUE TITLE
let and subsequent check

### ISSUE THREAD

**Issue by alexmasselot** [smartrics/RestFixture#139]
Hi,

if my json response is a list of objects, is it possible to catch one element with a let and then check various property values?

    | let | oneObj | js | response.jsonbody[2] | |

Thanks
Alex

**Comment by jplambert** [comment]
It is possible, though I don't have the exact syntax in mind. If you want to extract some sub-element from the response body interpreted as JSON, you'll have to write some JavaScript to do that. Nothing hard, really, but eventually you'll have to dig into JavaScript.

**Comment by smartrics** [comment]
actually i don't think it's possible. 'let' only manages strings.

**Comment by alexmasselot** [comment]
thanks. That fits my observations
Have a good one
Alex
