### ISSUE TITLE
POST processes, but RestFixture throws exception ""

### ISSUE THREAD

**Issue by KateDavis** [smartrics/RestFixture#140]
Odd error after processing:

POST
Execution of Post caused exception 'You must specify a body cell'
201
Date : Thu, 12 Nov 2015 20:09:30 GMT
Content-Type : application/json
Content-Length : 0

Raw Code with API Key removed. This appears to work, given the 201 return code. Is this an error in the test, or a fixture issue?

!|Table:Rest Fixture Config|
|restfixture.default.headers|Content-Type:application/json|
 
!|Table: Rest Fixture | !- http://qa-app-01.internal.emerlyn.com:8190/inventory/dispense-! |
|setHeader|!-X-API-KEY:XXXXXXXX
Content-Type:application/json-!|
|setBody|!-{"pharmacy": "15",
"department": "Portland",
"itemIdentifier": "67877022205",
"description": "Gabapentin",
"quantity": "10",
"transactionType": "allocate",
"rxNumber": "5222574",
"rxTimestamp": "2015-11-12T08:56:51.611Z",
"daw": "1"}-!|
| POST |  |  |  |

**Comment by smartrics** [comment]
Hello 

this 

| POST | | | |

looks incorrect as its not specifying the URI path and it must have 5 cells in total

| verb | uri | expected code | expected headers | expected body |

try

| POST | / |  |  |  |


leave empty cells in order to skip expectation matches

**Comment by KateDavis** [comment]
awesome. thank you for your help, and thank you for writing this great fixture.
