### ISSUE TITLE
Passing LET Symbol to fit column fixture

### ISSUE THREAD

**Issue by nuggit32** [smartrics/RestFixture#141]
Related to issue #136 
I'm using fit and do not seem to be about to use the let symbols in my fixture using $symbol for my column fixture. It passes the literal $symbol instead of the value. Any suggestions?
Example.
|let|status_code|js|response.statusCode||

!|com.job.fixture.SomeColumnFixture|
|originalString|=dowork()|
|$status_code|returnedValue|

**Comment by smartrics** [comment]
Hello - it looks like you have the incorrect syntax. Try 

!|com.job.fixture.SomeColumnFixture|
|originalString=|=dowork()|
|status_code|returnedValue|

**Comment by nuggit32** [comment]
I got the Slim to work as

!|com.cri.fixture.somefixture|
|key_value|method?|
|$key_value|$return_value=|
