### ISSUE TITLE
Assertions in GET response with JSON format

### ISSUE THREAD

**Issue by joshbp81** [smartrics/RestFixture#146]
Hello,

I've been using RestFixture for a while and it's been very helpful so far. But I just found a problem that is driving me mad. 

Part of the response I'm receiving is the following:

...
"info_service_asset_ref":   {
    "include":     {
      "@parse": "text",
      "@link": "documents/20-03562348/section/10"
    },
    "service_id_ref": "83262115",
    "product_name_ref": "Some name",
    "phone_number_ref": "0123456789"
  },
...

When I try to check the value in "service_id_ref" or other, everything works fine. The problem is when I try to get "@parse" or "@link" under "include". I'm not able to find the objects and that's crucial for my tests to work. Any idea of how to solve this?

Thanks a million in advance for your help!

**Comment by smartrics** [comment]
how are you trying to assert the value of the @parse/@link attribute?

Have you tried

jsonbody.info_service_asset_ref.include["@parse"]

?

**Comment by joshbp81** [comment]
Tried several methods but my JS knowledge is very poor. 

That one works like a charm!
