### ISSUE TITLE
POST Response code 500 when body contains a £

### ISSUE THREAD

**Issue by haroon-sheikh** [smartrics/RestFixture#147]
When I do a post request with body that has a pound sign, I'm getting a 500 error.
But if I use a html entity then it works as expected.
I really need to be posting the symbol instead.

Would you be able to advise please?

**Comment by smartrics** [comment]
Hi I am assuming that you have tried to post to your server directly and
that it works?

**Comment by haroon-sheikh** [comment]
yeah @smartrics, I've tried posting the same payload (with pound sign) using getpostman.com and it works.

**Comment by haroon-sheikh** [comment]
@smartrics ive tried running the same POST test on a Unix based machine and it seems to work. Its probably just an issue with my windows machine. Any idea what it could be?

**Comment by smartrics** [comment]
No really... maybe the char encoding

A tcpdump server side may show what s actually been sent

**Comment by smartrics** [comment]
i am closing this issue as it looks related to your environment
