### ISSUE TITLE
setting cookie for the application (to login)

### ISSUE THREAD

**Issue by mkyudi** [smartrics/RestFixture#148]
In my project there is one SSO cookie that i need to set.
I can hardcode that very easily using 
| setHeader | Cookie: MKSSO=04I114AAAAyUh9AAAAAreytryeryrtAAEAAAAAgABAAAADHdoaXRld2F0ZXJxYQACAAAADTEwLjI0Ni41MS4yNDYABQAAAAQBM55xAAYAAAAEVngTbwAQAAAAgKcV2C4DqIqdyXZF+OxwoyZC9PDgKivHVlgt/WSJZl0dr1HNiAsNertyertybZODRoXrCR/6PHfh5s+k0MVa32crHkMPiEKUnLeOWQAF8vEbHaRFbZRBshG2PxmWjSEnGIiQDs/sHFWWEk+2CoXflbfd7juxOCg25s4J5uwSKlHvjTPUaO4w |

Question: I want to generalize it, How can i do that? I dont want to give this hardcoded cookie. I have one standalone java method that can return this cookie value. (if i can use that).

I tried using below code as well, but didn't worked

!define TEST_SYSTEM {slim}
!path H:/Data/Code/FitnesseTest/mk-service-sandbox-SNAPSHOT/lib/*

 !define name {value}  
 
| Import |
| smartrics.rest.fitnesse.fixture |
| smartrics.rest.test.fitnesse.fixture|

| Table: Rest Fixture Config  |
| http.basicauth.username | MKSSO |
| http.basicauth.password | 4I114AAAAyUh9AAAAAreytryeryrtAAEAAAAAgABAAAADHdoaXRld2F0ZXJxYQACAAAADTEwLjI0Ni41MS4yNDYABQAAAAQBM55xAAYAAAAEVngTbwAQAAAAgKcV2C4DqIqdyXZF+OxwoyZC9PDgKivHVlgt/WSJZl0dr1HNiAsNertyertybZODRoXrCR/6PHfh5s+k0MVa32crHkMPiEKUnLeOWQAF8vEbHaRFbZRBshG2PxmWjSEnGIiQDs/sHFWWEk+2CoXflbfd7juxOCg25s4J5uwSKlHvjTPUaO4w |

| Table:smartrics.rest.fitnesse.fixture.RestFixture | http://localhost.mk.com:8080 |
| GET | /rest/hello-world/hello | | | Hello World |

**Comment by smartrics** [comment]
you could use a separate fixture (http://fitnesse.org/FitNesse.UserGuide.FixtureGallery.BasicFitFixtures.ColumnFixture) to execute your java method that returns the cookie value

!|your.fixture.CookieClass|
|newCookie?|
|$cookie_value=|

then

| setHeader | Cookie: $cookie_value |

**Comment by mkyudi** [comment]
Thanks for quick reply. Will try and let you know.
Thanks again :)

**Comment by mkyudi** [comment]
Thanks
It worked. Sample code:

!|your.fixture.CookieClass|
|newCookie?|
|$cookie_value=|

| Table:smartrics.rest.fitnesse.fixture.RestFixture | http://localhost.mk.com |
| setHeader | Cookie: $cookie_value |
| GET | /rest/takeRes/getUrl | | | Hello Rest |

Another issue is in matching regular expression ... will raise a new one for that.

**Comment by nirajyadav** [comment]
Can you please help... 

| Import |
| smartrics.rest.fitnesse.fixture |
| smartrics.rest.test.fitnesse.fixture|

| Table: Rest Fixture Config |
| http.basicauth.username | MKSSO |
| http.basicauth.password | abc |

|Table:smartrics.rest.fitnesse.fixture.RestFixture|${resourceUrl}                                                         |
|setHeader                                        |!-Content-Type : application/json
-!                                        |
|setBody                                          |{ "type" : "credentials" }                                             |
|POST                                             |/customers/auth?client_id=${clientId}|      |                         ||
|let                                              |token                                |header|Authorization:Bearer (.*)||


This is not working .. 
it says

{"type":"AuthorizationBasicMissingException","message":"Missing credentials: Add a Authorization:Basic header with base64 encoded username:password."}}


I have used my correct username and password. 

Any clue
