### ISSUE TITLE
Issue in regular expression matching - "no regex match"

### ISSUE THREAD

**Issue by mkyudi** [smartrics/RestFixture#149]
Getting issue : no regex match
Tried escaping the special characters as well, but no luck :(

sample code:
| Table:smartrics.rest.fitnesse.fixture.RestFixture | http://localhost.mk.com:8080 |
| GET | !-/rest/takeRes/getUrl-! | | | !-http://reso.mk.com/show/HAR+POT-! |

Thanks.

**Comment by smartrics** [comment]
never tried with a non json body response but you could try use a javascript block like

| GET | /rest/takeRes/getUrl | | | !- /* javascript */
jsonbody.response == 'http://reso.mk.com/show/HAR+POT'
-!|

**Comment by mkyudi** [comment]
Still getting "no regex match:"

**Comment by smartrics** [comment]
Oh I may have misunderstood your issue

Can you share the whole http response including the headers

**Comment by mkyudi** [comment]
Hi Smartrics

Fitnesse code:
| Table:smartrics.rest.fitnesse.fixture.RestFixture | http://localhost.mk.com:8080 |
| setHeader | Cookie: abcdefaksjflasd |
| GET | !-/rest/takeRes/getUrl-! | | | !-http://reso.mk.com/show/HAR+POT-! |

Response from rest call (a string in URL form) :-
http://reso.mk.com/show/HAR+POT

Thanks,

**Comment by smartrics** [comment]
i need the Content-Type header

On 22 December 2015 at 13:50, mkyudi <notifications@github.com> wrote:

> Hi Smartrics
>
> Fitnesse code:
> | Table:smartrics.rest.fitnesse.fixture.RestFixture |
> http://localhost.mk.com:8080 |
> | setHeader | Cookie: abcdefaksjflasd |
> | GET | !-/rest/takeRes/getUrl-! | | | !-http://reso.mk.com/show/HAR+POT-!
> |
>
> Response from rest call (a string in URL form) :-
> http://reso.mk.com/show/HAR+POT
>
> Thanks,
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/smartrics/RestFixture/issues/149#issuecomment-166622741>
> .
>



-- 
Regards,

 Fabrizio

**Comment by mkyudi** [comment]
content-Type is text/plain

Complete response header:----
Date : Tue, 22 Dec 2015 15:00:28 GMT
Set-Cookie : abcdefxxxx==;Path=/
Expires : Thu, 01 Jan 1970 00:00:00 GMT
Set-Cookie : x-authenticated-principal=mkqa;Path=/
Content-Type : text/plain
Content-Length : 65

**Comment by smartrics** [comment]
because the content type it's text/plain it's expecting to match the body with a regular expression

the regex matching your url is

try to start with

| GET | !-/rest/takeRes/getUrl-! | | | http:.+ |

then you can improve your regex for more accurate matching like

http:\/\/reso\.mk\.com\/show\/HAR\+POT

**Comment by mkyudi** [comment]
Hi Smartrics, Thanks for your inputs.
As I mentioned in my top post, I tried escaping all special characters (specially the plus (+) sign is creating problem). 
After escaping these characters it will not produce any error but will not pass the test case as well.

In the results (last column) have two rows, i.e. expected and actual. Whereas test case is expecting just one row with one value in Green colour background.

**Comment by mkyudi** [comment]
Thanks Smartrics, I think this is designed as such. You may want to enhance it in future :)
You did a great job by developing this RestFixture.
