### ISSUE TITLE
Matching response on jsonbody

### ISSUE THREAD

**Issue by fatmanmclone90** [smartrics/RestFixture#150]
I cant't seem to get any expected results to match on the jsonbody response.  I've tried various permutations and using the javascript matching.

Response looks from a GET looks like:

HTTP/1.1 200 OK
Cache-Control: no-cache
Pragma: no-cache
Content-Type: application/json; charset=utf-8
Expires: -1
Server: Microsoft-IIS/8.5
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET
Date: Thu, 24 Dec 2015 19:39:44 GMT
Content-Length: 61

[{"Id":1,"PupilID":987,"IndexNumber":"123"},
{"Id":2,"PupilID":789,"IndexNumber":"321"}]

I've tried:

|table:smartrics.rest.fitnesse.fixture.RestFixture| http://kcpe.qa.bridge.ac.ke:82 |overridesContentHandlerConfig|
| GET |/Api/Message/GetPupilIndexNumbersWithNoScores |200 |Content-Length:[\d]|!- /* javascript */
jsonbody.response == '[{"Id":1,"PupilID":987,"IndexNumber":"123"},
{"Id":2,"PupilID":789,"IndexNumber":"321"}]' [{"Id":8233,"PupilID":100136001,"IndexNumber":"11230410311"}]
-!|

|table:smartrics.rest.fitnesse.fixture.RestFixture| http://kcpe.qa.bridge.ac.ke:82 |overridesContentHandlerConfig|
| GET |/Api/Message/GetPupilIndexNumbersWithNoScores |200 |Content-Length:[\d]|/* javascript */ var s = new String(jsonbody.response); s.indexOf("PupilID") > - 1;|

|table:smartrics.rest.fitnesse.fixture.RestFixture| http://kcpe.qa.bridge.ac.ke:82 |overridesContentHandlerConfig|
| GET |/Api/Message/GetPupilIndexNumbersWithNoScores |200 |Content-Length:[\d]| /* javascript */  jsonbody.Id == 123|

Any help would be much appreciated.

**Comment by mkyudi** [comment]
Not sure, but seems your response is array of json objects instead of one json.
If the json is {"Id":1,"PupilID":987,"IndexNumber":"123"}, try below code:

| GET | /restTest/test/yourPath | | Content-Type : application/json | |
| let | body_value | js | response.jsonbody | |
| let | body_value | js | response.jsonbody.Id | 1 |

Thanks,

**Comment by smartrics** [comment]
The expression should be for each array element

response.jsonbody [0].id

**Comment by fatmanmclone90** [comment]
Thanks for the support.  Yes sorry for not explaining but I am expecting an array of objects to be returned.

The winning formula was:

|table:smartrics.rest.fitnesse.fixture.RestFixture| http://kcpe.qa.bridge.ac.ke:82 |overridesContentHandlerConfig|
| GET |/Api/Message/GetPupilIndexNumbersWithNoScores |200 |Content-Length:[\d]||
| let | body_value | js | response.jsonbody[0].Id | 3072 |
| let | body_value | js | response.jsonbody.length | 10.0 |
