### ISSUE TITLE
cannot evaluate json body if node contains a colon

### ISSUE THREAD

**Issue by haroon-sheikh** [smartrics/RestFixture#152]
Im verifying a json feed using jsonbody but one of the nodes contains a colon and hence it's failing to evaluate.

```bash
java.lang.IllegalArgumentException: Cannot evaluate 'jsonbody.imageFormats.16:9[0].width=="61"'
```
Can someone please advise on this?

**Comment by mkyudi** [comment]
That's not a valid Json in that case. Try putting values in double quotes ("")

**Comment by mukhark** [comment]
The solution may be similar to when a json name contains '@'. Look at [issue 146](https://github.com/smartrics/RestFixture/issues/146) and try the solution suggested there.

**Comment by smartrics** [comment]
Try Eval with

jsonbody.imageFormats["16:9"][0].width=="61"

**Comment by haroon-sheikh** [comment]
thanks @smartrics @mkyudi @mukhark. The double quotes worked for me. :)
