### ISSUE TITLE
How to pass output of one testCase to next testCase as parameter

### ISSUE THREAD

**Issue by mkyudi** [smartrics/RestFixture#153]
I have a requirement where in first testcase I will call "/getAllOrders" to fetch all the existing orders in json format. and in the next testcase I need to pass one orderId as parameter "/rest/getDetails?orderId=321" where 321 is first orderId from firstTestCase.

Thanks.

**Comment by smartrics** [comment]
You may try let the orderId in a symbol then reuse the symbol

|let| id| ...

/rest/getDetails?orderId=%id%

**Comment by mkyudi** [comment]
Thanks :)
