### ISSUE TITLE
body:xml:matchAll using "double root" inserts "<?xml version="1.0" encoding="UTF-8"?>" into each returned node

### ISSUE THREAD

**Issue by BrakTalk** [smartrics/RestFixture#154]
We have a let statement:

|let|completePersonNames|body:xml:matchAll|//profile//personname||

There are lastname nodes in two different areas of the document which is why we are establishing a root and then establishing another root to get all instances of "lastname" and we are wanting to create an output like so:

`<lastname>AARON</lastname> 
<lastname>AARON</lastname> 
<lastname>AARON</lastname> 
<lastname>AARON</lastname> 
<lastname>AARON</lastname>`

But we are getting:

`<lastname>AARON</lastname> 
<?xml version="1.0" encoding="UTF-8"?><lastname>AARON</lastname> 
<?xml version="1.0" encoding="UTF-8"?><lastname>AARON</lastname> 
<?xml version="1.0" encoding="UTF-8"?><lastname>AARON</lastname> 
<?xml version="1.0" encoding="UTF-8"?><lastname>AARON</lastname> `

Any guesses as to why this is being inserted into our body:xml string?

The interesting thing is, this doesn't appear to happen on all systems.  The above behavior is on a Win7 box.  Running Fitnesse on a Windows 2008 server does not exhibit this behavior.  This almost suggests a startup parameter that might be required?

Thanks,
Mason

**Comment by smartrics** [comment]
Hi - it's very odd. could it be some class shadowing happening on the system?
Or maybe differences in the JVM?

I am using starndard DOM API.

Unfortunately I don't have the means to reproduce it as you explain. 
If you can, it will help to run a test program using the underlying class used by Rest Fixture let.

The class is smartrics.rest.fitnesse.fixture.support.Tools and the method is #extractXPath(Map<String, String> ns, String xpathExpression, String content)

you should be able to reproduce the issue by running a java main that executes the method and hopefully get to the bottom of the issue.

If any code change is required I'd be happy to consider teh merge of a pull request
