### ISSUE TITLE
Setting multiple headers where at least one value in name/value pair is a variable, variable not populated

### ISSUE THREAD

**Issue by BrakTalk** [smartrics/RestFixture#155]
According to this [link](http://goo.gl/JiaooW), multiple headers are supported by entering the table like so:

| setHeaders | !- name1 : value 1
name2 : value2 -! |

We have attempted this where one of the name/value pairs has a variable for the value.  When the test is executed, the variable is not populated (however the variable name is).  Is there some sort of escaping that needs to happen so that the variable name gets treated as a variable?

|setHeaders|!- LegalAccessToken : ${setHeader.accesstoken} 
userGUID : 635d06c5f8ce4d8d9d4a76247b053fc3
sessionGUID : 0931677444ea4bfa8cda302f168ad178 -!|

When we use the following table, the variable is set and passed in:

|setHeader|LegalAccessToken : ${setHeader.legalaccesstoken}|

Please advise.

Thanks,
Mason

**Comment by BrakTalk** [comment]
To verify that I was at least getting the table syntax correct, I verified that the headers are getting set properly by inserting a hardcoded value for the accesstoken.  So the question becomes, are variables set by the !define statement supported and if so, what does a proper set of that look like?

**Comment by BrakTalk** [comment]
I've been paging through the previous issues and it appears the issue [here](https://github.com/smartrics/RestFixture/issues/49) is why the expected behavior (variable population) is not occurring.  It sounds like for this scenario, I need to "convert" the variable to a const/symbol and then reference the symbol in the setHeaders row?

I think it also means we need to upgrade our Fitnesse and RestFixture jars. We inherited a rather dated test suite (pre-3.0).

Let me know if I'm headed in the right direction with these evolving assumptions.

**Comment by smartrics** [comment]
Hi - yes - you should update to the latest RestFixuture. I have tested successfully this fixture:

!define MIMETYPE {application/json}

|Table: Rest Fixture |http://${jettyHost}:${jettyPort}|
|setHeader|Content-Type: ${MIMETYPE}|
|HEAD | /resources/0 | | | |
