### ISSUE TITLE
Range check And Regular Expression Comparisons

### ISSUE THREAD

**Issue by mkyudi** [smartrics/RestFixture#156]
Seems range checking is not supported in rest fixture. E.g. Output should be greater than 10 or returned date value should be bereeen two given values.
If need to implement this behaviour where in api we should write the logic?

Thanks,
Mk

**Comment by mkyudi** [comment]
I am asking some thing like this
http://www.fitnesse.org/FitNesse.UserGuide.WritingAcceptanceTests.SliM.ValueComparisons

```
|DT:Some Decision Table|
|input|output?|
|3|<5|
|5|>=3|
|8|3<_<9|
```

or

```
|check|echo|Bob|=~/Bob/|
|check|echo|My name is Bob."|=~/B.b/|
```

**Comment by smartrics** [comment]
I assume you want to assert on properties of the json object in the
response. If so you could use javascript expressions. I  the expectation
cell the first row should be /* javascript */
Then the rest of the cell is interpreted as a js block which passes the
test if it returns true

**Comment by mkyudi** [comment]
I tried various combinations, but not getting up to that....

```
| Table:RestFixture | $appLink |
| GET | /rest/doSearch | | Content-Type : application/json | |
| let | body_value | js | !-response.jsonbody.type.length-! | !- /* javascript */
$body_value > 3; -!|
| let | body_value | js | !-response.jsonbody.type.length-! | !- /* javascript */
body_value > 3 -!|
| let | body_value | js | !-response.jsonbody.type.length-! | !- /* javascript */
response.jsonbody.type.length > 3 -!|
| GET | / | | |!- /* javascript */
response.jsonbody.type.length > 3; -!|
| GET | / | | |!- /* javascript */
$body_value > 3; -!|
| GET | / | | |!- /* javascript */
body_value > 3; -!|
| GET | / | | |!- /* javascript */
true -!|
| GET | / | | |!- /* javascript */
return true -!|
| GET | /rest/doSearch | | Content-Type : application/json | !- /* javascript */
response.jsonbody.type.length > 3; -!|
```
Not even a single command is returning as pass in this test case.
What I am missing...

**Comment by mkyudi** [comment]
Now I see that I can use this javascript in GET command only, Is there any way to use this in LET as well?

This one is working fine now
```
| GET | /rest/doSearch | | Content-Type : application/json | !- /* javascript */
jsonbody.type.length>3; -!|
```

This one is failing
```
| let | body_value | js | !-response.jsonbody.type.length-! | !- /* javascript */
jsonbody.type.length>3 -!|
| let |  | js | !-response.jsonbody.type.length-! | !- /* javascript */
body_value.length>3 -!|
```

**Comment by smartrics** [comment]
All right what do you intend to do? I am not clear what is that you want to
achieve by setting a symbol with an expression

**Comment by mkyudi** [comment]
I am trying to further inspect the 'GET' result. In the 'LET' command i am fetching some value from 'json' and then want to verify that if that value is correct.

I see I can use javascript in GET command, but i dont want to give so many GET command for the same URL.

**Comment by mukhark** [comment]
You don't need to issue a GET request for every value you want to test. You can do all the tests inside the same result cell. For example (using RestFixture 3.1):

<pre>
|!-Table: Rest Fixture-!|http://maps.googleapis.com/maps/api/geocode/json|
|setHeader              |!-Accept: application/json-!                    |
|GET                    |?address=1600+Amphitheatre+Parkway   |200   |   |!-
  jsonbody.results[0].formatted_address==="1600 Amphitheatre Pkwy, Mountain View, CA 94043, USA"
  jsonbody.results[0].geometry.location.lat===37.4224504
  jsonbody.results[0].geometry.location.lng===-122.0840859
-!|
</pre>

This test calls google geocoding service which returns a json object with many different fields in it. I can check any or all of those fields in the same results cell as shown above. In that cell, I am testing the value of formatted_address, lat, and lng with only a single GET request to the service.

Likewise, you should be able to send your request to your rest service and evaluate or check everything within the same table row in the result cell with just a single GET. Also, I notice in your example you are referring to `response.jsonbody`. The correct way is to use `jsonbody` to reference the json object, and then each element of the response is a property of `jsonbody`. Finally, as smartrics mentioned, you can put javascript into the results cell. So for example, if the response includes an array, you can put js into the results cell to iterate over the array:

<pre>
|!-Table: Rest Fixture-!|http://maps.googleapis.com/maps/api/geocode/json|
|setHeader              |!-Accept: application/json-!                    |
|GET                    |?address=1600+Amphitheatre+Parkway   |200   |   |!-/* javascript */
result = false;
var addr = jsonbody.results[0].address_components;
for (i in addr) {
  if (addr[i].types[0]==='route') {
    if (addr[i].long_name==='Amphitheatre Parkway') {
      result = true;
    }
  }
}
result;
-!|
</pre>

**Comment by mkyudi** [comment]
Thanks a lot. Very nicely explained.
