### ISSUE TITLE
Please add support for JS expectations using XPATH-like expressions or jsonpath

### ISSUE THREAD

**Issue by sglebs** [smartrics/RestFixture#157]
DefiantJS allows one to use xpath-like expressions with JSON results. This is very useful with REST calls that return an array of objects and one wants to assert on a given property of a given object with a given id, for example. This involves searching in the array. See: http://defiantjs.com

I imagine the patch is to inject the DefiantJS lib. It looks like it should be done here:

```
	public Object evaluateExpression(RestResponse response, String expression) {
		if (expression == null) {
			return null;
		}
		Context context = Context.enter();
		ScriptableObject scope = context.initStandardObjects();
		injectFitNesseSymbolMap(scope);
		injectResponse(context, scope, response);
		Object result = evaluateExpression(context, scope, expression);
		return result;
	}
```

Maybe a generalization of this ticket is to allow people to inject the JS libs they want to use in the snippets. This way you don't need to hardcode any specific lib.

**Comment by sglebs** [comment]
DefiantJS has a problem: it assumes it runs in a web browser. See https://github.com/hbi99/defiant.js/issues/71

**Comment by sglebs** [comment]
I was able to make it work with https://github.com/s3u/JSONPath , after patching it for https://github.com/s3u/JSONPath/issues/67 . This is how it can be used:
```
!define TEST_SYSTEM {slim}


!***> classpath config 
!path ${java.class.path}

***!

!|Import| 
|fitnesse.fixtures| 

!| Import |
| smartrics.rest.fitnesse.fixture.RestFixture |
| smartrics.rest.fitnesse.fixture.FitRestFixture |
| smartrics.rest.fitnesse.fixture.RestFixtureConfig |

|script | 
| start | smartrics.rest.fitnesse.fixture.RestFixture |

|Table:smartrics.rest.fitnesse.fixture.RestFixture | http://jsonplaceholder.typicode.com |
|GET    |/users |200|Content-Type : application/json||
|let	| $site	| js	| JSONPath({json: response.jsonbody, path: "$..[?(@.id==3)].website"}).toString() |ramiro.info|



```

**Comment by smartrics** [comment]
Thanks I would be happy to review and possibly merge a pull request

**Comment by sglebs** [comment]
Done. I was unable to do it with just the 6cafe9d commit, so the pull request also has the setUri change and also a local pom modification which I committed by accident.

**Comment by smartrics** [comment]
I commented on the pull request - closing this issue now as we can discuss how best to implement it in the pull request comments section. thanks for the contribution
