### ISSUE TITLE
Can't set base url from FitNesse

### ISSUE THREAD

**Issue by sglebs** [smartrics/RestFixture#158]
The setBaseUrl method expects an URL object and not a String, so it can't be used from FitNesse. Even overloading it won't do it because FitNesse will find this one first.

I propose adding this method:

```
public void setBaseUri(String uri) {   //sglebs  - it comes as a string in a scenario.
		this.setBaseUrl(new Url(uri));
	}
```

**Comment by smartrics** [comment]
Hi
Can you explain how do you want to use setBaseUrl from fitnesse?

**Comment by sglebs** [comment]
Sure. This is how I use it (my own fork of RestFixture):
```
!| scenario | QUANDO efetuo login com dominio | varDominio | e usuario | varUsuario | e senha | varSenha |
| set base uri | http://${BOUNCERhostname} |
| setHeader | Content-Type : application/x-www-form-urlencoded;charset=UTF-8 |
| setBody | domain=@varDominio&username=@varUsuario&password=@varSenha |
| POST|/adv-bouncer-server/tokenGenerator.html|expecting | 200 |
| $token= | let | token| from | body | at | /text |
```

**Comment by sglebs** [comment]
It is in commit 692660e

**Comment by sglebs** [comment]
See ticket #160 for the motivation/need, translated into english.

**Comment by smartrics** [comment]
the issue i have is that what we're passing is a url and have two methods that do the same thing with two different types is confusing. would you be OK with just naming setBaseUri(String) as 

baseUrl(String)

**Comment by smartrics** [comment]
closed as this issue is fixed with https://github.com/smartrics/RestFixtureExtensions
