### ISSUE TITLE
RestFicture incorrectly assumes empty constructor is not called by SLIM

### ISSUE THREAD

**Issue by sglebs** [smartrics/RestFixture#164]
All the issues #161 , #162 , #163 happen because there is a flaw in the current implementation which assumes the empty constructor in RestFixture is not called by SLIM. This is not true. If you use SLIM and scenario/script tables, it is the empty constructor that will be called.

This design flaw makes it really hard to do fluent BDD with RestFixture.

Can this design flaw be fixed without a major refactoring pain? Thanks!

**Comment by smartrics** [comment]
hi - there's a RestFixture extension that should support scenario/script tables here 

 smartrics.rest.fitnesse.fixture.ext.RestScriptFixture

it's in the module RestFixtureExtensions here https://githubBaseUri.

Here you can find examples https://github.com/smartrics/RestFixtureExtensionsLiveDoc/tree/master/src/main/resources/FitNesseRoot/RestFixtureExtensionsTests/ScriptFixtureTests

mind you that the i haven't recently run any tests with this fixture who was contributed by another author, 

You're more than welcome to try it out and submit patches

**Comment by smartrics** [comment]
This to say that any structural variation / extension to rest fixture will have to go in the extensions module
