### ISSUE TITLE
400 when using setBody with DELETE

### ISSUE THREAD

**Issue by haroon-sheikh** [smartrics/RestFixture#165]
For some reason, when I set body e.g. ''<item id="1"></item> to delete 
it returns 400 - The request sent by the client was syntactically incorrect (Bad Request).

However, same body works outside of fitnesse i.e. Postman

**Comment by smartrics** [comment]
the delete in RestFixture ignores what's set via setBody.
So, if your server is expecting some content, it replies with 400 (Bad Request) because no content is sent.

HTTP spec is only forbidding body for TRACE method. Currently RestFixure sends the body for POST and PUT only

**Comment by smartrics** [comment]
I am closing this issue as I won't be able to implement this feature. I will be happy to consider a pull request though should you wish to implement it
