### ISSUE TITLE
How to stop displaying results

### ISSUE THREAD

**Issue by yudii** [smartrics/RestFixture#166]
My test case is like this:

|Table:smartrics.rest.fitnesse.fixture.RestFixture | http://localhost:8090 |
| GET | /getClientNames | | !-Content-Type : application/json -! | |

And it is returning a lot of data that is eating up all the screen space. how can I stop showing result on screen?

Thanks

**Comment by yudii** [comment]
restfixture.display.actual.on.right	false
does not stop this

**Comment by smartrics** [comment]
It looks like a bug in RestFixture.

I'll see what i can do to fix it for next release

On 9 March 2016 at 17:31, yudi <notifications@github.com> wrote:

> restfixture.display.actual.on.right false
> does not stop this
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/smartrics/RestFixture/issues/166#issuecomment-194414665>
> .
>



-- 
Regards,

 Fabrizio

**Comment by smartrics** [comment]
I have fixed the collapsible content whereby for large content you get to toggle whether its shown or not. But the property works. Please try

    | Table: Rest Fixture Config | no-content-on-right |
    | restfixture.display.actual.on.right | false |
    
    |Table:smartrics.rest.fitnesse.fixture.RestFixture | http://localhost:8090 | no-content-on-right |
    | GET | /getClientNames | | !-Content-Type : application/json -! | |

**Comment by yudii** [comment]
I am testing this code.... offtopic of this question... how to debug my code that is in Eclipse, while Fitnesse test cases are executing... Thanks.

**Comment by smartrics** [comment]
i do execute fitnesse within the IDE (Intellij) in debug mode. that'll allow me to test RestFixure.
you can also run via JUnit 
for example
https://github.com/smartrics/RestFixtureLiveDoc/tree/master/src/test/java/smartrics/rest/fitnesse/fixture

**Comment by yudii** [comment]
I remember, when I was using Intelij I was able to debug the code, but not with the eclipse. Please let me know if you know any particular setting to debug on eclipse as well. Thanks

**Comment by smartrics** [comment]
I don't know about Eclipse as I am not an Eclipse user
