### ISSUE TITLE
collapsable column: first row

### ISSUE THREAD

**Issue by yudii** [smartrics/RestFixture#167]
we can format and collapse the content of RestFixture table, All rows except the first one.

e.g.
|Table:smartrics.rest.fitnesse.fixture.RestFixture | http://localhost:8090 |
| GET | /getClientNames | | !-Content-Type : application/json -! | |

The first row - first cell is quite lengthy and I have to scroll to right every time, is there a way that I can make it collapsable, just like other result columns.

**Comment by smartrics** [comment]
> The first row - first cell is quite lengthy

in your example the first row first cell is the |GET |

do you mean the *last* cell of the first column being all in one row and forcing horizontal scrolling?

**Comment by yudii** [comment]
1st row, 1st cell
|Table:smartrics.rest.fitnesse.fixture.RestFixture | 
Thanks

**Comment by smartrics** [comment]
So do you want **that** cell to be collapsible?

**Comment by yudii** [comment]
Yes

**Comment by smartrics** [comment]
you can reduce the space by adding an import in your suite setup:

    | Import |
    | smartrics.rest.fitnesse.fixture |
    | smartrics.rest.test.fitnesse.fixture| 

and then writing it as 

    | Table: Rest Fixture | ... |

other than that there's no more to do.
