### ISSUE TITLE
Basic auth not working.

### ISSUE THREAD

**Issue by nirajyadav** [smartrics/RestFixture#168]
Can you please help...

| Import |
| smartrics.rest.fitnesse.fixture |
| smartrics.rest.test.fitnesse.fixture|

| Table: Rest Fixture Config |
| http.basicauth.username | MKSSO |
| http.basicauth.password | abc |

|Table:smartrics.rest.fitnesse.fixture.RestFixture|${resourceUrl} |
|setHeader |!-Content-Type : application/json
-! |
|setBody |{ "type" : "credentials" } |
|POST |/customers/auth?client_id=${clientId}| | ||
|let |token |header|Authorization:Bearer (.*)||

This is not working .. 
it says

{"type":"AuthorizationBasicMissingException","message":"Missing credentials: Add a Authorization:Basic header with base64 encoded username:password."}}

I have used my correct username and password.

Any clue

**Comment by smartrics** [comment]
There may be an issue with the RestFixture and the credentials being correctly set. 
As a workaround, try by removing 

   | Table: Rest Fixture Config |
   | http.basicauth.username | MKSSO |
   | http.basicauth.password | abc |

then add the Authorization header explicitly:

    |Table: Rest Fixture|${resourceUrl} |
    |setHeaders |!-Content-Type : application/json 
    Authorization: Basic TUtTU086YWJj
    -! |
    |setBody |{ "type" : "credentials" } |
    |POST |/customers/auth?client_id=${clientId}| | ||
    |let |token |header|Authorization:Bearer (.*)||

As an aside, as you have imported the package of the RestFixture class you can then 

    |Table: Rest Fixture|${resourceUrl} |

instead of 

    |Table:smartrics.rest.fitnesse.fixture.RestFixture|${resourceUrl} |

**Comment by nirajyadav** [comment]
Thanks thats how i managed to get it working using 

Authorization: Basic TUtTU086YWJj

. But i was wondering how can i use these settings to keep my test nice and clean. 

I am also facing an issue with posting binary data.. Will open new case

**Comment by smartrics** [comment]
you should be able to put the same header in the used RestFixtureConfig as a 

| restfixture.default.headers | !- Authorization: Basic TUtTU086YWJj
-!|

that way the header will be injected in all the RestFixture requests
