### ISSUE TITLE
Posting binary data

### ISSUE THREAD

**Issue by nirajyadav** [smartrics/RestFixture#169]
Just to give some context..

I am using RestFixture to test rest APIs hosted by an ecommerce platform. Most of tests are working. but stuck on payment tests since last week.

We are using datacash as payment gateway. As part of payment i need to post html form with some base64 data in field PaReq.

Test is like below

|Table:smartrics.rest.fitnesse.fixture.RestFixture|https://accreditation.datacash.com                               |                                                                                                  |
|setHeader                                        |Content-Type : application/x-www-form-urlencoded                                                                                                                    |
|setBody                                          |MD=%MD%&PaReq=%Pareq%&TermUrl=https%3A%2F%2Fdev01-realm1-mothercare.demandware.net%2Fon%2Fdemandware.store%2FSites-MCENGB-Site%2Fdefault%2FHello-Start&submit=submit|
|POST                                             |/acs                                                             |200                               |                               |                               |

Form body becomes like this on execution 

	
MD=3000900053976733&PaReq=eJxdU11PgzAUffdXEN/hUhhsLLXJ3IyayGKcLz42cBWSUbAUp/56W7auzJuQ9HzQ3pze0tdKIm52
WAwS2ZXn0Rz7nn+gV5c31x0Pkjibp/M4vjailp9XL/h5XGv0hbKvW8FIEAYRBQutnKMsKi6UJTTF
i8/bxy2bZSSdzymcoNMblI8btpgliyjNFuGxKBxpZxO8QXb3tIa8VZU+hUukMJLOU7SDUPKH6Z0o
WODkQe5ZpVS3BCjxKyS+RL5viN+cdwxKbLgoD2YpUEErYML0qpUIu1ph7+fru+39rW+AtrzzYa/g
oW3Q31XtgYI5ymYC/0Ohz4Mh+mnr33XJ8s3qMP22r3my/X2L89/8hoJxOH/JFbIoJGkYk8iL4mWY
LpOEwshPwm9MCozMgkyLJ+TkzjSysh5jmTKTYAcpURQ2WYucAb+7VqD+R8/EeT3pFvuCuYvzulMA
ul+jnJP6HwxdP1xMUqH0TMx0xboiXUSXmalRuGin1ldPspCM/dRuDijYPfVxdrTNHY2PgF1RuHwg
f93w5Eo=

When i post this form.. payment gateway rejects it.. saying its not base64 string.. Will appreciate if you can help..

**Comment by nirajyadav** [comment]
one of other payment gateway has given example using httpclient. but they using newer version

https://docs.adyen.com/manuals/api-manual/security-3d-avs/3d-secure/3d-secure-code-examples/authorise-a-3d-secure-payment-with-http-post-java

**Comment by smartrics** [comment]
please try include teh base64 string withing !--!
    |setBody |!-MD=%MD%&PaReq=%Pareq%&TermUrl=https%3A%2F%2Fdev01-realm1-mothercare.demandware.net%2Fon%2Fdemandware.store%2FSites-MCENGB-Site%2Fdefault%2FHello-Start&submit=submit-!|

**Comment by nirajyadav** [comment]
Thanks !

   Tried it but no joy.. After debugging i found that. RestFixture read body as raw byes.. At this stage it converting all \n to %5Cn where payment gateway expects %0A 

Thats why its failing.  

so i passed body 

8Q5eXV5ddiJI42wRz+Pk0ogoP61e4OO4RvQJqq9byWkQBhEjFlo5B1VUQmpLICWK\nj+v7LU8yOpvPGfmDTm9A3W/4IkkX0SxbhMdi5Eg7mxQN8JuHNclbXeEpQgEjI+k8RTtIrb457sSI\nBU4e1J5XWndLQkr4DKmvQOwb6jenHYMSGiHLg1lK0KSVZML0ulVAdrWG3s/XN9vba98AtLyJYa/J\nXduAv6vaAyPmKJsJ+R8KexoM0U9b/6pLnm9Wh+m3fc3Tx00e5z/PV4wYh/OXQgOPQjoLYxp7UbgM\nk2WK8Y78JPzGpMBpEmQpZn9ETu5MIyvrMZYpMwl2UApkYZO1yBngq2sl4D84E6f1pFvoC+4uzuv+\nAsB+jXJK6n8wbH13NkmFxplIsGKsCItimZkahbN2arx6moV07Kd2c8CI3ROPs6Nt7mh8BPyCkfMH\n8gt8peQK\n

and it became

7Hcuh78Q5eXV5ddiJI42wRz%2BPk0ogoP61e4OO4RvQJqq9byWkQBhEjFlo5B1VUQmpLICWK%5Cnj%2Bv7LU8yOpvPGfmDTm9A3W%2F4IkkX0SxbhMdi5Eg7mxQN8JuHNclbXeEpQgEjI%2Bk8RTtIrb457sSI%5CnBU4e1J5XWndLQkr4DKmvQOwb6jenHYMSGiHLg1lK0KSVZML0ulVAdrWG3s%2FXN9vba98AtLyJYa%2FJ%5CnXduAv6vaAyPmKJsJ%2BR8KexoM0U9b%2F6pLnm9Wh%2Bm3fc3Tx00e5z%2FPV4wYh%2FOXQgOPQjoLYxp7UbgM%5Cnk2WK8Y78JPzGpMBpEmQpZn9ETu5MIyvrMZYpMwl2UApkYZO1yBngq2sl4D84E6f1pFvoC%2B4uzuv%2B%5CnAsB%2BjXJK6n8wbH13NkmFxplIsGKsCItimZkahbN2arx6moV07Kd2c8CI3ROPs6Nt7mh8BPyCkfMH%5Cn8gt8peQK%5Cn

where as it should be 

MD=3900900053983734&PaReq=eJxdU%2BtOgzAU%2Fu9TEP9DKZdtLLXJ3IyayLzMF2jgKCSjYClOfXpPmV2ZJyHpd6E9%2BXrKXisFsNlB%0AMSjgF57Hcuh78Q5eXV5ddiJI42wRz%2BPk0ogoP61e4OO4RvQJqq9byWkQBhEjFlo5B1VUQmpLICWK%0Aj%2Bv7LU8yOpvPGfmDTm9A3W%2F4IkkX0SxbhMdi5Eg7mxQN8JuHNclbXeEpQgEjI%2Bk8RTtIrb457sSI%0ABU4e1J5XWndLQkr4DKmvQOwb6jenHYMSGiHLg1lK0KSVZML0ulVAdrWG3s%2FXN9vba98AtLyJYa%2FJ%0AXduAv6vaAyPmKJsJ%2BR8KexoM0U9b%2F6pLnm9Wh%2Bm3fc3Tx00e5z%2FPV4wYh%2FOXQgOPQjoLYxp7UbgM%0Ak2WK8Y78JPzGpMBpEmQpZn9ETu5MIyvrMZYpMwl2UApkYZO1yBngq2sl4D84E6f1pFvoC%2B4uzuv%2B%0AAsB%2BjXJK6n8wbH13NkmFxplIsGKsCItimZkahbN2arx6moV07Kd2c8CI3ROPs6Nt7mh8BPyCkfMH%0A8gt8peQK%0A

**Comment by smartrics** [comment]
I have not been able to reproduce the issue - I suspect the issue is in your base64 string not being url encoded. as such the = at the end gets removed

    MD=3000900053976733&PaReq=eJxd....5Eo=&TermUrl=https%3A%2F%2Fdev01-realm1-mothercare.demandware.net%2Fon%2Fdemandware.store%2FSites-MCENGB-Site%2Fdefault%2FHello-Start&submit=submit

see if you can url encode it as 

    MD=3000900053976733&PaReq=eJxd....5Eo%3D&TermUrl=https%3A%2F%2Fdev01-realm1-mothercare.demandware.net%2Fon%2Fdemandware.store%2FSites-MCENGB-Site%2Fdefault%2FHello-Start&submit=submit

(ie the = sign becomes %3D)
