### ISSUE TITLE
How to extract data from html response

### ISSUE THREAD

**Issue by nirajyadav** [smartrics/RestFixture#170]
HI Guys,

   I am using html post and response is in HTML like this 

<!DOCTYPE html
    PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
     "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en-US" xml:lang="en-US">
<head>
<title>ACS Simulator</title>
<link rel="stylesheet" type="text/css" href="https://www.datacash.com/CSS/application.css" />
<style type="text/css">

</style>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
</head>
<body>

How can i extract data from body.. Like i want to extract title html. Any clue will be appreciated.

Tried let body /html/head/title.. doesnt work :(

**Comment by smartrics** [comment]
can you share the actual fixture that you are executing?

**Comment by nirajyadav** [comment]
Table:smartrics.rest.fitnesse.fixture.RestFixture

and trying to use let body extraction.. i think it use xpath.

**Comment by smartrics** [comment]
Yes - XPath will help

    | Table: Rest Fixture |http://your.host:port|
    |GET    | /fetch/html/above| 200 | |!-
        /html/title[text()='ACS Simulator'] -! |
    |let    | title | body | /html/title/text() | |

**Comment by nirajyadav** [comment]
Thanks it doesnt work for html.

For example i have html like this 

<html xmlns="http://www.foo.org/">
<head>
<title>ACS Simulator</title>
<link rel="stylesheet" type="text/css" href="https://www.datacash.com/CSS/application.css" />
<style type="text/css">

</style>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
</head>
<body onload="onLoadHandler();">
<div class='acs_iframe_size'>
<h1>ACS Simulator</h1><form name="return_form" action="https%3A%2F%2Fdev01-realm1-mothercare.demandware.net%2Fon%2Fdemandware.store%2FSites-MCENGB-Site%2Fdefault%2FHello-Start" method="POST"> 
  <noscript> 
    <center> 
      <h1>Processing your 3-D Secure Transaction</h1> 
      <h2>JavaScript is currently disabled or is not supported by your browser.</h2> 
      <h3>Please click on the Submit button to continue the processing of your 3-D secure transaction.</h3> 

      <input type="submit" value="Submit"/> 
    </center> 
   </noscript> 

   <script language="javascript">

   </script>

   <textarea style="display: none" name="PaRes">eJzVWFmzokoSfudXdPQ8ErfZVW6cPhHFDlrIKssbCrKICwKC/PpBz2afODPT0/M0RBhKVlZWfpVf
ZpaFPDnZOUkEO9m05+QZ+fbtCSZ1HaXJtzz++f0U/WBogpzQ9PT7bXAcNoCV1J8Hf9R5ekjiV51R
65Kc6/x4eCZ+4D/IJ+zt9W0YJudNFh2aN8EoijYVp+rPNEtMptMn7PX1Y3yfnFXheUYzM3LCzvCX
5wl7Eb/ZxT4bfjLam6BOHiz1efwMBdA9fnTH7GER4Lqw+fmE3TQ+9OOoSZ5JnJjgFMl+I9i/GfZv
fAR1l3+onW4rgf2xHVcncOYJexR8qI37fE4Om+vziOMJe3/7UEj60/GQjHPGJd5/vwP8jOfpFB2e
8YeHGJ9x7ehjsx3/wXqT7x/AkPgdzOjsXf6hVjdR09bPwRP2+usBQHS5PAMAOC7QXdf17PT2WVkm
eHnG/burPCDa5M+3NW7fv9oBZXo85022v4H9VfCO+M39EfuNeq8v9ki40bFz8q3fl4f65/esaU5/
Y1jXdT866sfxnGLkuBsYzmKjQjzy8x8f7LTvbFUP2+MfzB7n89HheMg3UZkPUTPyGiZNdoy/vTv/
lT3HupkkMEvk/xpt/rUh6MNfNwlOEcx37MH6O7TfMfvZzXMd/VVnEfGLRSvZJjeaJd9cS/35/R//
JnPv+kKeJnXzJ8t/Xvrd2Coq2+QZTbk1V8nYUu67M6kmnq8tiMwnjI070uZR88N57N37D058BPCX
mN537WV+y9JRYRaGb7rTsqOFq6cvFldBJqSlbKpHtJyKdX7yrbLNa72smJpQJytV91fB8UqcPAfB
NHgW5S2xCFdh3l07R2ZNbTbXsX6wD0qUUtfTxKZVGPKkSTUXbV/7vuGXy12DL+UYyki0z7LNShGL
61TpsvMcMnTmd9h+GxcsxOnBsfol6a1YaKc/XxA9uP+Gap5cH1GOEp/BWSFqok8iPjk3+Xbk5FiT
oKoKqcPzoK1S0KkcSFVOdYDOpbsq2+Uy2+EcMF0JCDyXDuICgp0MCFfkMsiv3LpHRAcYXKqvxpkO
L+nFmrLqwGN20FI7EQTCyjQVsSulUC7b4LC6hmTaSw5wXuYcHUQQrSyWJSHw9aMq9ngoiA7kxPsq
fA/nK3lVRDJzWcvsIXHEDHKz+xjoYWDJEo4Erp5tyDR1ZYlZe6s2VmBq4mIa5/QVcrQvOICGgniF
gzhAARJwdRxl6k3WLwVxQF6FXfIFvt+Bh/w7fL8DD3nAF0Ju84bPvOF7g2e6uqMqQQsLnjsMv0YI
AaYoAbDkChN0abDj02CcPyjLSSAA2dhhxHFqn9a40UCu0ruZwDD6pbs6BUOhaMv3OMIoTNNJ0ym6
Yi+Hi63UmyCWJxrYDmXOcgad2FGurj1UmhwhuQykFRmjFXWxlMkpge5ujRgpwWGoMZu7LDW7Roe4
7E/6HK0mlEFSaTgkhB+5bnzCGifu9/V5QzAKhUbyZTUmCDnjETDuJ4iWPDCPXZqK8mskYrEzeQhA
twCBFqihCoI1baaiznEzT3HZLvQYx8W7FLHIVRv62rjbq50q6uXmYJ3CfVkEY+ZCDr8bE1LT4zhT
NLlkVmYJf4JL0zyWTbOtTYTU5e7g8FzVjXG18IJT5QKqcppyVi2E8FzOi7iTmINzsJ14cbGFBA92
kcxlc5tLHQ5DoFl3vHknhSx22soeRAuCF7ryHFRdUr/Ecp+t92YvFsB84cjG4d3VLvKYHIl97RAJ
4gpy8GVSBuEjBxzFGpkHO/FlkYXYndzQ04/rPVuvyZhBoIV3cncfHNltiSP2zCSlIeI5e02y+Lgv
3J1ExzHVv0hz5Eai1OT6RefsF008tvQi5Y1yXq3DiELTGZ3nR7FI+Ku23js6cZHsZtjSA6yA6gmW
EyLGtCLmGX+t2uoUTJdEi+okiTvQvaCHyZIbuRvrqML7OENAzUtOxbgll7mw3lX6arKdzZBqEfAt
TdWKhbtrfqqEBHogZE8KVw7VXrZliR9wzM3PI7l6amLVBvg51sTPdQ35stKxwljpmut7pftqC4DA
YV8FEvlvIvlVIJH/JpJfBRL5MpIFSKQO75bCWDAK2MMBDLqgR6Psepc56bsMGdks/C8kRf4Vtt+F
htyx2WKnvGPLHklqBn7ZjBmNb66cYNocuSjULg1nnWAG2vwYqkh22ehjtRuTGAhpgIMRkgaOMge0
U0gl13xeutE+KRilJlfLxFGGBGunGb8/F6cQn+w2iE4u7GK5RV0VbulZrxJMn0wXeSiJ7a6STbfB
18YGSE3HuJfFwlte+GXUdHqzkex2tgMzJLQ9NCZI+mBkRpqSERFcEtbEsk0Tb2fUZkfODU6m22S2
5eDKmHuT7ETSZrC9EvJp32hThBc1AqSQA0Au0u2uS7dBp5j3mrMcT8qiJHf67tq6lU4Bfx8vY03H
W1bVp1ZujXAH5BYSxYZiGtVdGuVAkpfDXINB7uHtBTjSYSE511MueyFmHQNZPKkyB5VZzw9Au81F
OBA4oFwtoCV2wkskVLHLnGAk1lqW2rFJ2aN/L52wh5rlWaf1XiM2+/gILbcbO9590lzs+sfwwVge
STMA64U0tcOXVhmQWbsm+0tI7XrFAetXD6AjPbZGSbusKfO9cafpDvTbaS4tCePUgxcvLdwBpoJx
YPRgbBccNtyq1bgX5owD25k4Gh3bR/BOlleuSHeupOOwQKUp7o11yLKRBX5ZHvY8NBg1Zhyxmrhb
OjC9fOoRkO/z1RozXZqUN2LTz3piyoY4HhJzphScajNZED6y2E/3GZxfpB4I9OzkJ3ZhJW6vFRku
NlULc1+9mHoVyH7YdJOaw2pcbwmJRRtYbTg7Q+jytDJ80OIXYsinYlZfeOHUR4U+EG3jmBsKs7Q+
7MwCoLKabxvqvHecOXrsz1S+3uoBEu/YjZei2sXpK8Wf1idMsgS0ZDkhbMN0J0KoVWCySp1zQ4Yl
zcjqok3xruMnqDSj1CsiUosGvRQFm1XbcKHGE4HderW9vRytnbAgFhpdUYPP93PCS2jVPJJEsbft
dTC/2otZNtRINV/keGYouDX73SIsJsNYhMnlWxHWAPRROnMaZ7IxIcBl3q5kW11Twj3LXfB/xtwv
jpwDlD6OnMjtzPkq7LZ/cORE/tOR+j8dOZFPR+oYcvXbkdN9rOTunr3E/EMhTsX8FiHkMURjzwSA
VjmhAzeFObgdLUxhH9QHjsAYnSwHmjmMLWU1eL6hFtXWXCP+2s/5xbDBbS8wZoGwNvI5m+KZtNss
JVTXrxNxQ5ftaUZupaW9niankEWDiFV3B0MWJi5C6eZUOMsXxVhNzTSdzEuLmyeAIDP5XEEulBh6
zWf7Ka/sHC3RIUpii9Yb1jQhRHOZDxCrrGasVh23hbKv5Eml2mdnEdETwk0ifE/nUJV0eloHziq8
Sri7pLGFyB6drCL9M9tnDDIE2kgOC9vgie2UbXOuUYzuDF+zE6MpjqxeD6U7mzM0TChJZpuFgdLe
1Fcq1u8N1GmQRF5TGqvSE2vqMX7o6KUlWBNcnLMEXR3IdL3U+MmZVLRWoIKq2JEDJQ/7YfXWOpCv
e8e/bgW33vHYOpA/6R2PCYj8SQY+JiDyJxn4mIDIn/SOx9aB/HbvmANIhBZpLLmO1WKUvxyYGnAF
ooz/OKeeoDoz4Thj+JWNMd1Y79e2cp67ykwuoqkSE2iOxzUqpWhpbrFL0m1pd0qiqqSekHi5d8NF
XnfKJmm6opSCAFNoCWqGHUvnc71xxwOcoWJodsYulU3jLGW2fu5bZuXCij4geQF8M7gcqdJT+k4T
QypftWrcamJEEPhhnxfc1EDltky11WHvpEqlE4mZS4pajK1TihFinhrrmR94rbYm2rXmkFdeveTT
g0Z7yxQf99SQ5/g+xstJIB+HvvAnqMns3RzbE3OUVhFjd+48SefYxXFSAkXkNEZq0MMWqJxMySrE
D7mxoXSFatRWbaGHC1XMOfy2W3j5THG/bB3Y59uLJ+yXG46He5D7XTT2ehl9m/rrRfU/ASpnEJk=
</textarea>
   <input type="hidden" name="MD" value="3400900054126447"/>
</form>
</div>

</body>
</html>


and i am trying 


/html/head/titile/text()

i also tried..

/html/head/text()

No joy. i actually gets stuck and cannot do anything. I think its because of namespace.. Anyway to handle it ?

**Comment by smartrics** [comment]
can you confirm whether your html is valid XML?

**Comment by nirajyadav** [comment]
Thanks !  

yes..


<!DOCTYPE html
    PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
     "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en-US" xml:lang="en-US">
<head>
<title>ACS Simulator</title>
<link rel="stylesheet" type="text/css" href="https://www.datacash.com/CSS/application.css" />
<style type="text/css">

</style>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
</head>
<body onload="onLoadHandler();">
<div class='acs_iframe_size'>
<h1>ACS Simulator</h1><form name="return_form" action="https%3A%2F%2Fdev01-realm1-mothercare.demandware.net%2Fon%2Fdemandware.store%2FSites-MCENGB-Site%2Fdefault%2FHello-Start" method="POST"> 
  <noscript> 
    <center> 
      <h1>Processing your 3-D Secure Transaction</h1> 
      <h2>JavaScript is currently disabled or is not supported by your browser.</h2> 
      <h3>Please click on the Submit button to continue the processing of your 3-D secure transaction.</h3> 

      <input type="submit" value="Submit"/> 
    </center> 
   </noscript> 

   <script language="javascript">

   </script>

   <textarea style="display: none" name="PaRes">eJzVWFmzokoSfudXdPQ8ErfZVW6cPhHFDlrIKssbCrKICwKC/PpBz2afODPT0/M0RBhKVlZWfpVf
ZpaFPDnZOUkEO9m05+QZ+fbtCSZ1HaXJtzz++f0U/WBogpzQ9PT7bXAcNoCV1J8Hf9R5ekjiV51R
65Kc6/x4eCZ+4D/I......9m/rrRfU/ASpnEJk=
</textarea>
   <input type="hidden" name="MD" value="3400900054126447"/>
</form>
</div>

</body>
</html>

**Comment by nirajyadav** [comment]
Cannot post html here. But if you can share your email id.. i can send you as attachment. i am getting that html from hsbc 3dsecure page.

**Comment by smartrics** [comment]
you're right it's the namespace. 

you must NOT re-define the default namespace as it's not supported.

by removing the namespace the XPath works as shown here

https://github.com/smartrics/RestFixtureLiveDoc/blob/master/src/main/resources/FitNesseRoot/RestFixtureTests/IssueFixes/Issue170/content.txt

**Comment by nirajyadav** [comment]
Thanks.. but this HTML is coming from HSBC and i have no control. Is there anyway to make this working ? This is basically 3d secure page.

**Comment by smartrics** [comment]
sorry - i made a mistake when checking. i actually proved it working here

https://github.com/smartrics/RestFixtureLiveDoc/blob/master/src/main/resources/FitNesseRoot/RestFixtureTests/IssueFixes/Issue170/content.txt

you must define the namespace alias in a config fixture for it to work

**Comment by nirajyadav** [comment]
Still no Joy.. Here is my complete script..

|Table:smartrics.rest.fitnesse.fixture.RestFixtureConfig|conf                            |
|restfixture.xml.namespace.context                      |!-defalias=http://www.w3.org/1999/xhtml-!|

----
# Comment
Submit 3d AUTH
 
# Test

|Table:smartrics.rest.fitnesse.fixture.RestFixture|https://accreditation.datacash.com                                    |                                                                                                                                       |
|setHeader                                        |Content-Type : application/x-www-form-urlencoded                                                                                                                                                              |
|setBody                                          |MD::%MD%&PaReq::%Pareq%&choice::Authenticated&error_choice::0&TermUrl::https%3A%2F%2Fdev01-realm1-mothercare.demandware.net%2Fon%2Fdemandware.store%2FSites-MCENGB-Site%2Fdefault%2FHello-Start&submit::submit|
|POST                                             |/acs                                                                  |200                                     |                                                          |                                   |
|let                                              |title                                                                 |body                                    |//defalias:/title/text()                                   |                                   |


and complete HTML attached here.

https://www.dropbox.com/s/5e1q60rd67jjb4k/untitled.html?dl=0

**Comment by nirajyadav** [comment]
Here is screen shot of test..

https://www.dropbox.com/s/m3qevs2163ia52r/Screenshot%202016-03-30%2008.54.24.png?dl=0

Please let me know if still i am missing something.

**Comment by smartrics** [comment]
defalias:/title in the xpath should be defalias:title

**Comment by nirajyadav** [comment]
Thanks.. Finally it started working but dam slow. Take 5 minutes to parse this html.

 problem was my restconfig is not picking. So i had to hardcode in restfixture.java

i am using 

|Table:smartrics.rest.fitnesse.fixture.RestFixtureConfig|conf                                     |
|restfixture.xml.namespace.context                      |!-defalias=http://www.w3.org/1999/xhtml-!|

tried other options as well like 

|Table:Rest Fixture Config |conf                                     |
|restfixture.xml.namespace.context                      |!-defalias=http://www.w3.org/1999/xhtml-!|

but no joy. any clue ?

**Comment by smartrics** [comment]
regarding the config not being picked up: if you have modified the source code i won't be able to support it. i have proven here that the conf is being correctly used

https://github.com/smartrics/RestFixtureLiveDoc/blob/master/src/main/resources/FitNesseRoot/RestFixtureTests/IssueFixes/Issue170/content.txt

both forms in your post above look correct to me. you should then be able to 

    |Table: Rest Fixture |http://${jettyHost}:${jettyPort} | conf |
    |POST |/acs |200 | | |
    | let | title | body | //defalias:title/text() | |

**Comment by nirajyadav** [comment]
Thanks for your support. Really appreciate.. My last question on this thread..

is there any method to urlencode let parameter ?

I am extracting some values from html but need to url encode like \n for end line. Is there any method to do that ?

or any method to encode value in let row ?

**Comment by nirajyadav** [comment]
Thanks finally found solution.. 

encodeURI(symbols.get('title'))
