### ISSUE TITLE
The resource URL is encoded  after RestFixture table execution

### ISSUE THREAD

**Issue by BindiyaShetty** [smartrics/RestFixture#171]
Hi smartrics,

We are facing an issue while using RestFixture when the request URL contains an encoded string appended with the resource path  as shown below:

Table:rest fixture 	http://<IP>:<port> 	                                                                         
setHeader 	        Max-Wait:10000 	
setBody 		
GET 	                /<resourcePath>/text%3A%2F%2Feventis.nl%2Ftext           	200 	

It is necessary that we encode the text else the resource will not be found. But, when the above fixture is executed, rest fixture seems to encode the following text "text%3A%2F%2Feventis.nl%2Ftext" again. Hence, the application doesn't receive the correct value. I am using smartrics-fixture 3.0 version.  I have also tried switching to latest versions and also included !- -! around the text. But no luck.

Can you let me know If this is the right way of using this fixture for such cases?. Please  note I have used the same for different resource URLs where key value pairs are used and I am able to successfully execute the test cases.

Thanks in advance.

**Comment by smartrics** [comment]
you can use a config property that tells to RestFixture that URIs are escaped already. For example

    | Table: Rest Fixture Config | assume_uri_is_escaped |
    | restfixture.resource.uris.are.escaped | true|

then

    | Table: Rest Fixture |http://${jettyHost}:${jettyPort}| assume_uri_is_escaped |
    |GET    | /resources/0/text%3A%2F%2Feventis.nl%2Ftext | 200 | Content-Length : [\d]+ | |

or you can put the value in the chared config so all fixtures will get it 

    | Table: Rest Fixture Config | 
    | restfixture.resource.uris.are.escaped | true|

**Comment by BindiyaShetty** [comment]
Hi smartrics,

Thank you very much for the solution. It worked perfectly.
Very useful library indeed.

Regards,
Bindiya Shetty
