### ISSUE TITLE
Data driven tests using Rest fixture

### ISSUE THREAD

**Issue by saitest** [smartrics/RestFixture#172]
Hi,

I am newbie to fitnesse and Rest fixture. Looking at Rest Fixture, it seems to be good to automate Rest APIs. I am able to run the basic Rest API using Get & POST and i get the response correctly.

How do I validate the response using let. I tried to follow the below link but I am more confused. Can any one help me in doing this?

Also how can i do data driven testing using this fixture? I don’t have to give the static values in the parameters. Please suggest.

file:///tmp/mozilla_sganga0/RestFixture-2.0.beta.2.html

Thanks for your support.

**Comment by saitest** [comment]
For example for let i gave some thing like this:

let 	status_code_value 		response.statusCode  200. It gives me a message like I don't know how to process the expression for ''.

Please help me

**Comment by smartrics** [comment]
Some examples are provided in the Live Doc project here: 

https://github.com/smartrics/RestFixtureLiveDoc/tree/master/src/main/resources/FitNesseRoot/RestFixtureTests

specifically in here you can find examples of LET usage: https://github.com/smartrics/RestFixtureLiveDoc/blob/master/src/main/resources/FitNesseRoot/RestFixtureTests/LetTests/content.txt

    | Table: Rest Fixture |http://${jettyHost}:${jettyPort}|
    |setBody|<resource><name>Bill</name><data>Some data on Bill</data></resource>|
    |POST   | /resources/ | 201 | | no-body |
    |let    | id | header | Location:/resources/(.+) | |
    |GET    | /resources/%id% | 200 | |!-
     /resource/name[text()='Bill']<br/>
     /resource/data[text()='Some data on Bill']
    -! |
    |let    | name | body | /resource/name/text() | |

To properly data drive your fixtures you could 
- use fitnesse !define and Fitnesse symbolic links to link to separate pages containing different !defined data values (this won't scale for large datasets)
- create your own fixture that loads from a data source the data, then sets such data as fitnesse variables that can be accessed in RestFixture via ${}

**Comment by saitest** [comment]
Hi smartrics,

I am not successfull doing the above. I think i am doing a little mistake did not quite understand what it is.
|Table:smartrics.rest.fitnesse.fixture.RestFixture 	|https://URL.com/ 	|
|setHeaders 	|!-Content-Type : application/x-www-form-urlencoded
Authorization: *********** (some username/password which is base 64)-!|
|setBody 	|Id=1234567&Id=976876786 	|	
|POST 	|/1/2/3/ 	|200 	|Content-Type : application/json 		|
|let |	name		|body|	/1/number/text()||

1 is the header and number is the node with in that. For every id i would expect a unique number to be displayed in the response and i would like to validate that.

Please suggest.

Thanks very much

**Comment by saitest** [comment]
I dont have any symlinks for this i am just passing the values directly in the table.

Thanks

**Comment by smartrics** [comment]
Ok this is your fixture:

    |Table:smartrics.rest.fitnesse.fixture.RestFixture 	|https://URL.com/ 	|
    |setHeaders 	|!-Content-Type : application/x-www-form-urlencoded
    Authorization: *********** (some username/password which is base 64)-!|
    |setBody 	|Id=1234567&Id=976876786 	|	
    |POST 	|/1/2/3/ 	|200 	|Content-Type : application/json 		|
    |let |	number	|body|	/B/number/text()||


The body of the response is a JSON object

**Comment by saitest** [comment]
cool this works :-). thanks very much.
