### ISSUE TITLE
using multiple fixtures together

### ISSUE THREAD

**Issue by nirajyadav** [smartrics/RestFixture#174]
Hi Experts,

    Need help. i want to use other fixtures with restfixture. For example i want to store output of restfixture (let variable) to database using another DB fixture. Now how to pass variables ?

I am trying to use $variable= in restfixture but not working. Any clue ?

Appreciate your help in advance.

**Comment by nirajyadav** [comment]
Somehow i made some progress. So now i am using this ..

|let                                              |StringToken                          |js    |String(symbols.get('token'))|$currentToken =|

now i am getting value in $currentToken =.. but i appends <div> in start and end of value.. Any clue ?

**Comment by smartrics** [comment]
i have created an example of usage for you to demonstrate how to pass in and out symbols:

https://github.com/smartrics/RestFixtureLiveDoc/blob/master/src/main/resources/FitNesseRoot/RestFixtureTests/IssueFixes/Issue174/content.txt

Though, you should do:

    |let |currentToken  |js |String(symbols.get('token'))| |

then use it as 

    $currentToken= 

in other fixtures. Check the examples above and let me know if you still have doubts
