### ISSUE TITLE
How to validate the JSON Respone returned from a service?

### ISSUE THREAD

**Issue by kadimulam** [smartrics/RestFixture#175]
Hello,

I am new to Fitnesse tool. Could you please help me on this?

I have a Spring Restful web service that returns JSON response as mentioned below for the GET request (/api/product/1). Could you please let me know if it is possible to compare the JSON Response AS-IS with the expected result that i give on the Test? If it is not possible can we do similar test with XML Reponse. If not, could you please let me know the options available with RestFixture?

Response:
**{"productId":1,"productName":"Car"}**

Test:
|Table:smartrics.rest.fitnesse.fixture.RestFixture | http://localhost:8002/|
|setHeader|!-Content-Type:application/json;charset=UTF-8-!|
|GET|/api/greetings/2|200|Content-Type : application/json|**{"productId":1,"productName":"Car"}**|

Thanks,
Kiran

**Comment by kadimulam** [comment]
Sorry for the typ, the Test that i executed is below:

**Test:**
|Table:smartrics.rest.fitnesse.fixture.RestFixture | http://localhost:8002/|
|setHeader|!-Content-Type:application/json;charset=UTF-8-!|
|GET|/api/product/1|200|Content-Type : application/json|{"productId":1,"productName":"Car"}|

**Comment by smartrics** [comment]
If this is the fixture you may want to validate the response with some simple json like

    |Table:smartrics.rest.fitnesse.fixture.RestFixture | http://localhost:8002/|
    |setHeader|!-Content-Type:application/json;charset=UTF-8-!|
    |GET|/api/product/1|200|Content-Type : application/json|!--
      jsonbody.productId==1 && jsonbody.productName == "Car"
    --!|

further examples here

https://github.com/smartrics/RestFixtureLiveDoc/tree/master/src/main/resources/FitNesseRoot/RestFixtureTests

**Comment by kadimulam** [comment]
Thanks so much for the reply. Could you please clarify further?

For a complex JSON output, are you saying that the developer need to write the comparing logic on jsonbody object to compare the expected and actual output? I wanted to check with you if RestFixture automatically compares the expected and actual output and then either passes/fails the test case. Is it possible?

If the developer need to write the comparing logic to verify the JSON reponse, would be huge for comparing a huge JSON. Moreover, the tests in the Wiki are written by QA/business teams who do not have such technical ability. Am i missing anything? Please correct me if i am wrong.

**Comment by EshwarprasadKc** [comment]
HOW CAN I PASS DATA B/W TWO TEST PAGES
