### ISSUE TITLE
how to read .txt file in post setbody using fitnesse? 

### ISSUE THREAD

**Issue by EshwarprasadKc** [smartrics/RestFixture#177]
!define TEST_SYSTEM {slim}
!path C:/RestFixture/target/dependencies/*
!path C:/RestFixture/target/smartrics-RestFixture-4.1-SNAPSHOT.jar
!path C:/RestFixture/slf4j-simple-1.6.6.jar
| Table:smartrics.rest.fitnesse.fixture.RestFixture | http://person-3-0-0-qa.run.covisintrnd.com |
| setHeader | !-Content-Type : application/vnd.com.covisint.platform.person.v1+json
Accept:application/vnd.com.covisint.platform.person.v1+json
x-requestor: [APPCLOUD-QA]APPCLOUD-QA_ADMIN
x-realm : S-PLATFORM-COVS
x-requestor-app : RnD Testing.
 -! |
| setBody |i want to read file directly here instead of json format|
| POST | /persons | 201 | | |

**Comment by smartrics** [comment]
Hi what you are asking is not supported

**Comment by EshwarprasadKc** [comment]
is there anyways to read a file in fitnesse ,if not .txt file atleast for json file

**Comment by smartrics** [comment]
You can write your fixture to read a file from the filesystem and set it to
a variable. then pass it to restfixture.

check in the fitnesse/slim documentation about script fixture for example.



.

On 30 March 2016 at 12:30, EshwarprasadKc <notifications@github.com> wrote:

> is there anyways to read a file in fitnesse ,if not .txt file atleast for
> json file
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/smartrics/RestFixture/issues/177#issuecomment-203388866>
>



-- 
Regards,

 Fabrizio

**Comment by kadimulam** [comment]
I also have similar requirement. I wrote a fixture that can read data from file, however need help in **assigning it to a variable and setting on the Test Page**. I searched for script fixture documentation, but could not find anything. Could you please point me to the right web page and a example on how it needs to be read on the Test Page?

**Comment by kadimulam** [comment]
Also, how can we combine two Fxitures (RestFixture and Script) in one Test page?

**Comment by smartrics** [comment]
check this out

https://github.com/smartrics/RestFixtureLiveDoc/blob/master/src/main/resources/FitNesseRoot/RestFixtureTests/IssueFixes/Issue174/content.txt

your DecisionFixtureTest could indeed read the file in input and provide it's content via a method. 
the output will be assigned to a variable that is then passed on to the RestFixture.

Kind of

    public class FileReaderFixture {
        private String fileName;
    
        public void setFileName(String value) {
            this.fileName = value;
        }
     
        public String fileContent() {
             String content= // read file in 'fileName'
             return content;
        }
     }


Then

    !| decision fixture test                |
    | fileName         | fileContent?                |
    | /path.txt  | $content=    |
    
    | Table: Rest Fixture |http://${jettyHost}:${jettyPort}| |
    | setBody | $content |
    |POST    | /uri     | 201 |  |  |

**Comment by EshwarprasadKc** [comment]
@kadimulam  can you please send that fixture to me

**Comment by EshwarprasadKc** [comment]
actually i am new to fitnesse can you guide me to write fixture to read a file in fitnesse
