### ISSUE TITLE
Adding loop to run the same test 10 times

### ISSUE THREAD

**Issue by saitest** [smartrics/RestFixture#178]
Hi,

I have started basic tests using Rest fixture. Now i would like to enhance my tests where i can run my GET & POST verbs for 10 times looping through the same test. 

Please suggest..

Thanks

**Comment by smartrics** [comment]
RestFixture doesn't support looping. You will have to manually copy/paste the same test 10 times in your page

**Comment by saitest** [comment]
ohh ok. If i have a fitnesse fixture to loop through the rest fixture tests does it support?

thanks

**Comment by smartrics** [comment]
you will have to extend the RestFixture and implement the behaviour yourself.

**Comment by EshwarprasadKc** [comment]
HOW CAN I PASS DATA B/W TWO TEST PAGES
