### ISSUE TITLE
how can compare full expected and actual body

### ISSUE THREAD

**Issue by EshwarprasadKc** [smartrics/RestFixture#179]
!define TEST_SYSTEM {slim}
!path C:/RestFixture/target/dependencies/*
!path C:/RestFixture/target/smartrics-RestFixture-4.1-SNAPSHOT.jar
!path C:/RestFixture/slf4j-simple-1.6.6.jar
| Table:smartrics.rest.fitnesse.fixture.RestFixture | http://person-3-0-0-qa.run.covisintrnd.com |
| setHeader | !-Content-Type:application/vnd.com.covisint.platform.person.v1+json
Accept : application/vnd.com.covisint.platform.person.v1+json
x-requestor: [APPCLOUD-QA]APPCLOUD-QA_ADMIN
x-realm : S-PLATFORM-COVS
x-requestor-app : RnD Testing.-! |
| setFileName | ..\RestFixture\FitNesseRoot\FrontPage\Myuserservice\post\Test data\file.json | |
| POST | /persons | 201 | | |
|let|id|header|/persons/(.+)||
| GET | /persons/%id%| 200 | | |
| let | body | js | JSON.parse(response.body) | |
| let | email | js | JSON.parse(response.body).email| |

**Comment by smartrics** [comment]
You can achieve deep comparison of json in javascript as discussed here https://github.com/smartrics/RestFixture/issues/176
