### ISSUE TITLE
What is the stable version of RestFixture if at all we want to use in production and what is the minimum JDK version that is required?

### ISSUE THREAD

**Issue by kadimulam** [smartrics/RestFixture#181]

**Comment by smartrics** [comment]
the latest release is 4.1, jdk is 1.8

**Comment by kadimulam** [comment]
How do i clone 4.1 version. When i clone master, i am getting SNAPSHOT version (4.2-SNAPSHOT) and i do not see a provision to select 4.1. Version 4.1 is not listed; however i see other versions (as shown in the attached image), please advise.

![restfixture_versions](https://cloud.githubusercontent.com/assets/18126158/14434208/a6e89514-ffdf-11e5-8601-6dda9712f5ef.JPG)

**Comment by smartrics** [comment]
Version 4.1 code hasn't been branched. But it's tagged
