### ISSUE TITLE
XPath expression to count number of rows

### ISSUE THREAD

**Issue by violinner** [smartrics/RestFixture#182]
Is it possible to test for the number of rows returned in a REST response,
something like:

|Table:smartrics.rest.fitnesse.fixture.RestFixture | http://localhost:8090 |
| GET |http://myapp/myquery/myparam |200 ||//count(//data/record) = '300'|

Thanks

**Comment by smartrics** [comment]
if your response is in XML you should be able to check expectations using XPath.
An xpath that counts elements is:


| GET |/path |200 | | !- count(//data/record) = 300 -!|

(note you dont need // infront of count and the quotes around the number to match

**Comment by violinner** [comment]
Thanks for the response!
It works also for: 
| ! count(/data/record[contains(MyNode,'my_string')]) = 42 -!|

The applications I'm testing produce CSV but return 'Content-type=text/html' and not 'text/csv.'

I have added "fromCsvToXml()" to Tools.java, called inside Tools.toDocument() if the text "looks like CSV."  It does everything I need, doesn't break existing tests, but structurally the addition is a hack.

Should a new CsvBodyTypeAdapter be made to call Tools.fromCsvToXml(), and if so, how can I convince the system to use it if the Content-type is text/html?

Thanks again!

**Comment by smartrics** [comment]
You should indeed create a new adapter
You can configure it via RestFixtureConfig via the adapters map property
