### ISSUE TITLE
Testing XHTML response from a REST service containing a large table 

### ISSUE THREAD

**Issue by violinner** [smartrics/RestFixture#184]
I need to call a URL of a REST service, the expected response in XHTML contains a table of dozens of rows. This may contain 1000 or 1000s or cells.

Is there any way to configure or extend RestFixture to validate the table as a whole, with a previously saved copy of the table?

The 

Thanks,
V

**Comment by smartrics** [comment]
Hi
It should be certainly possible by extending RestFixture. It may be
possible by creating your own content handler and setting it via
RestFixtureConfig.

It will all bold down to what 'validate' means in your context. And how you
intend to

  - express the validation rules and encode them in the body expectations
cell.

  - report the expected and actual results to the reader in a concise and
clear form with the intention of communicating the result.

HTH

**Comment by smartrics** [comment]
BTW with 'previously saved copy' of the table I meant 'in memory'

if you intend to use the file system then the only option is by extension
