### ISSUE TITLE
to read file into variable  and edit the  content of file in wiki page 

### ISSUE THREAD

**Issue by EshwarprasadKc** [smartrics/RestFixture#185]
we read file using 
| setFilename |../Test data\file.json|
 can you tell me  how i can edit the content of file which i read in fitnesse in other words how can i edit external file in fitnesse
and also tell me how to store a file in variable

**Comment by smartrics** [comment]
You can't

**Comment by EshwarprasadKc** [comment]
is there anyways we can do that..!

**Comment by PriyankaKoppad** [comment]
how to call and set values for objects,are present in setFilename (external file) like 
| Table:smartrics.rest.fitnesse.fixture.RestFixture | http://person-3-0-0-qa.run.covisintrnd.com|
|setHeader | !-Content-Type:application/vnd.com.covisint.platform.person.v1+json
Accept : application/vnd.com.covisint.platform.person.v1+json
x-requestor:GWXPD9A9
x-realm : Q-PLATFORM-COVS
x-requestor-app : POSTMAN-! |
| setFileName | ../fitnesse/FitNesseRoot/FrontPage/Login/personPost/files/file3.json |
| POST | /persons | 201 | | |

in the above body i want to change the value for objects in wiki page ,are present in file3.json.so how to call and change the values

**Comment by EshwarprasadKc** [comment]
how can i check Fitnesse Random value to a Variable

**Comment by smartrics** [comment]
You are asking: "given some json in a file in the filesystem how can i use the fitnesse wiki as an editor to edit the file?"

you may have to ask the question on the fitnesse forum but AFAIK you can't

**Comment by EshwarprasadKc** [comment]
how can i use generated id  automatically in external file
if i post using
|POST|/persons|201|   |  |
person id will be created ,i want to use that id in external file..!

IN wiki we use like this %id% to get generated id ,suppose if i create a person that id should automatically should link to external file

**Comment by smartrics** [comment]
Any op on external files will require extending the RestFixture

**Comment by PriyankaKoppad** [comment]
in the above body if we need to generate random username then what are the plug-ins and syntax to use ?

**Comment by smartrics** [comment]
You could use

| let | username | js | /*some js that generates random usernames */ ||

**Comment by EshwarprasadKc** [comment]
can we execute test cases in the suite according to sequence we want..! like if T1 ,T2 ,T3 are test cases T2 first T3 second and T1 third in other words Reordering the test cases in a FitNesse test suite

AND ALSO TELL ME
can we choose testcases to run in fitnesse suite ?

i have also found we can use tags to run it in sequence which we want but i found that everytime i run test ,it runs all tests

**Comment by smartrics** [comment]
For fitnesse specific questions please ask the fitnesse support group

https://groups.yahoo.com/neo/groups/fitnesse
On 2 May 2016 07:03, "EshwarprasadKc" <notifications@github.com> wrote:

can we execute test cases in the suite according to sequence we want..!
like if T1 ,T2 ,T3 are test cases T2 first T3 second and T1 third in other
words Reordering the test cases in a FitNesse test suite

AND ALSO TELL ME
can we choose testcases to run in fitnesse suite ?

i have also found we can use tags to run it in sequence which we want but i
found that everytime i run test ,it runs all tests

—
You are receiving this because you modified the open/close state.

Reply to this email directly or view it on GitHub
<https://github.com/smartrics/RestFixture/issues/185#issuecomment-216111933>

**Comment by EshwarprasadKc** [comment]
how can we make list of suites..?

**Comment by smartrics** [comment]
For fitnesse specific questions please ask the fitnesse support group

https://groups.yahoo.com/neo/groups/fitnesse

**Comment by EshwarprasadKc** [comment]
how can declare variable globally and use it in any wiki page where we write test case

**Comment by wangyunshuai** [comment]
Add below code in SuiteSetup, then you can use 'env' as variable in anywhere, it will be 158.
`
!| Table: RestFixture | http://set.this.url.because.format.require |
| let | env | js | var env = "158"; env |  |
`

**Comment by EshwarprasadKc** [comment]
tried same in suite page didn't get

**Comment by EshwarprasadKc** [comment]
what is the syntax to use that variable in test page

**Comment by wangyunshuai** [comment]
like this:    %env%

**Comment by EshwarprasadKc** [comment]
thank you 
|let|mynum|js|%env%||
  if i use like above i will get output but if i use here i am not getting
| PUT | /persons/%id%/accounts/password | %env% | | |   HERE I GET AS IT IS

**Comment by wangyunshuai** [comment]
Could you give me a full line code?
Do not write comments and code in one line.

**Comment by EshwarprasadKc** [comment]
!define TEST_SYSTEM {slim}
!path ..//RestFixture/target/dependencies/*
!path ..//RestFixture/target/smartrics-RestFixture-4.1-SNAPSHOT.jar
!path ..//RestFixture/slf4j-simple-1.6.6.jar
| Table:smartrics.rest.fitnesse.fixture.RestFixture | http://person-3-1-0-qa.run.covisintrnd.com |
| setHeader | !-Content-Type:application/vnd.com.covisint.platform.person.v1+json
                                                                                                                                                                                  Accept : application/vnd.com.covisint.platform.person.v1+json
                                                                                                                                                                                  x-requestor:{application}cca
                                                                                                                                                                                  x-realm : Q-PLATFORM-COVS
x-requestor-app : POSTMAN-! |
| setBody | !-{
   
    "creation":1424071000,
    "realm": "Q-PLATFORM-COVS",
    "status": "inactive",
    "name": {
      "given": "sivani test",
      "surname": "gottipati"
    },
    "addresses": [
      {
        "streets": [
          "25800 Northwestern Hwy"
        ],
        "city": "Bangalore",
        "state": "Karnataka",
        "postal": "48076",
        "country": "IN"
      }
    ],
    "language": "en",
    "timezone": "EST5EDT",
    "phones": [
      {
        "type": "main",
        "number": "897-987-0987"
      }
    ],
    "email": "sg94402@yopmail.com",
    "organization": {
      "id": "OQ-PLATFORM-COVS204002",
      "type": "organization",
      "realm": "Q-PLATFORM-COVS"
    }
}-! |
| POST | /persons | 201 | | |
| let | id | js | JSON.parse(response.body).id ||
| let | username | js | "PRIYA"+"_"+ Math.floor((Math.random() * 100000) + 1) | |
| setBody | !-{  
   "username":"%username%",
   "password":"Covisint_123",
   "passwordPolicy": {
    "id": "67b6c21a-badb-40d9-9753-bc7802c56997",
    "type": "passwordPolicy",
    "realm": "Q-PLATFORM-COVS"
  },
  "authenticationPolicy": {
    "id": "8fbe6d1d-db54-401b-afa8-fe0d1dc5a36f",
    "type": "authenticationPolicy",
    "realm": "Q-PLATFORM-COVS"
  },
   "creator":"[APPCLOUD-QA]APPCLOUD-QA_ADMIN",
   "creation":0,
   "realm":"S-PLATFORM-COVS",
   "expiration":0,
   "locked":"true",
   "unlockInstant":0,
   "version":"1"
} -! |
| setHeader | !-Content-Type:application/vnd.com.covisint.platform.person.account.password.v1+json
                                                                                                                                                                                  Accept : application/vnd.com.covisint.platform.person.account.password.v1+json
                                                                                                                                                                                  x-requestor:{application}cca
                                                                                                                                                                                  x-realm : Q-PLATFORM-COVS
x-requestor-app : POSTMAN-! |
| PUT | /persons/%id%/accounts/password | 200 | | |
| let | id | js | JSON.parse(response.body).id | |
|let|mynum|js|%env%||

**Comment by EshwarprasadKc** [comment]
just check in that last but third line
instead of  200 if i use
 | PUT | /persons/%id%/accounts/password | %env% | |  
i get output %env% instead of 158

**Comment by PriyankaKoppad** [comment]
java.lang.NullPointerException
is coming while using %env%

**Comment by wangyunshuai** [comment]
I have created one case use your code, and it work well, and test passed. Please check below pic
![1](https://cloud.githubusercontent.com/assets/12732404/15251396/c038bd60-195b-11e6-9a63-38ef0e1e888d.png)

**Comment by EshwarprasadKc** [comment]
i know that will work ..! since nothing wrong just check this
!define TEST_SYSTEM {slim}
!path ..//RestFixture/target/dependencies/*
!path ..//RestFixture/target/smartrics-RestFixture-4.1-SNAPSHOT.jar
!path ..//RestFixture/slf4j-simple-1.6.6.jar
| Table:smartrics.rest.fitnesse.fixture.RestFixture | http://person-3-1-0-qa.run.covisintrnd.com |
| setHeader | !-Content-Type:application/vnd.com.covisint.platform.person.v1+json
                                                                                                                                                                                  Accept : application/vnd.com.covisint.platform.person.v1+json
                                                                                                                                                                                  x-requestor:{application}cca
                                                                                                                                                                                  x-realm : Q-PLATFORM-COVS
x-requestor-app : POSTMAN-! |
| setBody | !-{
   
    "creation":1424071000,
    "realm": "Q-PLATFORM-COVS",
    "status": "inactive",
    "name": {
      "given": "sivani test",
      "surname": "gottipati"
    },
    "addresses": [
      {
        "streets": [
          "25800 Northwestern Hwy"
        ],
        "city": "Bangalore",
        "state": "Karnataka",
        "postal": "48076",
        "country": "IN"
      }
    ],
    "language": "en",
    "timezone": "EST5EDT",
    "phones": [
      {
        "type": "main",
        "number": "897-987-0987"
      }
    ],
    "email": "sg94402@yopmail.com",
    "organization": {
      "id": "OQ-PLATFORM-COVS204002",
      "type": "organization",
      "realm": "Q-PLATFORM-COVS"
    }
}-! |
| POST | /persons | 201 | | |
| let | id | js | JSON.parse(response.body).id ||
| let | username | js | "PRIYA"+"_"+ Math.floor((Math.random() * 100000) + 1) | |
| setBody | !-{  
   "username":"%username%",
   "password":"Covisint_123",
   "passwordPolicy": {
    "id": "67b6c21a-badb-40d9-9753-bc7802c56997",
    "type": "passwordPolicy",
    "realm": "Q-PLATFORM-COVS"
  },
  "authenticationPolicy": {
    "id": "8fbe6d1d-db54-401b-afa8-fe0d1dc5a36f",
    "type": "authenticationPolicy",
    "realm": "Q-PLATFORM-COVS"
  },
   "creator":"[APPCLOUD-QA]APPCLOUD-QA_ADMIN",
   "creation":0,
   "realm":"S-PLATFORM-COVS",
   "expiration":0,
   "locked":"true",
   "unlockInstant":0,
   "version":"1"
} -! |
| setHeader | !-Content-Type:application/vnd.com.covisint.platform.person.account.password.v1+json
                                                                                                                                                                                  Accept : application/vnd.com.covisint.platform.person.account.password.v1+json
                                                                                                                                                                                  x-requestor:{application}cca
                                                                                                                                                                                  x-realm : Q-PLATFORM-COVS
x-requestor-app : POSTMAN-! |
| PUT | /persons/%id%/accounts/password | %env%| | |
| let | id | js | JSON.parse(response.body).id | |
|let|mynum|js|%env%||

**Comment by EshwarprasadKc** [comment]
IN put request JUST CHECK THERE I USED %env% instead of 200 ,there i should get 158 but i am getting %env%

**Comment by wangyunshuai** [comment]
I get 158 but not %env% in my test

**Comment by EshwarprasadKc** [comment]
yea i got now i miss read the answer

**Comment by EshwarprasadKc** [comment]
how do i implement version control in fitnesse..?

**Comment by wangyunshuai** [comment]
I think we should discuss in private

**Comment by EshwarprasadKc** [comment]
send me a mail about it to friendlyeshwar@gmail.com

**Comment by EshwarprasadKc** [comment]
Eswaraprasad141989@outlook.com
