### ISSUE TITLE
Dependency JARs

### ISSUE THREAD

**Issue by kadimulam** [smartrics/RestFixture#186]
Are the below JARs required for RestFixture for executing code in RestFixture.

velocity-1.7.jar
javaEWAH-0.7.9.jar
jsch-0.1.50.jar

I see that velocity is being used for Unit Testing (test), could not find references for javaEWAH & jsch in the code. Are there any other JARs that are not being used?

Please advice.

**Comment by kadimulam** [comment]
Could you please let me know if XMLPull is required?

**Comment by smartrics** [comment]
You can check the dependencies via

    $> mvn dependency:tree

which returns: 
    INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ smartrics-RestFixture ---
    [INFO] smartrics.restfixture:smartrics-RestFixture:jar:4.2-SNAPSHOT
    [INFO] +- org.fitnesse:fitnesse:jar:20151230:compile
    [INFO] |  +- org.htmlparser:htmlparser:jar:2.1:compile
    [INFO] |  |  \- org.htmlparser:htmllexer:jar:2.1:compile
    [INFO] |  +- org.apache.velocity:velocity:jar:1.7:compile
    [INFO] |  |  \- commons-collections:commons-collections:jar:3.2.1:compile
    [INFO] |  +- commons-lang:commons-lang:jar:2.6:compile
    [INFO] |  +- org.json:json:jar:20140107:compile
    [INFO] |  \- com.googlecode.java-diff-utils:diffutils:jar:1.3.0:compile
    [INFO] +- smartrics.restfixture:smartrics-RestClient:jar:2.1:compile
    [INFO] |  \- commons-httpclient:commons-httpclient:jar:3.1:compile
    [INFO] |     +- commons-logging:commons-logging:jar:1.0.4:compile
    [INFO] |     \- commons-codec:commons-codec:jar:1.2:compile
    [INFO] +- org.mozilla:rhino:jar:1.7R3:compile
    [INFO] +- org.codehaus.jettison:jettison:jar:1.3.2:compile
    [INFO] |  \- stax:stax-api:jar:1.0.1:compile
    [INFO] +- com.thoughtworks.xstream:xstream:jar:1.4.2:compile
    [INFO] |  +- xmlpull:xmlpull:jar:1.1.3.1:compile
    [INFO] |  \- xpp3:xpp3_min:jar:1.1.4c:compile
    [INFO] +- org.slf4j:slf4j-api:jar:1.7.13:compile
    [INFO] +- junit:junit:jar:4.10:test
    [INFO] |  \- org.hamcrest:hamcrest-core:jar:1.1:test
    [INFO] +- org.hamcrest:hamcrest-all:jar:1.3:test
    [INFO] \- org.mockito:mockito-all:jar:1.9.0:test

**Comment by EshwarprasadKc** [comment]
how can i pass data b/w two test pages example below:
1st test page
!define TEST_SYSTEM {slim}
!path C:/RestFixture/target/dependencies/*
!path C:/RestFixture/target/smartrics-RestFixture-4.1-SNAPSHOT.jar
!path C:/RestFixture/slf4j-simple-1.6.6.jar
| Table:smartrics.rest.fitnesse.fixture.RestFixture | http://person-3-0-0-qa.run.covisintrnd.com |
| setHeader | !-Content-Type:application/vnd.com.covisint.platform.person.v1+json
                                                                                                                                                                                  Accept : application/vnd.com.covisint.platform.person.v1+json
                                                                                                                                                                                  x-requestor:GWXPD9A9
                                                                                                                                                                                  x-realm : Q-PLATFORM-COVS
x-requestor-app : POSTMAN-! |
| setBody | !-{
   
    "creation": 1433603998000,
    "realm": "Q-PLATFORM-COVS",
    "status": "inactive",
    "name": {
      "given": "sivani test",
      "surname": "gottipati"
    },
    "addresses": [
      {
        "streets": [
          "25800 Northwestern Hwy"
        ],
        "city": "Bangalore",
        "state": "Karnataka",
        "postal": "48076",
        "country": "IN"
      }
    ],
    "language": "en",
    "timezone": "EST5EDT",
    "phones": [
      {
        "type": "main",
        "number": "897-987-0987"
      }
    ],
    "email": "sg94402@yopmail.com",
    "organization": {
      "id": "OQ-PLATFORM-COVS204002",
      "type": "organization",
      "realm": "Q-PLATFORM-COVS"
    }
}-! |
| POST | /persons | 201 | | |
| let | id | js | JSON.parse(response.body).id | |
| let | username | js | "PRIYA"+"_"+ Math.floor((Math.random() * 100000) + 1) | |
| setBody | !-{  
   "username":"%username%",
   "password":"Covisint_123",
   "passwordPolicy": {
    "id": "67b6c21a-badb-40d9-9753-bc7802c56997",
    "type": "passwordPolicy",
    "realm": "Q-PLATFORM-COVS"
  },
  "authenticationPolicy": {
    "id": "8fbe6d1d-db54-401b-afa8-fe0d1dc5a36f",
    "type": "authenticationPolicy",
    "realm": "Q-PLATFORM-COVS"
  },
   "creator":"[APPCLOUD-QA]APPCLOUD-QA_ADMIN",
   "creation":0,
   "realm":"S-PLATFORM-COVS",
   "expiration":0,
   "locked":"true",
   "unlockInstant":0,
   "version":"1"
} -! |
| setHeader | !-Content-Type:application/vnd.com.covisint.platform.person.account.password.v1+json
                                                                                                                                                                                  Accept : application/vnd.com.covisint.platform.person.account.password.v1+json
                                                                                                                                                                                  x-requestor:GWXPD9A9
                                                                                                                                                                                  x-realm : Q-PLATFORM-COVS
x-requestor-app : POSTMAN-! |
| PUT | /persons/%id%/accounts/password | 200 | | |
| let | id | js | JSON.parse(response.body).id | |
I WANT TO USE THIS GENERATED ID IN ANOTHER TEST PAGES (2ND TEST BELOW)
!define TEST_SYSTEM {slim}
!path C:/RestFixture/target/dependencies/*
!path C:/RestFixture/target/smartrics-RestFixture-4.1-SNAPSHOT.jar
!path C:/RestFixture/slf4j-simple-1.6.6.jar
| Table:smartrics.rest.fitnesse.fixture.RestFixture | http://person-3-0-0-qa.run.covisintrnd.com|
|setHeader | !-Content-Type:application/vnd.com.covisint.platform.person.request.v1+json
                                                                                                                                                                                  Accept : application/vnd.com.covisint.platform.person.request.v1+json
                                                                                                                                                                                  x-requestor:GWXPD9A9
                                                                                                                                                                                  x-realm : Q-PLATFORM-COVS
x-requestor-app : POSTMAN-! |
| setBody |!- {
  "creator": "[APPCLOUD-QA]APPCLOUD-QA_ADMIN",
  "realm":"SYS",
  "creatorAppId":"2de44e1e-504e-432d-bbe4-cf0c17a8f55e",
  "justification":"I need access.",
  "registrant": {
    "id":"%id%",
    "realm":"SYS",
    "type":"person"
  },
  "servicePackageRequest": {
      "packageId":"PS-PLATFORM-COVS13976838",
      "realm":"SYS"
  }
}-! |      
| POST | /requests | 201 | | |
|let | id |js|  JSON.parse(response.body).id| |
|POST |/requests/tasks/approve?requestId=%id%| 204| | |

**Comment by smartrics** [comment]
Use let and refer to the symbol with %symbol%

**Comment by EshwarprasadKc** [comment]
Can you please tell me the syntax

**Comment by EshwarprasadKc** [comment]
can we execute test cases in the suite according to sequence we want..!  like if  T1 ,T2 ,T3 are test cases  T2 first T3 second and T1 third
