### ISSUE TITLE
Need to pass variable information to new BodyType

### ISSUE THREAD

**Issue by violinner** [smartrics/RestFixture#187]
I am writing an XHTML body type that needs to be passed ids of "div" tags to ignore.
Is there a way to access globally defined variables without using them to substitute text in the body?
The response body is already parsed as XHTML, and all the "div" tags are already enumerated.
Some must be ignored in the bodyType "equals()" method.

Thanks,
V

**Comment by violinner** [comment]
The fixture working and is quite simple - Parse the "Table" tags, using a Dom parser, Extract the text from the "TH" and "TD" tags, convert to CSV, and evaluate using a "String csv.equals(String expected)" or "String csv.contains(String expected)".  The problem is that some "TD" tags sometimes contain "DIV" tags with ids like "updateTimeStamp", which will never match an expected value.  I would like to snip these out in the DOM parser, not try to make a pattern matcher.  Is there a way to directly access the table of global variables from "!define" and look for div names to ignore?

**Comment by smartrics** [comment]
!defines are "wiki" variables whose value is resolved before the control is passed to your fixture.
if you are extending `RestFixture` you could also use to `RestFixtureConfig`

Regarding accessing the symbols you could use the class `smartrics.rest.fitnesse.fixture.support.SlimVariables`
