### ISSUE TITLE
restfixture.default.headers does not work in 4.2 and 4.1 version branch

### ISSUE THREAD

**Issue by wangyunshuai** [smartrics/RestFixture#189]
!| Import |
| smartrics.rest.fitnesse.fixture |
| smartrics.rest.test.fitnesse.fixture |

| Table: Rest Fixture Config |
| http.client.connection.timeout | 10000 |
| http.client.use.new.http.uri.factory | false |
| restfixture.display.toggle.for.cells.larger.than | 160 |
| restfixture.default.headers | !-Content-Type:application/x-www-form-urlencoded-!|
| restfixture.content.default.charset | UTF-8 |

I set the "restfixture.default.headers" as above, but it does not work in 4.2 branch.  if I down grade restFixture to 4.0, this can work well.  This issue also can be reproduced on 4.1 version.

**Comment by smartrics** [comment]
pushed a fix for this - it is available if you build master or on next release. please reopen if you require further support on this issue
