### ISSUE TITLE
Below error occurred sometimes after start test

### ISSUE THREAD

**Issue by wangyunshuai** [smartrics/RestFixture#190]
Below error occurred sometimes after start test：
`Could not complete testing: fitnesse.slim.SlimError: Timeout while reading slim header from client. Check that you are connecting to the right port and that the slim client is running. You can increase the timeout limit by setting 'slim.timeout' in the fitnesse properties file.`

**Comment by smartrics** [comment]
Hi I don't think this is related to RestFixture

You should post this on the fitnesse support group

**Comment by wangyunshuai** [comment]
Oh，sorry，my mistake!

Could you help check issue #189 ?
