### ISSUE TITLE
multiple regex expressions

### ISSUE THREAD

**Issue by violinner** [smartrics/RestFixture#193]
Is there a way to test with multiple regex repressions on one REST GET query returning plain text?

The response may be large, so specifying long text sequences to skip may overwhelm the evaluator.

Thanks!

**Comment by smartrics** [comment]
Hi - currently there's no support for it. A change is required on ```smartrics.rest.fitnesse.fixture.support.TextBodyTypeAdapter``` to support multi line regexes
