### ISSUE TITLE
Dynamically fetching the expected

### ISSUE THREAD

**Issue by sandeeprajub4u** [smartrics/RestFixture#194]
We want to invoke the same request (with same URI and request query params or post body) on prod parallel and QA
We would like to compare the response of prod parallel and QA where response of prod parallel will be expected and response of QA will be actuals.
Ideally we would like to compare only few attributes between prod parallel and QA.

Can you please let us know how to achieve using RESTFixture's

**Comment by mukhark** [comment]
Yes, this is possible.

One way is to create two RESTFixture tables in the test page. Use variables to set the server and request URL and any other table params:

    !define server (dns-of-your-qa-server)
    !define url (your-rest-url)
    !define GET_SUCCESS (200)
    !define correctResult (anything-you-want-to-test-for)
    |!-Table: Rest Fixture-!|${server}                                                           |
    |setHeader              |!-Accept: application/json-!                                        |
    |GET                    |${url}             |${GET_SUCCESS}|                |${correctResult}|
    |let                    |summary1           |body          |/plan/summary[1]|                |

The `let` statement in the last row of the table stores part of the response body into a variable named `summary1.` In this example, the response is a json body with a `plan` element that holds an array element named `summary`. (Note that XPath array elements are indexed starting at 1 and not 0.)

Then test the production server:

    !define server (dns-of-your-prod-server)
    |!-Table: Rest Fixture-!|${server}                          |
    |setHeader              |!-Accept: application/json-!       |
    |GET                    | ${url} | ${GET_SUCCESS} | | jsonbody.plan.summary[0]==="%summary1%" |

Here, json array elements are 0-indexed,

There may also be other ways to dynamically set the expected values, but this is one way that I found that works for me.

**Comment by smartrics** [comment]
@mukhark thanks!
