### ISSUE TITLE
Execution of PUT caused exception 'null'

### ISSUE THREAD

**Issue by am12** [smartrics/RestFixture#195]
Hi,
I get this error when only when i run my fitnesse test to a particular server. the same test pointing to all other hosts work fine. This is a new server we have set up. 
Execution of PUT caused exception 'null' 

Below is my request and stacktrace of the error i get 
!***< Import fixtures

| import |
| smartrics.rest.fitnesse.fixture.RestFixture |
*!

!***< Configure the !-RestFixture-! for debug mode

!define REMOTE_DEBUG_COMMAND {java -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=8000 -cp %p %m}
[[Debug Test][${PAGE_NAME}?responder=test&remote_debug=true]]

*!

!***> Configure the !-RestFixture-! with named configuration table of key value pairs+++

| Table: rest Fixture Config |  
| http.client.connection.timeout | 50000 |
| http.socket.timeout | 20000 |
| restfixture.display.toggle.for.cells.larger.than | 20 |
| restfixture.default.headers |!- -! |
| %qID% | #FUNCTION[fitnesse.utils.RandomGenerator, getRandomInteger(), qID]|
*!

!1 Verify 
----
| Table: Rest Fixture | https://services-qa.xx.com|
| Method | Url | Request Headers |Request Payload | Status | Response Headers | Response Payload | Variable |
| PUT |/q17/xxx|{{{
Authorization : Bearer ${accessToken_QA}
Content-Type : application/json
}}} | {{{
{
  "resources": [
    {
      "deleted": false,
      "cashBalance": 43343
    }
  ]
}
}}} | 200 | {{{Server : Apache-Coyote/1.1
X-Application-Context : userprofile-service:10102
Content-Length : 0
}}}| |  |

--------------------------

[main] ERROR com.uimirror.framework.http.CustomResponseErrorHandler - Response error: 400 BAD_REQUEST
[main] ERROR fitnesse.fixture.RestFixture - Exception occurred when processing method=PUTURL= /q17/xx
java.lang.NullPointerException
	at com.uimirror.framework.http.CustomResponseErrorHandler.handleError(CustomResponseErrorHandler.java:30)
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:614)

Please help me with this.

Thanks,

**Comment by smartrics** [comment]
hi - i don't recognise the error nor the structure of the RestFixture.

RestFixture expects 

| Method | Url | Status | Response Headers | Response Payload | Variable |

whilst you have 

| Method | Url | Request Headers |Request Payload | Status | Response Headers | Response Payload | Variable |

Please clarify

**Comment by am12** [comment]
Hi,
I have customised the fixture to support additional structure. im still wondering if something needs to be done on the server itself, sicne im able to hit every API other than the new server.

**Comment by smartrics** [comment]
OK i understand but i can't comment as it it seems the issue is in your code.
you may want to compare request/response you get on the wire for both servers and see if there are differences that may cause the issue.

**Comment by d-insig** [comment]
Hi, Would it be possible to meet over skype/webex. i'd love to show you my framework and discuss what i have in mind for fitnesse.

Thanks,
Abhishek

**Comment by smartrics** [comment]
If this is something related to fitnesse please post this question on the fitnesse yahoo group.
If it's for RestFixture please open a new issue and describe what the proposal is. I will be happy to comment
