### ISSUE TITLE
How do i call hashmap in fitnesse UI

### ISSUE THREAD

**Issue by d-insig** [smartrics/RestFixture#196]
Hi,

I have the below function and I'm new to fitnesse, i've been using your fixture for quite sometime. I need your help in executing the below function through the fitnesse UI. how do i go about with this.

`public HashMap<String, Quote> getQuotes(Set<String> tickerSymbolList) {
        int index = 0;
        StringBuilder postBodyBuilder = new StringBuilder();
        postBodyBuilder.append("symbols: stk");
        for (String each: tickerSymbolList) {
            if(!each.isEmpty()) {
                postBodyBuilder.append("." + (++index) + "=" + each + ";");
            }
        }
        String postBody = postBodyBuilder.toString();
        RestTemplate restTemplate = new RestTemplate();
        String responseString =  restTemplate.postForObject(url, postBody, String.class);
        System.out.println(responseString);
        return parse(responseString);
    }`

I need to input a string[tickerSymbolList] and the output is returned in another hashmap like below.

        HashMap<String, Quote> quoteHashMap = new HashMap<String, Quote>();

I read about using decision tables, do i use that? I'm unaware of the format as well.
Thanks in advance!

**Comment by smartrics** [comment]
Hi I use github issues for RestFixture support only. Please post the question to the fitnesse yahoo group

F

**Comment by d-insig** [comment]
Done, need your help on this please

**Comment by smartrics** [comment]
Please refer to this thread https://groups.yahoo.com/neo/groups/fitnesse/conversations/topics/21603
