### ISSUE TITLE
How do i call REST POST URL to support both query param and json input?

### ISSUE THREAD

**Issue by krthiks** [smartrics/RestFixture#199]
@Consumes({MediaType.APPLICATION_JSON})
	public boolean transformMessageGeneral(
			@QueryParam("param") String param,
			JsonInput tInput){
              }

**Comment by smartrics** [comment]
I am not sure what the JsonInput is, but I assume it;s the content posted.
So you would set the json with

| setBody | { 'your' : 'json; }|

and the content type with

| setHeader | !- Content-Type: application/json -! |

then post with 

|POST   | /path?param=value |  |  |  |
|
