### ISSUE TITLE
NO SUCH FIeld error : DEFAULT_ENCODING

### ISSUE THREAD

**Issue by konarbalaji** [smartrics/RestFixture#200]
I am new to Fitnesse & was trying to connect to REST API but end up getting below error. I checked the src of the RestClient version(smartrics-RestClient-2.0) i am using & I can see DEFAULT_ENCODING defined there but still getting this error. can you please help me solve this ?

![default_encoding_err](https://cloud.githubusercontent.com/assets/11050745/18311710/7747f854-7523-11e6-9299-ebbdc147a634.png)

**Comment by smartrics** [comment]
Hi not sure, but you're using a very old version of RestFixture.
Here you can find the latest

http://mvnrepository.com/artifact/smartrics.restfixture/smartrics-RestFixture/4.1

Use maven (or compatible) to fetch all dependencies, or else build it by cloning this repo.
