### ISSUE TITLE
Could not invoke constructor for GET[4]

### ISSUE THREAD

**Issue by konarbalaji** [smartrics/RestFixture#201]
I am getting the error - Could not invoke the constructor for GET[4]. As you can see in the screenshot, i am passing exactly 4 parameters to the GET method but still it gives error. Can you please tell mwewhats causing this issue.

![get_constructor_test](https://cloud.githubusercontent.com/assets/11050745/18311988/0c76dd9a-7525-11e6-8e33-f36339202ddd.png)
![get_constructor _error](https://cloud.githubusercontent.com/assets/11050745/18311989/0c86388a-7525-11e6-950e-877d0da5b5fa.png)

**Comment by smartrics** [comment]
Hi you must not leave any blank line between the Fixture declaration and the first command

    | Table: Rest Fixture |http://host:8080 |
    |GET    | /resources/0 | 200 | Content-Length : [\d]+ | |
