### ISSUE TITLE
Unable to download file through GET request

### ISSUE THREAD

**Issue by konarbalaji** [smartrics/RestFixture#203]
Hi Fabrizio,

If i fire the below highlighted URL(Its A REST API request) on browser , it gives me a csv file to download.
**http://verum.jpmchase.net/Verum/latest/bulkapi/OSI?columnSelect=invNo;parentInvNo;assetName;primaryDNSName;primaryIP;platformName;status;platformVersion&format=csv&page=1-4** 

However if i add the same URL in GET request of RestFixtures. it responds with 401 error status code. What is causing this issue ? I have provided the login details as well but am getting the login page as response to my request. 

I think that the URL i have passed along "Table:RestFixture" line (as seen in 1st screenshot) is incorrect. Can you help me what should i put in the 1st row of the table & what needs to go in  the GET  & what else is needed with login details to get this working 

Below screenshot shows the behavior of test execution : 
![get_request_lands_on_login](https://cloud.githubusercontent.com/assets/11050745/18385688/c234abcc-76af-11e6-9322-63bb94684430.png)

I copy pasted the Actual response to html file to see it in html view & found that it returns a login page: 
![res_in_html](https://cloud.githubusercontent.com/assets/11050745/18386116/5c1f08e8-76b2-11e6-95c7-f3ebcf3aa261.png)

**Comment by konarbalaji** [comment]
Hi,

can you please let me know whats wrong here & how to solve this ?

Regards,.

**Comment by smartrics** [comment]
i am not sure what your goal is bu if it's automation of a download operation, RestFixture isn't the ideal tool. 

at any rate, your best bet is to run the sequence login / download in a browser with the developers tool open and try replicate the operations as RestFixture tables.
quite possibly you will have to extract some form of auth token from the response to the post of the login form and pass it back to the download.
also note that once you get to download the file you will likely see the file content in the GET expectation cell.

**Comment by konarbalaji** [comment]
OK , Thanks for this info.

**Comment by prasannark** [comment]
As part of Get request i need to download file. I has written below code

| Table: Rest Fixture| http://localhost:8080/Service|
|GET| /getFile |200 | | |

when i executed the above code it is giving 404 instead of 200. But, if i checked headers are coming fine with proper filename.

My Rest Service giving response like below,
{
return Response.ok(file, MediaType.APPLICATION_OCTET_STREAM)
      .header("Content-Disposition", "attachment; filename=\"" + file.getName() + "\"" ) //optional
      .build();
}

**Comment by prasannark** [comment]
please provide update on the above problem
