### ISSUE TITLE
script file not imported correctly resulting in error msg - ' is not defined. (unnamed script#1)'

### ISSUE THREAD

**Issue by cdshah** [smartrics/RestFixture#204]
I have launched my fitnesse as 'java -jar  fitnesse-standalone.jar -d js/'
setting rest fixture cfg w.r.t importing javascript  as
`
!path D:/smartrics-RestFixture-3.0-bin/smartrics-RestFixture-3.0/lib/*.jar
| Table: Rest Fixture Config |  imp |
| restfixture.javascript.imports.map | !-sampleAdd=js/FitNesseRoot/javascript/sample.js-! |

|Table:smartrics.rest.fitnesse.fixture.RestFixture|http://192.168.57.155:8980|imp|
| setHeaders | !- Authorization: userSession=a6636578415f4d67d2 -! |
|GET|/abc/def/v1/gfh/stats?groupBy=1&cobrandId=10000000&reportType=REFRESH&duration=24h|200|Content-Type : application/json||
| let   | sum | js | var sum = sampleAdd(1, 2); sum;| |
`
My folder structure is  :- 
Js
 --> FitnesseRoot
     -->javascript
        -->sample.js
I m getting an error - ReferenceError: "sampleAdd" is not defined. but sampleAdd is defined in sample.js. I understand that path is incorrect. How can i debug the issue to specify the right path? Can i print the absolute path of js file ? Is there any checks that i can use to check if the file is loaded or at which path does fitnesse look to read this js file ?

**Comment by smartrics** [comment]
the ability to load custom javascript it implemented in RestFixture 4.1 (https://github.com/smartrics/RestFixture/blob/master/CHANGELOG)
you seem to be using 3.0, so please update and try again

**Comment by cdshah** [comment]
Thx Fabrizio. That indeed was the problem
