### ISSUE TITLE
Unable to download a file through GET request

### ISSUE THREAD

**Issue by prasannark** [smartrics/RestFixture#206]
As part of Get request i need to download file. I has written below code

| Table: Rest Fixture| http://localhost:8080/Service|
|GET| /getFile |200 | | |

when i executed the above code it is giving 404 instead of 200. But, if i checked headers are coming fine with proper filename.

My Rest Service giving response like below,
{
return Response.ok(file, MediaType.APPLICATION_OCTET_STREAM)
.header("Content-Disposition", "attachment; filename=\"" + file.getName() + "\"" ) //optional
.build();
}

**Comment by prasannark** [comment]
Please provide update on this issue

**Comment by smartrics** [comment]
Hello - i am not sure what you actually intend to do here. 
But anyway - if you intend to "get" the file and render it's content as body of the REST response, I don't think it's supported right now.

**Comment by prasannark** [comment]
Thank you for your reply.
 
My question is -  I dont' want to render the contents as body of the REST response. 

Service will download the file(it will automatically store in downloads folder of browser)  and set headers with filename . 
In fitnesse logs i am able to see with correct headers but, response status is coming as 404 instead of 200.

Error:  "HTTP/1.1 404 Not Found[\r][\n]"
RestClientImpl - response: [404] Not Found

do I need to write any custom restfixture / Can i set any property for not to expect response from service?

**Comment by smartrics** [comment]
So what you're saying is that if you hit this http://localhost:8080/Service/getFile on a browser, a file will be downloaded. If you do from RestFixture you will get a 404? 

Can you please run a tcpdump on the server and compare the request sent via RestFixure and the request sent via browser and see what the differences are?

If you want to check that the resource is available and can be served, have you tried with OPTION ?

**Comment by smartrics** [comment]
Closing - please reopen if needed
