### ISSUE TITLE
Unable to set baseUrl using symbol

### ISSUE THREAD

**Issue by francescoforesti** [smartrics/RestFixture#207]
Hi, I'd like to set the baseUrl for a table based on the outcome of another test (on the same page).
I tried following this page of Fitnesse's docs : [http://fitnesse.org/FitNesse.UserGuide.FixtureGallery.ImportantConcepts.FixtureSymbols](url) and other
docs I found (also a blog post from 2008 in smartrics.blogspot.it), but I can't seem to get it working.
I've tried with the following syntaxes :
`| Fit Rest Fixture | %emailLink% |
| GET | / | 200 |Content-Type: text/plain|Email Verified|`
`| Fit Rest Fixture | emailLink= |
| GET | / | 200 |Content-Type: text/plain|Email Verified|`
`| Fit Rest Fixture | $emailLink |
| GET | / | 200 |Content-Type: text/plain|Email Verified|`
but none of those work.
I know that the emailLink symbol is not null because I'm testing it in another table, but I can't seem to
inject it into the RestFixture. The error I get is an IllegalArgumentException, e.g. :
`java.lang.IllegalArgumentException: Malformed base URL: $emailLink`

Any help would be appreciated.

**Comment by smartrics** [comment]
Hello - what you are trying to do is not possible with Fit Rest Fixture but it's possible with (Slim) Rest Fixture as shown here:

https://github.com/smartrics/RestFixtureLiveDoc/blob/master/src/main/resources/FitNesseRoot/RestFixtureTests/IssueFixes/Issue207/content.txt
