### ISSUE TITLE
First run error:Unable to start test system 'slim': fitnesse.slim.SlimError: Got invalid slim header from client. Read the following: HTTP/1.1 408 Request Time-out

### ISSUE THREAD

**Issue by miichy** [smartrics/RestFixture#208]
Thanks smartics.I love RestFixture very much.Thanks for your work.here is the problem: when I restart the restfixture,the very first time to run a test.The error shows like:Unable to start test system 'slim': fitnesse.slim.SlimError: Got invalid slim header from client. Read the following: HTTP/1.1 408 Request Time-out.The second time is totally OK.Always the first time.Don't have clue.Please.

**Comment by smartrics** [comment]
I am not sure why you get this behaviour. do you see any other clue in the logs?
As this is a Slim specific question you may want to post it in the Yahoo Fitnesse forum.
