### ISSUE TITLE
Let results in a decimal value when it is in an integer in the JSON body.

### ISSUE THREAD

**Issue by nuggit32** [smartrics/RestFixture#209]
Having an issue where using LET results in a decimal variable when the JSON is an integer value.
The JSON response is
[ {
  "id" : 1
  },
 {
"id": 2
}
]

**The following has a result of 1.0 instead of 1.** for token1 and token2.

| Table:smartrics.rest.fitnesse.fixture.RestFixture | ${BASEURL} | restconfig |
| setHeader | ${HEADER} |
| GET | /models | 200 | | | 
| let | token1 | js | response.jsonbody[0]["id"] ||
| let | token2 | js | Math.floor(response.jsonbody[0]["id"] )  ||

I tried to use Math.floor to see if that resolves it but the result is always 1.0.

Any ideas?

**Comment by nuggit32** [comment]
An update on this it only appears to be the first json response when the id = 1 for LET.  If I change the insert and make the first record a value of 2 it is fine?  Very strange.

HERE is my SQL insert
INSERT [dbo].[T_COMPONENT_TYPE] ([Component_Type_Id], [Component_Type_Nme]) VALUES (1, N'Access Point')
INSERT [dbo].[T_COMPONENT_TYPE] ([Component_Type_Id], [Component_Type_Nme]) VALUES (2, N'AIM')

When I then call the REST API with LET this is the result:
JSONBODY:
[ {
  "id" : 1,
  "name" : "Access Point"
}, {
  "id" : 2,
  "name" : "AIM"
} ]

response.jsonbody[0]["id"] = 1.0
response.jsonbody[1]["id"] = 2

**Comment by smartrics** [comment]
The behaviour is "not incorrect". JSON has only a data type. That's Number, which is double precision floating point (https://www.tutorialspoint.com/json/json_data_types.htm).
So 1 is equal to 1.0. 

RestFixture doesn't change the value, any JSON body is parsed through the Rhino JavaScript interpreter (https://developer.mozilla.org/en-US/docs/Mozilla/Projects/Rhino)

if you want to preserve the value you'll need to store it in a String.

**Comment by nuggit32** [comment]
For future research.

| let | token2 | js | response.jsonbody[0]["id"].toString() ||

is the answer.

**Comment by smartrics** [comment]
Thanks - good tip!!
