### ISSUE TITLE
How can I make it fail early if status codes do not match?

### ISSUE THREAD

**Issue by haroon-sheikh** [smartrics/RestFixture#210]
Currently, I have a scenario where I'm expecting a 200 but when I get a 404. it gets stuck for a while.

How can I setup so that it errors as soon as it sees a 404?

**Comment by smartrics** [comment]
can you please provide a concrete example?
anyway - if the server takes time to respond in case of a 404 you could lower the client socket timeout for example by setting an appropriate value for the http.socket.timeout

| Table:smartrics.rest.fitnesse.fixture.RestFixtureConfig |my_custom_config|
| http.client.connection.timeout| XXXXX |

**Comment by smartrics** [comment]
closing for now - if the issue occurs again, feel free to reopen
