### ISSUE TITLE
HTML response with LET

### ISSUE THREAD

**Issue by nuggit32** [smartrics/RestFixture#211]
I'm trying to use LET to extract values from a HTML response.

I set me Configuration as follows:
| Table:smartrics.rest.fitnesse.fixture.RestFixtureConfig |restconfig|
| http.client.connection.timeout | 60000 |
| http.socket.timeout| 10000 |
| restfixture.content.handlers.map | !-text/html=TEXT-!|

Tried something simple from fitnesse.org to get the title in a variable.

|Table:smartrics.rest.fitnesse.fixture.RestFixture|http://www.fitnesse.org|restconfig |
|GET| / | 200 | |  <title>FrontPage</title>  |
|let    | title | body | /html/head/title/text() | |

The result is:
last response body cannot be parsed.

Can you use the above example and show me what I'm doing wrong in LET?

Fitnesse version = Release v20161106
RestFixture = smartrics-RestFixture-4.3-SNAPSHOT.jar

Thanks.

**Comment by smartrics** [comment]
Hi - could it be that the HTML is not valid XML?
Can you try with an XHTML and see if it works?

**Comment by nuggit32** [comment]
Sorry,  I've not had time yet to check.  Plan on this week to take a look.

**Comment by nuggit32** [comment]
So I tried with http://www.xhtml.org and that works.  Takes a long time, but eventually comes back.
Looking at the source it appears the difference is xhtml has a namespace and defines the xml:lang:
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

while http://www.fitnesse.org is:
<html>

The format for both look like valid xml.

**Comment by smartrics** [comment]
I viewed the source of fitnesse.org and I read

    <meta http-equiv="X-UA-Compatible" content="IE=edge">

which is not valid XML

**Comment by smartrics** [comment]
I am closing this on the basis that RestFixure doesn't support HTML content except XHTML.
