### ISSUE TITLE
Not found jsonbody.status=="FAIL"

### ISSUE THREAD

**Issue by Castlely** [smartrics/RestFixture#212]
jsonbody in some complex json return could not be found.

**Correct url**
!define TEST_SYSTEM {slim}
!path .\lib\*
| Table:smartrics.rest.fitnesse.fixture.RestFixture | http://localhost:8111/ |
| GET | / | 200 | Content-Type: application/json | jsonbody.status=="FAIL" |
![2](https://cloud.githubusercontent.com/assets/4417016/21479918/70825dfe-cb93-11e6-9dce-81f3809cd2a3.JPG)

**Wrong URL**
| Table:smartrics.rest.fitnesse.fixture.RestFixture | http://localhost:8111/|
| GET |/api/create.json| 200 |Content-Type: application/json| jsonbody.status=="FAIL"
![1](https://cloud.githubusercontent.com/assets/4417016/21479865/ff70dcd0-cb92-11e6-8eeb-8ec4fbf9df91.jpg)

**Comment by Castlely** [comment]
Fitnesse Version 20161106
RestFeature Version 4.2.

I'v tried javascript way but have same result.
| GET |/api/create.json| 200 |Content-Type: application/json|!- 
jsonbody=='a funky name'
-!|
@smartrics 
Could you please guide me which part is wrong in my wiki?

**Comment by smartrics** [comment]
your test is failing as it should because jsonbody.status=="SUCCESS"
