### ISSUE TITLE
Assertion failing with IllegalArguementException

### ISSUE THREAD

**Issue by kirru1432000** [smartrics/RestFixture#215]
**Hi Smartrics,

I am facing an issue similar to [this](https://github.com/smartrics/RestFixture/issues/126).
my json structure is
{
"items":[
{
"item1":"value1",
"item2":"value2",
"item3":"value3",
"item4":"value4"
}
,{..........},
{..........}
] ,
"things":{
"specialThings":[
{"A":"1"},
{"B":"2"},
{"C":"3"}
]
}
"error":null
}

I have to validate A,B,C values and Am using the xpath "//things/specialThings[0]/A[text()='1']" to assert by using rest fixture,but am getting illegal argument exception.

**Comment by smartrics** [comment]
can you not just assert for

jsonbody.things.specialThings[0].A == '1'

?

**Comment by kirru1432000** [comment]
I have used the below statement
jsonbody.things.specialThings[0].A == '1'.
But am getting error when the special things has key value as beow
"specialThings":[
{"1":"1"},
{"2":"2"},
{"A":"3"}
]
if I give jsonbody.things.specialThings[0].1 == '1', again it gives IllegalArg Exception.

**Comment by smartrics** [comment]
this is INVALID javascript

jsonbody.things.specialThings[0].1

try this

jsonbody.things.specialThings[0]['1']
