### ISSUE TITLE
about "RestFixture is not a fixture" error

### ISSUE THREAD

**Issue by btakeya** [smartrics/RestFixture#217]
Hi all,
I have some trouble with running FitNesse test using RestFixture.

Environment:
* Linux (CentOS 6.4)
* JDK 1.8 (1.8.0_102)
* FitNesse (20161106) 
* RestFixture (4.4)
* RestClient (2.2)
* Test has run via Web interface (ex: http://server/page?test)

Test wiki page:
 - !path /directory/to/lib/*.jar
!3 Aceess /hello Page
|smartrics.rest.fitnesse.fixture.RestFixture|http://server.url|
|GET|/hello|200|Content-Length: \[d\]+|Hello, Vitamin project!|

(server.url is arbitrary URL. all libraries-*.jar files are in /directory/to/lib)

I got "Class smartrics.rest.fitnesse.fixture.RestFixture is not a fixture." message as result (see below)
![shot](https://cloud.githubusercontent.com/assets/5250553/22639323/c6d90432-ec90-11e6-968d-e2fba7eaf5d4.png)

FitNesse and RestFixture and any other libraries are **not modified** (just build with ```gradle clean package``` command)

It would be thankful if you let me know why does it happening or you have any other concern.

**Comment by btakeya** [comment]
Standard Error:
[main] INFO smartrics.rest.fitnesse.fixture.RestFixture - ############ Detected FitNesse version: v20161106 ###########

(sorry but attach image is not working now :( )

**Comment by smartrics** [comment]
hello - could you try to enforce the test system by setting, at the top of the page, 

!define TEST_SYSTEM {slim}

I am not an expert in gradle but I assume that /directory/to/lib/ correctly contains all the dependencies and the RestFixture jar. If not, make sure it does or add the !path to it

**Comment by btakeya** [comment]
Thank you for your answer, @smartrics.
Use ```!define TEST_SYSTEM {slim}``` at the top of the page, problem I asked is solved.
(although another problem comes out 😂 )
