### ISSUE TITLE
Do we have support to run bash script from RestFixture table

### ISSUE THREAD

**Issue by vipinksahu** [smartrics/RestFixture#219]
I want to run bash script based on response from Rest service. My Fitnesse script is as below:

!define result (!- 
jsonbody.Parent === null -!)
|Table:Rest Fixture|${server}                                              |
|setHeader         |${json}                                                |
|GET               |${request}|${SC_OK}|Content-Type : application/json|${result}|

Trying to run bash script when I get Parent in jsonbody as null.

**Comment by smartrics** [comment]
There's no such thing in RestFixure!
