### ISSUE TITLE
Writing extra cells on the output table

### ISSUE THREAD

**Issue by violinner** [smartrics/RestFixture#220]
I would like to extend RestFixture to write a few more rows in the output table when the test is finished.
Where can I get a handle on something like "addRow( Cell [ ] );" ?

**Comment by smartrics** [comment]
check the RestFixture#doTable metod.
it takes a List<List<String>> representing the input table and returns a List<List<String>> representing the output table.
By adding to the returned list you should be able to add rows/cells as you need.
