### ISSUE TITLE
Int value in json interpreted and shown as Float

### ISSUE THREAD

**Issue by GaganJotSingh** [smartrics/RestFixture#222]
I have two suites A and B. Suite B contains a request with the response like `{"error_code":12,"error":"MISSING_VALUE"}`. It the makes an assertion for response.jsonbody.error_code (to be 12), which should obviously pass.

One unusual thing is happening now. When suite A and suite B are run independently then this test in suite B passes. But when suite B is run just after suite A, then the test fails. The test is expecting 12 but actually response.jsonbody.error_code is giving 12.0

Does anyone have an idea why this happens?
**NOTE:** This happens when RestFixture v4.4 or v4.3 is used. Earlier I was using v4.1 and there was no error like this.

**Comment by smartrics** [comment]
Hi - this has been reported here too - see if it helps:

https://github.com/smartrics/RestFixture/issues/209

**Comment by GaganJotSingh** [comment]
Yes, it works. Thanks for reply.

But the surprising thing is that when Suite B (in my question) is run alone then it works without the conversion to string.
Then jsonbody.error_code is not 12.0 but 12

It is only in some cases that it gives 12.0
