### ISSUE TITLE
Unable to assign a local variable to a global variable in fitnesse

### ISSUE THREAD

**Issue by JayashreeNagaraja** [smartrics/RestFixture#223]
Here is my case:
I am receiving the set of response in JSON (which includes a URL).  I am extracting the URL and saving it in a variable say Test_Url.  This is a dynamic URL and changes with every request.

I have a global variable by name Upload_Url.  I am trying the following method to assign the local variable extracted from JSON to the global variable in my test wiki page:

!define Upload_Url {${%Test_Url}}  

This does not seem to work.  I have to use this URL in a global variable to be able to use it in my next test.  Any help on this??

**Comment by smartrics** [comment]
You don't need to store the variable in a global Symbol as symbols are global by themselves.

!define won't work as it's resolved at rendering time and not at runtime.
