### ISSUE TITLE
not able to use RestFixture in conjunction with proxy authentication

### ISSUE THREAD

**Issue by ChristineMitterbauer** [smartrics/RestFixture#224]
Hi together,
in our customer's infrastructure there is a proxy infrastructure. We tried to use our FitNesse-Tests there, but unfortunately we always get IO-Errors and internally:

16 [main] INFO smartrics.rest.fitnesse.fixture.RestFixture - ############ Detected FitNesse version: v20160618 ###########
Apr 28, 2017 9:03:20 AM org.apache.commons.httpclient.auth.AuthChallengeProcessor selectAuthScheme
Information: basic authentication scheme selected
Apr 28, 2017 9:03:20 AM org.apache.commons.httpclient.HttpMethodDirector processProxyAuthChallenge
Information: No credentials available for BASIC 'Squid proxy-caching web server'@proxy.microdoc.dmz:8080
609 [main] ERROR smartrics.rest.fitnesse.fixture.RestFixture - Exception occurred when processing method=Post
 
we tried using the RestFixtureConfig with
!|Table: RestFixtureConfig|
|http.client.connection.timeout|50000|
|http.proxy.host|proxy.microdoc.dmz|
|http.proxy.port|8080|
|http.basicauth.username|myuser|
|http.basicauth.password|mypasswd|

and we tried to set the Basic Authentication Header directly in the call
|setHeader | Authorization: Basic base64encodeduserpasswd|

and also
|setHeaders | Proxy-Authorization: Basic base64encodeduserpasswd|

Nothing worked - can you help ?

Many thanks
Christine

**Comment by smartrics** [comment]
Hi - I am sorry but to diagnose this issue I'd have to be able to reproduce it.
the best thing to do is to try the same request from within a browser whilst capturing the http traffic (tcpdump) and see what a successful request look like. Then try to emulate it with the RestFixture.

**Comment by PeterKleinMicrodoc** [comment]
Hi Fabrizio.

I've been working with Christine on this project and wrote a patch for our problem. To reproduce, you need to set up  a http proxy with authentication (like squid, for example). Or you can use the one that your organization provides. You will then find that your browser can communicate with the web using the proxy (you will be prompted for user and password), but your rest fixture can't. 

Proxy authentication works by the client setting a request header like this:

`Proxy-Authorization:"Basic somethingInBbase64="`

Luckily, Apache Http Client already provide the method setProxyCredentials to set the proxy user and password. setCredentials does not work for proxies. Therefore, I amended the HttpClientBuilder like this: 

 ```
 private void configureCredentials(final Config config, HttpClient client) {
        String username = config.get("http.basicauth.username");
        String password = config.get("http.basicauth.password");
        if (username != null && password != null) {
            Credentials defaultcreds = new UsernamePasswordCredentials(username, password);
            client.getState().setCredentials(AuthScope.ANY, defaultcreds);
        }
        String proxyUsername = config.get("http.proxy.username");
        String proxyPassword = config.get("http.proxy.password");
        if (proxyUsername != null && proxyPassword != null) {
            Credentials defaultcreds = new UsernamePasswordCredentials(proxyUsername, proxyPassword);
            client.getState().setProxyCredentials(AuthScope.ANY, defaultcreds);
        }
    }
```

So now you can specify http.proxy.username and http.proxy.password and then, the RestFixture works for us from inside the company network.
I hope what I wrote makes sense? Anyway, it would be cool if you could take the code and integrate it into the trunk. I'm sure there are others who would appreciate this capability :-)

Greetings,

Peter

**Comment by smartrics** [comment]
Great! would you be able to create a pull request? If not I'll copy/paste

**Comment by PeterKleinMicrodoc** [comment]
Done!

**Comment by smartrics** [comment]
Merged - thanks
