### ISSUE TITLE
Unable to bypass URL encoding..

### ISSUE THREAD

**Issue by JayashreeNagaraja** [smartrics/RestFixture#225]
I want to make a PUT call on a URL which looks like:
/original/596141312_fit_test_text?Policy=%7B%22Version%22%3A%222012-10-17%22%2C%22Statement%22%3A%5B3A%221%22%2C%22Effect%2A%22Allow%22%2CAction%22%3A%5B%22s3%3AObject%ThanEquals%22%3A%7B%22s3%3Acontent-length-range%22%3221073741824%22%5D%7D%7D%7D%5D%7D

I tried adding: | restfixture.resource.uris.are.escaped | true | to my test in the config section but that does not seem to change the behavior. Also, the URL mentioned above is being picked up from the response of the previous test and I am passing the URL as |PUT|!- %Url% -!| | | |

Rest is continuing to encode the URL with %252 in every occurrence. PUT call is failing due to this.

Any help on this??

**Comment by smartrics** [comment]
Hi - I am not able to reproduce it, please check whether my test is correct:
https://github.com/smartrics/RestFixtureLiveDoc/blob/master/src/main/resources/FitNesseRoot/RestFixtureTests/IssueFixes/Issue225/content.txt

I am echoing back the query string and checking it's the same as the one I send. The two match. So I don't believe the problem is in the RestFixure/RestClient.

**Comment by JayashreeNagaraja** [comment]
Thanks for your reply.. After looking into our framework, I realized that we are using 'RestTemplateWrapper' instead of 'buildRestClient' and 'buildRestReqest' functions for configuring the rest client and building the rest request.  Could this be the issue?

I could not find a way to escape the URLs while using RestTemplateWrapper.  Could you please point me to the function/class file that encodes the URLs while processing the request, so that I can override it?

As a workaround, I tried decoding the (already encoded) URL before sending the request, to see if the default encoding works fine.  But, it continued to encode twice resulting with the same output.  Setting the | restfixture.resource.uris.are.escaped | configuration to work is the only way to get this going.

**Comment by smartrics** [comment]
the method is RestClientImpl#createUri
it's odd as that method simply creates new URI(Strin, boolean) where the boolean is the value of config.getAsBoolean("restfixture.resource.uris.are.escaped") in RestFixture#1322

worth checking whether the property is spelled correctly and/or the value set appropriately

**Comment by JayashreeNagaraja** [comment]
Thanks for the reply.. It helped me with another issue I was facing..

We were using the wrong 'exchange' method in RestTemplateWrapper which was encoding the the URL sent in the request.  Switching to the 'exchange' method which accepts Uri as the input, solved the URL encoding issue for me.
