### ISSUE TITLE
RestFixture repeating test cases

### ISSUE THREAD

**Issue by srinivasmmdl** [smartrics/RestFixture#232]
Hi Team,

I'm using the below wiki table to test mt rest api's 

|!define TEST_SYSTEM {slim}|
|!path D:/APIConnect/RestFixture_Latest/smartrics-RestFixture-3.0-bin/smartrics-RestFixture-3.0/lib/*|
|!| Table:smartrics.rest.fitnesse.fixture.RestFixture | http://localhost:7080/apitest |
|| let | ApiName | const | create | create |
|| let | Name | const | xxx| xxx|
|| let | Country | const | IN | IN |
|| setBody | <API><ApiName>%ApiName%</ApiName><Name>%Name%</Name><Country>%Country%</Country></API> |
|| POST | | 200 | | /Response/Status[text()='Success'] |
|| let | ApiName | const | Success | Success |
|| let | Name | const | xx| xxx|
|| let | Country | const | IN | IN |
|| setBody | <API><ApiName>%ApiName%</ApiName><Name>%Name%</Name><Country>%Country%</Country></API> |
|| POST | | 200 | | /Response/Status[text()='Failure'] |
|| let | ApiName | const | delete | delete |
|| let | Name | const | xx| xx|
|| let | Country | const | IN | IN |
|| setBody | <API><ApiName>%ApiName%</ApiName><Name>%Name%</Name><Country>%Country%</Country></API> |
|| POST | | 200 | | /Response/Status[text()='Delete'] |
|POST ||200||/Response/Status[text()='Success']|

My scenario:

I wanted to test the service for multiple test cases
1) success case
2)business failure
3)technical failure 

but the setBody remains same for the all three test cases and data will be changes for this I'm using LET to send the different data.

Here I'm setting body (setBody)  for each test case even though the message structure is same.

Is there any way to use one setBody for all three test scenarios and data needs to be change for each scenario?

I tried to use ${variable} variable concept to achieve this but I'm not sure how to use this.

Can anyone help me to achieve this?

my wiki table should be like below.

one setBody for all test cases and data will be changes for each scenario.

|!define TEST_SYSTEM {slim}|
|!path D:/APIConnect/RestFixture_Latest/smartrics-RestFixture-3.0-bin/smartrics-RestFixture-3.0/lib/*|
|!| Table:smartrics.rest.fitnesse.fixture.RestFixture | http://localhost:7080/apitest |
|| setBody | <API><ApiName>%ApiName%</ApiName><Name>%Name%</Name><Country>%Country%</Country></API> |
|| POST | | 200 | | /Response/Status[text()='Success'] |
|| POST | | 200 | | /Response/Status[text()='Failure'] |
|| POST | | 200 | | /Response/Status[text()='Delete'] |

Thanks,

**Comment by srinivasmmdl** [comment]
Hi,
Thank you for the response.

I tried to get the source code to modify it to work for SSL but I can't find the right java file.
Can you please share the links to download the source code and give me the class name to modify the code.

Thanks.

**Comment by smartrics** [comment]
the approach you have followed should work

| setBody | %ApiName%%Name%%Country% |
| POST | | 200 | | /Response/Status[text()='Success'] |
| POST | | 200 | | /Response/Status[text()='Failure'] |
| POST | | 200 | | /Response/Status[text()='Delete'] |

why do you think otherwise?
