### ISSUE TITLE
RestFixture Workflow

### ISSUE THREAD

**Issue by srinivasmmdl** [smartrics/RestFixture#233]
Hi All,

I have choosen restfixture for fitnesse to test my rest apis its simple and easy to use.

I am able to test simple rest api services and I wanted to add SSL functionality then I started looking into the source code of restfixture I found "RestClientImpl.java"  which looks suitable to add the code.

But still I don't understand the workflow (i.e when we hit the TEST where this control will go and what class will be executed and how response will be displayed on the wiki table).

Can anyone explain the workflow please.

Thanks,

**Comment by smartrics** [comment]
hi - every time you execute a fixture with a GET POST PUT DELETE etc, the request is mapped into a call to the rest client.

if you want to add SSL you need to make sure that ssl is configured (using for example RestFixtureConfig), that the configuration is passed on to the client and correctly applied.

you may want to consider looking at the method 

    smartrics.rest.fitnesse.fixture.PartsFactory#buildRestClient(Config)

and find a way - from the config - to create an HttpClient that is able to talk SSL. 

see this for reference http://hc.apache.org/httpclient-3.x/sslguide.html
