### ISSUE TITLE
GET causes random IO exception

### ISSUE THREAD

**Issue by ploutarchos** [smartrics/RestFixture#235]
I randomly get the following error:
Execution of Get caused exception 'Http call failed for IO failure'

It looks like this happens when the REST request takes more than a few milliseconds to come back.

Does the REST Fixture have any internal timeout? If yes, is there any way to configure it?

**Comment by smartrics** [comment]
yes - check the RestFixtureConfig property

    http.client.connection.timeout

**Comment by ploutarchos** [comment]
This is a late response but thanks a lot @smartrics!

I tried your suggestion and it worked beautifully. To help other people, below is what I added in my SuiteSetUp file to increase the timeout from the default 3000 milliseconds to 15000 milliseconds:

```
|Import                         |
|smartrics.rest.fitnesse.fixture|

|Table: Rest Fixture Config           |
|http.client.connection.timeout|15000|
```

However, I have discovered a case that the above override will not work. This is when you use the REST Fixture as follows (this can be done by mistake most possibly):

```
|Table: Rest Fixture |http://localhost:8080/api/|     |
...
```

I had a look in the code, and in the above case, the constructor "RestFixture(String hostName, String configName)" is used but with a blank configName. The code will then default the configName to "default".

However, the most possible is that you may not have defined any default config anywhere, and your configuration will be null in this case. As a result, your overridden value will not be set as the config below will be null:

```
private HttpClient createConfiguredClient(final Config config) {
    HttpClientParams params = new HttpClientParams();
    params.setSoTimeout(DEFAULT_SO_TO);
    if (config != null) {
        params.setSoTimeout(config.getAsInteger("http.client.connection.timeout", DEFAULT_SO_TO));
    }
    ...
}
```

I believe the following 2 changes would be worth considering:

A) Ideally we should remove the defaulting of the config name to "default". Because if it is not provided in the RestFixture constructor then it should try to use a RestFixtureConfig without a name (if it exists).

B) On the other hand, if a config name has been provided in the RestFixture then it should try to find a RestFixtureConfig with that name. And if it doesn't exist, it should through an exception.

The (A) would make us backwards incompatible, however, the (B) should be a change that can be done without an issue.

Do you think we could re-open this issue and do the change (B)?

**Comment by smartrics** [comment]
OK - would you be happy to send a pull request with the changes above and respective unit tests?
