### ISSUE TITLE
javascript resubstitution throws exception 

### ISSUE THREAD

**Issue by MaheshVelankar** [smartrics/RestFixture#237]
I am using Rest fixture to get a json body from a url.
Then I extract a member from that json body.  This member is actually a url to other service.
I store it in a javascript variable with let like ... ( my_svc_url )

This works successfully.............I can read the url string as extracted above and stored in the var.

I  use the above extracted url to call another service GET. ( this way ....  %my_svc_url% )
That time it is throwing exception about malformed url

I also tried using !- and -! around %%  like .... !-%my_svc_url%-!
Still I get the same error.

Please let me know if I am doing something basically wrong.

(There are several other variables that I am setting with let and using them in subsequent tables........this works without any issue.............Only the url string is having some problems.)

========================
This is from a real session
|let                                              |service_now_url     |js |response.jsonbody.items.serviceNowUrl||

This works properly and I get the the service_now_url as
https://XXXXXXX.service-now.com/api/now/table/u_event

However when I substitute the above as written below,
|Table:smartrics.rest.fitnesse.fixture.RestFixture |%service_now_url% |

This throws this error:
Table:smartrics.rest.fitnesse.fixture.RestFixture java.lang.IllegalArgumentException: Malformed base URL: %service_now_url% 	
=========================

Hope, I could explain my problem now.

**Comment by smartrics** [comment]
Hello - unfortunately it's not possible as the baseUrl is not resolved against symbols.
But it's an easy fix in the RestFixture#buildThisRequestUrl(String uri) method.
Would you be able to do it and send a pull request?

**Comment by MaheshVelankar** [comment]
No sir, 
Unfortunately I do not have bandwidth for that work.
I fixed this issue by 

|let |service_now_url |js |response.jsonbody.items.serviceNowUrl|**$snu=**|

and then later

|Table:smartrics.rest.fitnesse.fixture.RestFixture |**!-$snu-!** |

That seems to have solved my problem.

Please see if that is okay.
Thanks
