### ISSUE TITLE
RestFixture not working with Integration Authentication

### ISSUE THREAD

**Issue by sej2105** [smartrics/RestFixture#238]
Hi,

I am using the restfixture to test our services, however my tests fail to hit our end points because of integration authentication. 

I tried using the Rest Fixture Config however this didn't work. This is my test below:

|Table:smartrics.rest.fitnesse.fixture.RestFixtureConfig|http://ah-devtest:4450|
|http.client.connection.timeout|50000|
|http.proxy.host|http://entwsg-wcg.int.hermes.co.uk|
|http.proxy.port|8080|
|http.basicauth.username|user1|
|http.basicauth.password|password!|

|Table:smartrics.rest.fitnesse.fixture.RestFixture|http://ah-devtest:4450|
|GET|/api/Ratings|200|Content-Type:application/json||

and this is the response i get in FitNesse: 

`<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>

<title>401 - Unauthorized: Access is denied due to invalid credentials.</title>

<style type="text/css">

</style>

</head>

<body>

<div id="header"><h1>Server Error</h1></div>

<div id="content">

 <div class="content-container"><fieldset>

  <h2>401 - Unauthorized: Access is denied due to invalid credentials.</h2>

  <h3>You do not have permission to view this directory or page using the credentials that you supplied.</h3>

 </fieldset></div>

</div>

</body>

</html>
`

I'm not sure if i am missing something in the test or whether the restfixture can work with integration authentication. Any help is much appreciated.

Many thanks

**Comment by smartrics** [comment]
You may have incurred in two problems

|Table:smartrics.rest.fitnesse.fixture.RestFixtureConfig|http://ah-devtest:4450|

here the RestFixtureConfig takes zero or one arg. The arg represents the config name. 
Correct:

    |Table:smartrics.rest.fitnesse.fixture.RestFixtureConfig|

Regarding the values, you should escape using !--!

    |http.client.connection.timeout|50000|
    |http.proxy.host|!-http://entwsg-wcg.int.hermes.co.uk-!|
    |http.proxy.port|!-8080-!|
    |http.basicauth.username|!-user1-!|
    |http.basicauth.password|!-password!-!|

You could have also chosen to use a named config

    |Table:smartrics.rest.fitnesse.fixture.RestFixtureConfig| myConf |

but then you need to use it in the RestFixture

     |Table:smartrics.rest.fitnesse.fixture.RestFixture|http://ah-devtest:4450| myConf |

**Comment by sej2105** [comment]
Thanks for your help i did the above and got the following error when executing my test. 



```
Table:smartrics.rest.fitnesse.fixture.RestFixture | http://my-test:4450 | myConf
-- | -- | --
GETExecution of Get caused exception 'Http call failed for IO failure' | /api/tests| 200 | Content-Type: application/xml |  

```

When removing all values from the config other than username and password, i get the same error as in the first message. 

Sorry i'm implementing this into our organisation and everyone is pretty new to it, so any help would be much appreciated. 

Many thanks

**Comment by smartrics** [comment]
Please paste the actual test fixture. Also can you turn debug on and check the actual HTTP request?
Or alternatively use tcpdump or rawcap to capture the traffic and see how the request looks like.

I am assuming you have this correctly set as

    | Table: Table:smartrics.rest.fitnesse.fixture.RestFixtureConfig  | myConf |

and

    | Table:smartrics.rest.fitnesse.fixture.RestFixture | http://my-test:4450 | myConf |

**Comment by sej2105** [comment]
have this set out correctly now as above

|Table:smartrics.rest.fitnesse.fixture.RestFixtureConfig|myConf|
|http.client.connection.timeout|60000|
|http.proxy.host|!-http://entwsg-wcg.int.mytest.co.uk-!|
|http.proxy.port|!-8080-!|
|http.basicauth.username|!-user1-!|
|http.basicauth.password|!-password!-!|


|Table:smartrics.rest.fitnesse.fixture.RestFixture|http://ah-devtest:4450|myConf|
|GET|/api/Ratings|200|Content-Type: application/xml||

**Comment by smartrics** [comment]
so is it now working? or not?
and if not can you paste the http request executed when the 

    |GET | /api/Ratings | 200 | Content-Type: application/xml | | 

is executed?

**Comment by sej2105** [comment]
No, sorry still not working.

When executing GET http://my-test:4450/api/Ratings i get the following response: 

`GET http://my-test:4450/api/Ratings HTTP/1.1
Host: my-test:4450
Connection: keep-alive
Authorization: Negotiate YIIIgwYGKwYBBQUCoIIIdzCCCHOgMDAuBgkqhkiC9xIBAgIGCSqGSIb3EgECAgYKKwYBBAGCNwICHgYKKwYBBAGCNwICCqKCCD0Eggg5YIIINQYJKoZIhvcSAQICAQBugggkMIIIIKADAgEFoQMCAQ6iBwMFACAAAACjggatYYIGqTCCBqWgAwIBBaESGxBJTlQuSEVSTUVTLkNPLlVLojIwMKADAgECoSkwJxsESFRUUBsfZW50cHJvbXN5c3Rlc3QuaW50Lmhlcm1lcy5jby51a6OCBlQwggZQoAMCARKhAwIBF6KCBkIEggY+cLj++9agcsVFaKVNVAGkpnTNBf0OjZgqqSal2nyZrFlbv+SyO1C7bKgLhAWyxW4nKzO1kaVaROGLyMmbixmW0qFpTyTzZfNaCGHLnhlmcwSHOVD6f3HNx69mcuI/X+VUWEGKyF3ReoTaKY4IMcFgmmcTUalgElvcT5ysmC2cC7UtL4Zp9Fvx3VZuTd0SLKNAtMbK2+gMngh52H3mvZxBfqm+CB5rBT8XBzX5Wvavnjc4P1ZqAPaL6BZVt5MT5+CjKnX+DKmteWj68mmx6RXzleXe7Q4lTuL1StPUU8rSdGBYAO0+bkjKoRrNVyCrhRX0eiCeFIVI6H+I5Jz6HzVkW/PaGUrSGCZWUghM6IXf8MpVTUAR8HGSaXoRf56MBWrPNU6lbFuVOdTYa1l/ey1jKOp8qjIMkXtSNn2Y9qfon2u3lEYQgux7Dno/DkpAYngWYLoXzQxbwrV8+9dNhnPTVcGSDfsgElRkpQb8g1QleoJ+CQGWQnJGTnvwjeA6SLLOvvMBENUwZY2HJm2hD5QqDGhXx5y/0ZRPOpBYOvVPSdyYbYtzvBIVyUOjd8vyuZkjq7P5FLKBrWMcrtk3v6JGQo3qMtB3tqKJI8LnCl7JdqUpjLAvqjuIq1IV8+Hudil132S2TyExMMiVc27u4W0Db6+al6JeldKjjwkz9m099Cfbq6AAo5HCsPcwKg+MRb8XZlwfGu0QgAJecfvkFS8CADaKX1VWW4YBxSKuzrGm+fNs3Ru6gM3G7Pe9xLcSB/OB/MUF/TzFDnXa8LCiw9UsNp2F46n/53YBGgoQgZZ2ZfVNJ1b7chMsO3SfF7jTqN2X3XcGUDgQJmMLg3MwIavEi0MtWox37w9h306xNtrZnfyYnGK2F+SB3gX6mJlc0Hi2wvWatzmLsvHaue5NO99WvjfFTQR97Wtcgdf9TJghQN8bBcjHAs3zcPBlxNXL+gHR0qyFwBFTJBeYXAjYqAio2vVhD4ZGne6WVqV9m8V/9f3Qc6qi9Zw1A5LlAlY1+nQESH7cU8SWlACO22Y9sVg/56TdpCY30WcsmhjIWMps/9HPOWRTjxWOylhU+V1YuUKHKqv+L0VmyCyHlnD+kG7gehUK2n29+kZB8QSopCmRMTYJgy4my+W6hd8XKRBUh1DaNaWgoT8Pot/VG1NpAs5s38/biVJX1ClnTfamwVMk0Gg6TjawrsHzhDqUsBCNJTESB0QWDmojDIiX3SVLueJAY3iri9g4XXzSI+qyWwYJu3iwXVLNVZi8U43QDToCUrJqLFrkk30fU6SIzj/+wPmNKOcx7TTa0t3S29ZM5GGMBSPTZSEBA5kibYqThwKuEq5bBjr3UufdQGIWnIlD5ygpTMi6cb7BflQPqHgTrMdNzVwf5BB6Xs8Rs0XG0Utpix/mu2edSZZ+fRi3hH4LAhAtozqTZqW7Oj7k4d38ysT2u5gXX1rwdlOgpJhCLLhr6gje3nB7wnQl3FOBsb/k/CXeQDkS+0hzhmhiF81UZFrlJXJyHYra3cMOXzzQ6jRNcykymhAwb0SdSlMKMd8u+LnIBITmvdN3QHocUxXdp36sBiYV98Ta25e+Von72zpdSP5jCQXmCxx3NOUznT3ao+OXY9lC8J5fC/s43gLgjmg+i8kNxFALw/tHEOFJKvG9ogucMMcil7zaV8W14Vzo2B5s4eEpfbcEVtU5JKugH1lILior/8Ul9XU5QZeGgtu0BI7fPDvymAiv6XMc315SnFcA7Cfd8SFTfkhQyKwXnMI2nSLxbxzIBX134a6icd+syh/hGCBnTQ0ReJu+j2Vv85z482eV6RK3O3W+6pwpHynW6aOTmXwhcu+yrJusRDOJqOxv5X2akiPvdqB1AoUz2Wc13z4DokuuzDdQy/s3skKxoYU9ZWcfHN8eLJwBe3HTtqxrDQAq4mPwEbISH6L3vYtEJX67DgofqJ8NO5PwAB6M5SApmDLzioh0uekYMlXSMajTDvoiOLUCgLnrbXNm9o0r/R+sOImxJKfDhlPfzDVc7GZSnjmM8nZ1OlDRzJRE08v52RMuAqwWvq//nSbG7n9CBsVvzjSmm+t3hciBo1C+o6xqjJb2kkYH1/V8aFkZItnJgqnFkbWIlbBmw1tqliWkggFYMIIBVKADAgESooIBSwSCAUdK29GSQY1CNbUn6a3rJEqAd1nkkacWmCFY6T95X0hFL9WzoJ3Y0MyA4j7hSM+Fis6Gkw8309bOOTE6sDO4EXH2v/egxmBoPwi+fyR3/KiJU+WcA4SQFXHlj5q7Uwfk77DyzY7EW8zL9QXnuYDvbMkhMxb/kHsNGcNtvq8PCXWIY42eZ5mfOrhIHMOKEax7ASGz3BnSZDCiYNBifTILQrkbu0a8eXsyq63oF3wbwS7EgDRzAKyjFf72DV43eNSCqUk+5cpHcb4GEWiPN/MNJmCKKG77CtHIhjc8sDVFLOm6VUHvPbFhd+KqRe0Bs1AFNCcsk/reTdn/DwqO8rHNg+ExrFucG+xfWmATy8gx6KiIgWLD20ZMBJk+k+SkQqsKHja9O2Xc0QEcfjbFj3jafHNGn1IHIsEm/aw0YYEO3QrX46UO9j0hV44=
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.109 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.8


HTTP/1.1 200 OK
Cache-Control: no-cache
Pragma: no-cache
Content-Type: application/xml; charset=utf-8
Expires: -1
Server: Microsoft-IIS/8.5
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS
Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept, X-Token
Access-Control-Allow-Credentials: true
X-AspNet-Version: 4.0.30319
Persistent-Auth: true
X-Powered-By: ASP.NET
WWW-Authenticate: Negotiate oYG3MIG0oAMKAQChCwYJKoZIgvcSAQICooGfBIGcYIGZBgkqhkiG9xIBAgICAG+BiTCBhqADAgEFoQMCAQ+iejB4oAMCARKicQRv6TYk6zY7v8ulTE1W005r1kZXetFAy2pqg96XwusITKURx5tcoH/EllQuyGErytfHhCmuRQKr0HFcgQ694TMyE0XM8ZDH4gXkVeBBmXge3YWxg9OPvLbtMg2KkFv7+1KunAun79QMMRKzQth+829p
Date: Mon, 18 Sep 2017 15:14:15 GMT
Content-Length: 1661

<ArrayOfRatingRank xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.datacontract.org/2004/07/Prometheus.Domain.Holding.ProfitAndLoss"><RatingRank><Rank>100</Rank><Rating>AAA</Rating></RatingRank><RatingRank><Rank>200</Rank><Rating>AA+</Rating></RatingRank><RatingRank><Rank>300</Rank><Rating>AA</Rating></RatingRank><RatingRank><Rank>400</Rank><Rating>AA-</Rating></RatingRank><RatingRank><Rank>500</Rank><Rating>A+</Rating></RatingRank><RatingRank><Rank>600</Rank><Rating>A</Rating></RatingRank><RatingRank><Rank>700</Rank><Rating>A-</Rating></RatingRank><RatingRank><Rank>800</Rank><Rating>BBB+</Rating></RatingRank><RatingRank><Rank>900</Rank><Rating>BBB</Rating></RatingRank><RatingRank><Rank>1000</Rank><Rating>BBB-</Rating></RatingRank><RatingRank><Rank>1100</Rank><Rating>BB+</Rating></RatingRank><RatingRank><Rank>1200</Rank><Rating>BB</Rating></RatingRank><RatingRank><Rank>1300</Rank><Rating>BB-</Rating></RatingRank><RatingRank><Rank>1400</Rank><Rating>B+</Rating></RatingRank><RatingRank><Rank>1500</Rank><Rating>B</Rating></RatingRank><RatingRank><Rank>1600</Rank><Rating>B-</Rating></RatingRank><RatingRank><Rank>1700</Rank><Rating>CCC+</Rating></RatingRank><RatingRank><Rank>1800</Rank><Rating>CCC</Rating></RatingRank><RatingRank><Rank>1900</Rank><Rating>CCC-</Rating></RatingRank><RatingRank><Rank>2000</Rank><Rating>CC</Rating></RatingRank><RatingRank><Rank>2100</Rank><Rating>C</Rating></RatingRank><RatingRank><Rank>2200</Rank><Rating>D</Rating></RatingRank><RatingRank><Rank>2300</Rank><Rating>NR</Rating></RatingRank><RatingRank><Rank>2400</Rank><Rating>#N/A Invalid Field</Rating></RatingRank></ArrayOfRatingRank>
`
this my RestFixtureConfig and test below:

|Table:smartrics.rest.fitnesse.fixture.RestFixtureConfig|myConf|
|http.client.connection.timeout|60000|
|http.basicauth.username|!-user1-!|
|http.basicauth.password|!-password!-!|


|Table:smartrics.rest.fitnesse.fixture.RestFixture|http://my-test:4450|myConf|
|GET|/api/Ratings|200|Content-Type: application/xml||

When executing via FitNesse, i get the below error message: 

```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>

<title>401 - Unauthorized: Access is denied due to invalid credentials.</title>

<style type="text/css">

<!--

body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}

fieldset{padding:0 15px 10px 15px;} 

h1{font-size:2.4em;margin:0;color:#FFF;}

h2{font-size:1.7em;margin:0;color:#CC0000;} 

h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;} 

#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;

background-color:#555555;}

#content{margin:0 0 0 2%;position:relative;}

.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}

-->

</style>

</head>

<body>

<div id="header"><h1>Server Error</h1></div>

<div id="content">

 <div class="content-container"><fieldset>

  <h2>401 - Unauthorized: Access is denied due to invalid credentials.</h2>

  <h3>You do not have permission to view this directory or page using the credentials that you supplied.</h3>

 </fieldset></div>

</div>

</body>

</html>
```

We are using Integrated Authentication in IIS, when hitting the above service without FitNesse we get a 401 code first, the credentials are checked to ensure they are valid and the GET request called and comes back with 200.

**Comment by smartrics** [comment]
It looks like your service uses NTLM (http://hc.apache.org/httpclient-3.x/authentication.html#NTLM) which is not supported by RestFixture. With RestFixture you can only do Basic auth.

your best bet is to try to build some mechanism that authenticates with the service and gets a valid token then supplies the token to the RestFixture using the setHeader.

Or even better, disable authentication all together.

**Comment by sej2105** [comment]
Thanks for your answer, that's good to know. 

Unfortunately turning off the authentication isn't a possibility so we will look to build our own in order to test the services with NTLM.

Thank you so much for your time in helping to resolve the issue.

**Comment by smartrics** [comment]
you could consider adding ntlm support to RestFixture.

I haven't looked into it in depth but you should be able to Register https://hc.apache.org/httpclient-3.x/apidocs/org/apache/commons/httpclient/auth/NTLMScheme.html
as explained here: http://hc.apache.org/httpclient-3.x/authentication.html#Authentication_Schemes
in the smartrics.rest.fitnesse.fixture.support.HttpClientBuilder#configureCredentials 

You'll need to add other config properties to inject ntlm specific credentials, domain and challenge (input required for ntlm to work).

Check also http://devsac.blogspot.co.uk/2010/10/supoprt-for-ntlmv2-with-apache.html?showComment=1381849801529#c7263680121593236558

I am happy to review if you want to send a pull request once completed
