### ISSUE TITLE
RestFixture - Chain Requests

### ISSUE THREAD

**Issue by damogallagher** [smartrics/RestFixture#240]
Hi

I have a few crud like Rest API calls I want to test using Rest Fixture
I want to test my create calls an delete calls in an efficient way.

using RestFixture - is it possible to call the create call, set the id in a variable and use this as input to the delete call without having to write a Java fixture?

Thank you
Damien

**Comment by smartrics** [comment]
Hi I am sure I understand this. What do you mean with 'create'? 
If you intend an http post then yes absolutely. 
You can execute a post then fetch the I'd from the response body or an header value and pass it on to a delete. Details and samples in the RestFixtureLiveDoc project
