### ISSUE TITLE
Accessing LET variable in DBslim query

### ISSUE THREAD

**Issue by Sooriyaa** [smartrics/RestFixture#242]
Hi,

I need to access the below ID in the DB slim query.  I am not able to assess the ID outside rest fixture.

| POST |/URL | 200 | Content-Type : application/xml ||
| let  | ID | body |//ns:Id/text() | |

| script | Db Slim Select Query | select COLUM_NAME from TABLE_NAME where COLUM_NAME=ID ; |
| check | dataByColumnNameAndRowIndex; | id| 0 | ID |

Can you help me resolve the issue. I have read all the closed issues related to accessing LET variable outside restFixture and nothing worked for me.

Thanks in advance

**Comment by smartrics** [comment]
Can you try and use $ID in the DbSlim and see if it works?

    | script | Db Slim Select Query | select COLUM_NAME from TABLE_NAME where COLUM_NAME=$ID ; |
    | check | dataByColumnNameAndRowIndex; | id| 0 | $ID |

**Comment by Sooriyaa** [comment]
I tried the same but its printing "select COLUM_NAME from TABLE_NAME where COLUM_NAME=$ID"  instead of the value present in it.
