### ISSUE TITLE
Execution of Get caused exception 'Problem when building URI: https://XXX.YYY.dev/api/V/Person/1372801207'

### ISSUE THREAD

**Issue by Hubbleup** [smartrics/RestFixture#244]
Hi 

I am new to fitnesse and i would like to automate testing of my JSON based API calls. 
to begin with, I have downloaded the restfixture and tried the default link it worked but when i was trying the same with my environment i am getting this error "Execution of Get caused exception 'Problem when building URI: https://XXX.YYY.dev/api/V/Person/1372801207'"

this is the request

!define TEST_SYSTEM {slim}
!path C:/scratch/target/dependencies/*.jar

| Import |
| smartrics.rest.fitnesse.fixture |
| smartrics.rest.test.fitnesse.fixture|

| Table: Rest Fixture Config |
| http.basicauth.username | tester1 |
| http.basicauth.password | Lookout12 |
| http.client.connection.timeout | 5000 |
| http.client.use.new.http.uri.factory | true |

| Table : Rest Fixture | https://XXX.YYY.dev/ |
| GET | /api/V/Person/1372801207?h=m | 200 | Content-Type : application/JSON ||

I need to know if issue is caused due to the keystore not embedded in the request or am i missing some other setting.

Let me know if you would need any other additional information.

**Comment by smartrics** [comment]
Hi - the problem may be in the lack of support for https in RestFixture.

Please try by accessing a plain http endpoint.
