### ISSUE TITLE
Assert on whole json body

### ISSUE THREAD

**Issue by jigarshah** [smartrics/RestFixture#245]
Can we assert something like

|!-jsonbody == {"status":"Received","claimStatus":null} -!| 

Basically instead of jsonbody.status=="Received" 
Can we assert whole json body.

**Comment by smartrics** [comment]
Do you intend to compare the json serialized as a string?

**Comment by jigarshah** [comment]
Yes

**Comment by smartrics** [comment]
I wouldn't advise on that approach, but, at any rate, you could override the handler of the application/json content type and use a Text handler to do proper string comparisons
