### ISSUE TITLE
RestFixture: SSL Client Cert 

### ISSUE THREAD

**Issue by floridian** [smartrics/RestFixture#247]
Hi
My REST API requirement is to get the JWT token by passing the user credentials. Once getting the JWT token pass the token as header in actual API end point call. In order to get the JWT token i need to have SSL certificate configured. Also i need to store the JWT token and pass to the test call. How can i customize the SSL. I have custom Java class which takes care of this but how can i use this in TEST Page.

**Comment by smartrics** [comment]
RestFixture doesn't support https.
You'll have to change RestClient to do so by - somehow - allowing the usage of certificates if server requires them, or use the appropriate http client setup.
