### ISSUE TITLE
Value captured using let( ) is not replaced in Let ( ) of other step 

### ISSUE THREAD

**Issue by PriyankaBonam** [smartrics/RestFixture#248]
Hi,

A web service is launched using the Rest Fixture which intern generates a XML response
|POST|/ |200 | | |
|let |count|body|//count/text()|$total=|
Once the script is launched $total is assigned with value as mentioned below,
$total<-[8630]

When trying to access the same variable in other let statement, the variable is not replaced with value
|POST|/ |200 | | |
|let |count|body|//count/text()|$total=|
|let |sum |body|//sum/text() |$count |

I have tried with $count,$total, !-{count}-!, !-{total}-!,!-count-!,!-total-!
None of the notations has worked in symbol replacement.

**Comment by smartrics** [comment]
I am not sure of  what you're trying to achieve. 

can you explain why you want to render $count in that cell?
 
 |let |sum |body|//sum/text() |$count |

The above statement says: "assign to 'sum' the content of //sum/text() extracted from the response body, then display it in the last cell.

**Comment by PriyankaBonam** [comment]
Hi,

The XML has to be parsed using "//sum/text()" and then the value enclosed in the <sum> has to be compared with $count
|let |sum |body|//sum/text() |$count |

**Comment by PriyankaBonam** [comment]
When below mentioned script is used,
|POST|/ |200 | | |
|let |count|body|//count/text()|$total|
The value of $total is compared with $count

The problem arises only when we store the variable value using Let( )  and then compare it in another Let ( )

**Comment by smartrics** [comment]
Hi that's not what let is been designed for.
Let is only to store values in  a variable extracted from body.
the last cell in let shows the value being assigned

to achieve what you want you should write your fixture. for example


 | Table: Rest Fixture |http://${jettyHost}:${jettyPort}|
 |GET    | %resType%/%id% | 200 | | |
 |let    | theName | body | /resource/name/text() | |
 
 | script |!-smartrics.rest.test.fitnesse.fixture.LetTestSupport-!|
 |assign| $theName |
 | check |value |Bill|


https://github.com/smartrics/RestFixtureLiveDoc/blob/master/src/main/java/smartrics/rest/test/fitnesse/fixture/LetTestSupport.java
