### ISSUE TITLE
RestFixture 4.5 Not Working for FitNesse 20161106

### ISSUE THREAD

**Issue by AditiAich** [smartrics/RestFixture#250]
Maven version-3.5.4
Java- jdk1.8.0_40
FitNesse Version- 20161106
************************
My Wiki Page is-

!define TEST_SYSTEM {fit}

!path ../FitNesse/plugins/RestFixture/*.jar

!define TEST_RUNNER {FitSharp\Runner.exe}
!define COLLAPSE_SETUP {true}
!define COLLAPSE_TEARDOWN {true}

|Import                         |
|smartrics.rest.fitnesse.fixture|

!|!-smartrics.rest.fitnesse.fixture.RestFixtureConfig-!|
|restfixture.display.actual.on.right       |true       |

''' Get all resources '''
!|smartrics.rest.fitnesse.fixture.FitRestFixture|http://services.odata.org/V4/Northwind/Northwind.svc|
|GET                                            |       |200       |OData-Version : 4.0       |      |

***********************************

Getting Exception-
fitSharp.Machine.Exception.TypeMissingException: Type 'smartrics.rest.fitnesse.fixture.RestFixtureConfig' not found in assemblies:
    file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
    file:///C:/FitNesse/FitSharp/Runner.exe
    file:///C:/FitNesse/fitSharp/fitSharp.DLL
    file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
    file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
    file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
    file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
    file:///C:/FitNesse/Fixtures/bin/EVFitLibrary.dll
    file:///C:/FitNesse/fitSharp/fit.DLL
    file:///C:/FitNesse/Fixtures/bin/KVS.EnterpriseVault.Interop.EVContentManagementAPI.DLL
    file:///C:/FitNesse/Fixtures/bin/KVS.EnterpriseVault.Interop.AUI.DLL
    file:///C:/FitNesse/Fixtures/bin/Microsoft.Exchange.WebServices.DLL
    file:///C:/FitNesse/Fixtures/bin/EVFitRCWLibrary.DLL
    file:///C:/Windows/assembly/GAC_MSIL/Microsoft.Office.Interop.Outlook/15.0.0.0__71e9bce111e9429c/Microsoft.Office.Interop.Outlook.dll
    file:///C:/FitNesse/Fixtures/bin/KVS.EnterpriseVault.Interop.DirectoryConnection.DLL
    file:///C:/FitNesse/Fixtures/bin/KVS.EnterpriseVault.Interop.TaskController.DLL
    file:///C:/FitNesse/Fixtures/bin/KVS.EnterpriseVault.Interop.RetentionAPI.DLL
    file:///C:/FitNesse/Fixtures/bin/EVAdminAPI.DLL
    file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.DirectoryServices.AccountManagement/v4.0_4.0.0.0__b77a5c561934e089/System.DirectoryServices.AccountManagement.dll
    file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
    file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel/v4.0_4.0.0.0__b77a5c561934e089/System.ServiceModel.dll
    file:///C:/FitNesse/fitSharp/dbfit.DLL
    file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
    file:///C:/FitNesse/fitSharp/dbfit.SqlServer.DLL
    file:///C:/Windows/assembly/GAC_MSIL/office/15.0.0.0__71e9bce111e9429c/office.dll
    file:///C:/FitNesse/Fixtures/bin/KVS.EnterpriseVault.Common.DLL
    file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Management.Automation/v4.0_3.0.0.0__31bf3856ad364e35/System.Management.Automation.dll
    file:///C:/FitNesse/Fixtures/bin/KVS.EnterpriseVault.Interop.AdminService.DLL
    file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Web.Services/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.Services.dll
    file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.DurableInstancing/v4.0_4.0.0.0__31bf3856ad364e35/System.Runtime.DurableInstancing.dll
    file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll
    file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.IdentityModel/v4.0_4.0.0.0__b77a5c561934e089/System.IdentityModel.dll
    file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.EnterpriseServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll

   at fitSharp.Machine.Engine.ReflectionMember.Invoke(Object[] parameters)
   at fitSharp.Machine.Engine.ProcessorBase`2.Operate[O](Object[] parameters)
   at fitSharp.Machine.Engine.ProcessorExtension.Create[T](Processor`1 processor, NameMatcher memberName, Tree`1 parameters)
   at fitSharp.Fit.Operators.ParseInterpreter.MakeInterpreter(Cell classCell)
   at fitSharp.Fit.Operators.ParseInterpreter.Parse(Type type, TypedValue instance, Tree`1 parameters)
   at fitSharp.Machine.Engine.ProcessorBase`2.<>c__DisplayClass11.<>c__DisplayClass13.b__10(ParseOperator`1 o)
   at fitSharp.Machine.Engine.Operators`2.Do[O](CanDoOperation`1 canDoOperation, DoOperation`1 doOperation)
   at fitSharp.Machine.Engine.ProcessorBase`2.<>c__DisplayClass11.b__e(OperationLogging logging)
   at fitSharp.Machine.Engine.ProcessorBase`2.DoLoggedOperation[R](String startMessage, Func`2 operation)
   at fitSharp.Machine.Engine.ProcessorBase`2.Parse(Type type, TypedValue instance, Tree`1 parameters)
   at fitSharp.Fit.Service.CellProcessorBase.Parse(Type type, TypedValue instance, Tree`1 parameters)
   at fitSharp.Machine.Engine.ProcessorExtension.ParseTree[T](Processor`1 processor, Type type, Tree`1 parameters)
   at fitSharp.Machine.Engine.ProcessorExtension.ParseTree[T,V](Processor`1 processor, Tree`1 input)
   at fitSharp.Fit.Engine.InterpretFlow.ProcessFlowRow(Tree`1 table, Int32 rowNumber)

Please help!

**Comment by AditiAich** [comment]
@smartrics 
Please help.. :(  its urgent

**Comment by AditiAich** [comment]
@smartrics _**PLEASE HELP**_

After looking more into it and trying more options found-
---When I am **commenting** 'COMMAND_PATTERN', then the things are working else getting the exception.
---Please help me with the solution as I need to refer Fixture.dll's which are refered using config file and also need the RestFixture jar files for obvious reason.



Following is my new test page which I am trying to check if RestFixture working.

#!define COMMAND_PATTERN {%m -r fitnesse.fitserver.FitServer,fitSharp\fit.dll -c FitNesse\FitnesseRoot\SuiteOdata\odata.config.xml}

!path FitNesse/Plugins/RestFixture/*.jar

|Import                         |
|smartrics.rest.fitnesse.fixture|

|!-smartrics.rest.fitnesse.fixture.RestFixtureConfig-!|!-OdataConfig-!|
|http.client.connection.timeout                       |60000          |
|http.socket.timeout                                  |60000          |

|!-smartrics.rest.fitnesse.fixture.RestFixtureConfig-!|!-OdataConfig-!|
|http.basicauth.username                              |Domain\Admin1        |
|http.basicauth.password                              |Pass78163hn       |
|restfixture.display.actual.on.right                  |true           |

**Comment by smartrics** [comment]
Sorry - I can't help as unable to reproduce any issue with FitSharp.

You could try on the main FitNesse yahoo group
