### ISSUE TITLE
Can I use RestFixture to test if a web server is down?

### ISSUE THREAD

**Issue by superherosalive** [smartrics/RestFixture#253]
I'm trying to write a simple test to see whether the rest server is down using RestFixture before sending a restful request.  If the response code is NOT 200, then I know it's down and no need to send a request.

I keep getting this error:
INFO: I/O exception (java.net.ConnectException) caught when processing request: Connection timed out: connect
OR
Execution of GET caused exception 'Http call failed for IO failure'

Can someone help?  

!define TEST_SYSTEM {slim}
!path C:\QATests\RestFixtureLib\lib\*.jar
!path C:\QATests\fitnesse-standalone.jar

|Import|
|smartrics.rest.fitnesse.fixture|

|Table: Rest Fixture|http://localhost:8888|
|GET||200|||

**Comment by frank-at-work** [comment]
Hi superherosalive, 
I am not familiar with testing web Services. But isn't the exception correct? Only a running web server is able to create a proper HTTP return Code. 

Please verify those resources for testing expected exceptions:

- [SliM Exception Handling](http://fitnesse.org/FitNesse.UserGuide.WritingAcceptanceTests.SliM.ExceptionHandling)
- Or search Google for 'fitnesse test for exceptions'

Best wishes
Frank

**Comment by superherosalive** [comment]
Hi Frank,
Thank you for your help.  I believe you're right that a web server must be running in order for it to return a code.  Also RestFixture doesn't support HTTPS, which I need.  I'm wonder if there's a workaround for HTTPS.

**Comment by frank-at-work** [comment]
> ...  Also RestFixture doesn't support HTTPS, which I need.  I'm wonder if there's a workaround for HTTPS.

If I read anything Right, it should work. Please read along the following Sources:

1. [Missing Proxy configuration](https://github.com/smartrics/RestFixture/issues/42)
2. [Higher timeout](https://github.com/smartrics/RestFixture/issues/44)
3. [Quite old 'Not entirely' remark](https://github.com/smartrics/RestFixture/issues/127)

Best wishes 
Frank

**Comment by smartrics** [comment]
Hi - RestFixture allows you to test an existing API - It is not a general purpose http client. For this check you can write your own fixture or use an existing fixture. 

There's no support for https. Again you could write a tiny proxy or enrich the RestClient to support https.

Regarding redirect, there's a property you can set to determine whether you want the RestClient to follow redirects or not: `restfixture.requests.follow.redirects`

**Comment by frank-at-work** [comment]
Hi Fabrizio,
thank you for your fast Reply. I am also planning to automate a REST API with the help of RestFixture. It is for sure, that we are testing against secured HTTPS. Could you please comment on the links given above about the proxy, a higher timeout or the 'Not entirely' remark? Are those comments true? Is it covered in RestFixture's documentation? Thank you for your answer.
Best wishes
Frank

**Comment by smartrics** [comment]
Hi - RestFixture isn't supporting HTTPS and I don't have time to update the code (basically the rest client). Proxy and custom timeouts should be supported.

**Comment by frank-at-work** [comment]
Thank you for your reply. We are using Postman right now. We plan to automate it by using the Newman plugin.
