### ISSUE TITLE
Json assertion failing with IlegalArgumentException

### ISSUE THREAD

**Issue by qhu009** [smartrics/RestFixture#255]
Hello,
I'm facing an issue while asserting json fields. 
Here is my JSON response 
{
    "id": 123,
    "name": "steven",
    "item": "Cheers"
}

and this is my assertion code

!define myBody {!-
 jsonbody.id==123
 -!}

!3 Create Auth
|Table:smartrics.rest.fitnesse.fixture.RestFixture|${AuthServiceEndPoint}                                |
|GET                                              |/?id=123|200|                               |${myBody}|
|let                                              |id      |js |JSON.parse(response.body).id;  |123      |
|let                                              |name    |js |JSON.parse(response.body).name;|steven   |
|let                                              |item    |js |JSON.parse(response.body).item;|Cheers   |

java.lang.IllegalArgumentException: Cannot evaluate 'jsonbody.id==123' in {
    "id": 123,
    "name": "steven",
    "item": "Cheers"
}

**Comment by smartrics** [comment]
Hi - i have reproduced your test case but it works for me:

https://github.com/smartrics/RestFixtureLiveDoc/blob/master/src/main/resources/FitNesseRoot/RestFixtureTests/IssueFixes/Issue255/content.txt

make sure your response sets the content type to application/json or override via restfixture config your content type to use the json body handler

    | Table: Rest Fixture Config  | overridesContentHandlerConfig |
    | restfixture.content.handlers.map | !-
    your/mime=JSON
    -!|
