### ISSUE TITLE
why the let value is change?

### ISSUE THREAD

**Issue by cmaster007** [smartrics/RestFixture#256]
let | incident_accept_count | js | response.jsonbody.dws[0]["incident_accept_count"] | 270
sometimes   incident_accept_count==‘270’  sometimes   incident_accept_count==‘270.0'

**Comment by smartrics** [comment]
I think it's caused by javascript interpreter. as far as the numbers are concerned both 270 and 270.0 are identical. 
You could try to convert the result to string and check it as string:

    response.jsonbody.dws[0]["incident_accept_count"].toString()

**Comment by cmaster007** [comment]
thank you
