### ISSUE TITLE
How set header Authorization?

### ISSUE THREAD

**Issue by cmaster007** [smartrics/RestFixture#260]
!include -c .RestHive.Library
|Table:Rest Fixture | ${RestQuery}| 
|setHeader |Authorization: Basic YWRtaW5AemlhZG1pbjAxOnppYWRtaW4wMQ==| 
|setBody |{"sql":"select count(*) from ecmp.dwd_inc_accept" }|
|POST | /query | 200 |Content-Type:application/json | jsonbody.__sys__.status=="0" |

it will error: 

java.lang.IllegalArgumentException: Cannot evaluate 'jsonbody.__sys__.status=="0"' in <html><head><title>Apache Tomcat/7.0.33 - Error report</title><style></style> </head><body><h1>HTTP Status 415 - Unsupported Media Type</h1><HR size="1" noshade="noshade"><p><b>type</b> Status report</p><p><b>message</b> <u>Unsupported Media Type</u></p><p><b>description</b> <u>The server refused this request because the request entity is in a format not supported by the requested resource for the requested method.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/7.0.33</h3></body></html>

    at smartrics.rest.fitnesse.fixture.support.XPathBodyTypeAdapter.equals(XPathBodyTypeAdapter.java:76)

    at smartrics.rest.fitnesse.fixture.RestFixture.process(RestFixture.java:1221)

|setHeader |Authorization: Basic YWRtaW5AemlhZG1pbjAxOnppYWRtaW4wMQ==;Content-Type:application/json| 

it  will error:

(ErrorCode:6)Invalid username or password.

**Comment by smartrics** [comment]
please try

```
|setHeader |Authorization: Basic YWRtaW5AemlhZG1pbjAxOnppYWRtaW4wMQ==|
|addHeader|Content-Type:application/json|
```

please reopen if it doesn't work for you
