### ISSUE TITLE
Problem when building URI

### ISSUE THREAD

**Issue by ghost** [smartrics/RestFixture#42]
Hi,

I am having a problem using RestFixture 2.0. I have downloaded the complete package including all dependencies (RestFixture-2.0.zip). I have installed it as described here: https://github.com/smartrics/RestFixture/tree/RestFixture-2.0. I am using FitNesse v.20111025.

This is my test case:

``` javascript
!define TEST_SYSTEM {slim}
!path RestFixture/lib/*.jar
!path RestFixture/RestFixture.jar

| !-Table:smartrics.rest.fitnesse.fixture.RestFixtureConfig-! |
| http.client.use.new.http.uri.factory | true |

| !-Table:smartrics.rest.fitnesse.fixture.RestFixture-! | !-https://c2bpmt-i.xy.com/idm/services-! |
| GET | !-/version-! | 200 | Content-Type : text/plain | =~/.*Manifest.*/ |
```

When running the test, the last row of the table is yellow and has the following error message:

``` javascript
Execution of Get caused exception 'Problem when building URI: https://c2bpmt-i.xy.com/idm/services/version'
```

This is strange as the URL looks fine for me and I can open it manually on my machine without a problem.

When I use the stricter URI validation rules using the configuration option

``` javascript
| http.client.use.new.http.uri.factory | false |
```

I get the following error:

``` javascript
Execution of Get caused exception 'Http call failed for IO failure. Exception message = c2bpmt-i.xy.com'
```

First I thought it might be a charset or encoding problem, but everything is using UTF-8.

Do you have an idea what the problem might be? Thanks for your help!

**Comment by srinivasmmdl** [comment]
Where you have configured keystore and trust store to call the https services.
