### ISSUE TITLE
Http call failed for IO failure. Exception message = Read timed out

### ISSUE THREAD

**Issue by facundofarias** [smartrics/RestFixture#44]
Doing a POST operation, using Fitnesse with RestFixture, I am getting this error: 

Execution of Post caused exception 'Http call failed for IO failure. Exception message = Read timed out'

It's weird, because it's just in some tests, I mean, I'm doing another POST operations and are working okay. It seems to be that the response it's taking a while more.
I've configured: 

http.client.connection.timeout  100000

But I'm still with the same issue. How I can force an sleep time between tests?
Thanks!

Facundo

**Comment by lucianlesu** [comment]
Thank you @facundofarias for leaving the above reply. After days and days of crying in the shower asking the gods why do the test fail, I found your comment. I now believe in a higher power (Google). Thank you for fixing my tests as well.

**Comment by facundofarias** [comment]
@lucianlesu Hahaha glad it worked for you as well! 👍

**Comment by papatwo** [comment]
> Alright. I've turned on the logs. I found something:
> 
> DEBUG [DefaultHttpParams] - Set parameter http.socket.timeout = 3000
> 
> Shouldn't this be the value that I put in the configuration? I will try changing this value, and running my tests again.

Hi @facundofarias 
very sorry to bother you again after years. I think I met the same issue as yours. I set my http.client.connection.timeout 100000 in RestFixtureConfig but still get the IO failure. And I checked log http.socket.timeout is still 3000 just as you mentioned in this reply. May I ask how did you manage to change this value to extend the timeout? Thanks a million if you could gimme a hint.
