### ISSUE TITLE
Retrieving XML Value Using XPath

### ISSUE THREAD

**Issue by dwhalen14** [smartrics/RestFixture#53]
I am trying to extract a value using xpath.  I want to put it into a variable that I can use later.  My let is returning a blank (see atch).  I've tried a couple of options but I get nothing.  I've also tried putting it in the GET - that gives me a yellow java error.  Suggestions?

![Xpath2](https://f.cloud.github.com/assets/3673410/198754/029905fe-8065-11e2-8d3a-d7d815444175.png)
![Xpath1](https://f.cloud.github.com/assets/3673410/198755/02957510-8065-11e2-8594-5af7ecc8978e.png)

**Comment by krishnammadduri** [comment]
Hi,
Could you please help in validating the XML,

I am facing the problem with assertions.

Below is the sample excerpt from the XML

<Order xmlns="http://namespace.abc.defghi.com/common/v2_4_1/order" version="2.4.1" type="TEST" ID="123456789">
<Header>
<SourceService>
<Application>
<Name>xxxx</Name>
<Version>2.0</Version>
</Application>
<Locale country="US" language="en"/>
</SourceService>
</Header>

I want to validate Version from the above xml. can you please help ?

Below is the test

!define defns {!-http://namespace.abc.defghi.com/common/v2_4_1/order-!}

|Table: Rest Fixture Config                   |
|restfixture.xml.namespace.context|ns=${defns}|

and assertion as
//Order/Header/SourceService/Application/Version[text()='2.0']

**Comment by smartrics** [comment]
Hi this worked for me

    |Table: Rest Fixture Config | conf |
    |restfixture.xml.namespace.context| !-defns=http://namespace.abc.defghi.com/common/v2_4_1/order-! |

    |Table: Rest Fixture |http://${jettyHost}:${jettyPort} | conf |
    | GET | /order |  |  | //defns:Version[text()='2.0'] |
