### ISSUE TITLE
getting a GET to work with the proper JSONpath

### ISSUE THREAD

**Issue by sam4adams** [smartrics/RestFixture#64]
Hi Smartrics,
I’m fairly new to this. So I apologize ahead of time. I’ve been experimenting with RestFixture on simple XML and JSON tables.  I’ve been able to make a GET test work with a XML output. But I’m having difficulty making a similar test work with a JSON output.  Also can you give me examples of how one would do a GET call for different objects further down the JSON output (Different artist/albums/tracks etc)?  
Thx,

-Fitnesse Setup (what I have setup):

!define TEST_SYSTEM {slim}
!path C:/RestFixture/target/dependencies/*
!path C:/RestFixture/target/smartrics-RestFixture-3.1-SNAPSHOT.jar
!path C:/RestFixture/smartrics-RestFixture-3.0/lib/xmlpull-1.1.3.1.jar
!path C:/RestFixture/smartrics-RestFixture-3.0/lib/smartrics-RestFixture-3.0.jar

| Table:smartrics.rest.fitnesse.fixture.RestFixture |http://******\* |
| GET ||||jsonbody.albums[0].title=="Ten Summoner's Tales"|

-JSON output: 
[

```
{
    "name": "Sting",
    "albums": [
        {
            "year": "1993",
            "title": "Ten Summoner's Tales",
            "tracks": [
                "1:If I Ever Lose My Faith in You",
                "2:Love Is Stronger Than Justice",
                "3:Fields of Gold",
                "4:Heavy Cloud No Rain",
                "5:She's Too Good for Me",
                "6:Seven Days",
                "7:Saint Augustine in Hell",
                "8:It's Probably Me",
                "9:Everybody Laughed But You",
                "10:Shape of My Heart",
                "11:Something the Boy Said",
                "12:Epilogue"
            ]
        },
        {
            "year": "1991",
            "title": "The Soul Cages",
            "tracks": [
                "1:Island of Souls",
                "2:All This Time",
                "3:Mad About You",
                "4:Jeremiah Blues",
                "5:Why Should I Cry for You",
                "6:Saint Agnes and the Burning Train",
                "7:he Wild Wild Sea",
                "8:The Soul Cages",
                "9:When the Angels Fall"
            ]
        }
    ]
},
{
    "name": "Metallica",
    "albums": [
        {
            "year": "1991",
            "title": "Black",
            "tracks": [
                "1:Enter Sandman",
                "2:Holier Then Thou",
                "3:The Unforgiven"
            ]
        }
    ]
}
```

]

**Comment by ahmah11** [comment]
Is there a way to define a variable through the rest fixture, example i do a get and receive a json that contains a username, can i do something like !define username {jsonbody.username} ?

**Comment by ahmah11** [comment]
I see we can use "let" command, but let's say i saved something from my json into 'id', how can i reuse 'id' in the following tests ?
