### ISSUE TITLE
HTTP 401 error help

### ISSUE THREAD

**Issue by sam4adams** [smartrics/RestFixture#67]
Hi,
I'm trying the following POST rest call in Fitnesse.
|Table:smartrics.rest.fitnesse.fixture.RestFixture|!-https://rally1.rallydev.com/slm/webservice/v2.0-!|
|setHeader|!-Content-Type : text/javascript-!|
|setBody|!-{"ID":{"Notes":" Testing works3"}}-!|
|POST|!-/HierarchicalRequirement/XXXXXXX.js?fetch=Notes,Rank&key=xxxx-xxxxx-xxxx-xxx-xxxx-!||||

Running the same POST call in the REST client plug in (IE Firefox) works just fine. However running the same post in Fitnesse results in the following 401 error(below). Any ideas? 

Table:smartrics.rest.fitnesse.fixture.RestFixture | https://rally1.rallydev.com/slm/webservice/v2.0 |
setHeader   Content-Type&nbsp;:&nbsp;text/javascript |
setBody     {"ID":{"Notes":" Testing works3"}} |
POST | "<a href='https://rally1.rallydev.com/slm/webservice/v2.0/HierarchicalRequirement/XXXXXXX.jsfetch=Notes,Rank&key=xxxx-xxxxx-xxxx-xxx-xxxx>/HierarchicalRequirement/XXXXXXX.js?fetch=Notes,Rank&key=xxxx-xxxxx-xxxx-xxx-xxxx</a>|401 |WWW-Authenticate&nbsp;:&nbsp;Basic&nbsp;realm="Rally&nbsp;ALM"<br/>Content-Type&nbsp;:&nbsp;text/html;charset=ISO-8859-1<br/>Cache-Control&nbsp;:&nbsp;no-cache,no-store,max-age=0,must-revalidate<br/>Expires&nbsp;:&nbsp;Mon,&nbsp;19&nbsp;Aug&nbsp;2013&nbsp;18:37:39&nbsp;GMT<br/>Vary&nbsp;:&nbsp;Accept-Encoding<br/>Content-Encoding&nbsp;:&nbsp;gzip<br/>P3P&nbsp;:&nbsp;CP="NON&nbsp;DSP&nbsp;COR&nbsp;CURa&nbsp;PSAa&nbsp;PSDa&nbsp;OUR&nbsp;NOR&nbsp;BUS&nbsp;PUR&nbsp;COM&nbsp;NAV&nbsp;STA"<br/>Content-Length&nbsp;:&nbsp;313<br/>Date&nbsp;:&nbsp;Mon,&nbsp;19&nbsp;Aug&nbsp;2013&nbsp;18:37:39&nbsp;GMT<br/>Connection&nbsp;:&nbsp;close<br/>Set-Cookie&nbsp;:&nbsp;JSESSIONID=qs-app-071gb4akul8ip6515gnqgzkuqss1.qs-app-07;Path=/;Secure;HttpOnly |
íÁRÂ0ï&lt;ÅNïeiÑ1äâà Ê¤aÇÄIL¶&nbsp;ooÚòz=$l¾ÿ~a¸qr"©CÚbùÓWgO«ìÙ·L-çûË2Ðãi1}3öèh£B$^½¾oóÅâþ1/2LJlÙ\àÜÍ<br/>xéÕ±I¼Õ­oÁFý@`JkØ÷ÑwAÀQh"ðj±ö¦ý~ëªÚVýÔ/S÷(wÁ×«m?£kðLu¤p²ðTNg¸±TÐ&yqÕh¢IÖ°å¬(óégBE*úvIHõçôiMÞ VØ(çäÎ©ë¼óe(pl&nbsp;&nbsp;&nbsp;&nbsp;L¯êÃàßÔäFÝ¨õ©CTöÉ9dü×RGë |"
Is it because the URL is HTTPS based insted of HTTP?

**Comment by mkyudi** [comment]
binary data in cookie is due to "Content-Encoding : gzip"
