### ISSUE TITLE
Encountered code generation error while compiling script: generated bytecode for method exceeds 64K limit. (unnamed script#1)

### ISSUE THREAD

**Issue by aramzl** [smartrics/RestFixture#74]
Hi,

I've working with FitNesse und the RestFixture and everything worked fine.
But then I had a json response that is too large, hence the 'exceeds 64K limit', but I haven't found a workaround or solution to the problem. I found a couple of links: http://soa.ulitzer.com/node/659575 
but it didn't help much. I would appreciate some explanation and/or solution.

Am I the only person getting this error?

**Comment by joshbp81** [comment]
Hi, 

I have been using RestFixture for a while and had no problems at all. However, I recently found this problem when testing a website that returns a large JSON response. Is there anything I can do to solve the issue?

Thanks!

**Comment by smartrics** [comment]
Hi - you'll need to rebuild the RestFixture after fixing the class 

smartrics.rest.fitnesse.fixture.support.JavascriptWrapper

specifically by adding the setOptimisationLevel(-1) in the method

	public Object evaluateExpression(RestResponse response, String expression) {
		if (expression == null) {
			return null;
		}
		Context context = Context.enter();
                context.setOptimizationLevel(-1);
     ...

    }


I have not tried but according to the comment above from @aramzl it should work.

**Comment by joshbp81** [comment]
Just tested it and it works like a charm. 

Thanks a million!

**Comment by smartrics** [comment]
Thanks for checking.
i have committed it to the master branch so it will come by default on the next release of RestFixture.

**Comment by joshbp81** [comment]
You're very welcome. It's been a very useful Fixture for me so far, so I'm happy to help.

**Comment by haroon-sheikh** [comment]
@smartrics I'm still seeing this error with 4.2. Any idea how I can resolve this?
