### ISSUE TITLE
Xml converted to html entities

### ISSUE THREAD

**Issue by iwan41** [smartrics/RestFixture#76]
I have problem with latest fitnesse and RestFixture from git. Am I missing something or how can I configure restFixture to display xml correct.

![restfixture](https://f.cloud.github.com/assets/6312273/1840320/13fa5648-7490-11e3-8cc4-894b12b998a8.png)

In your examples I can see that your xml is properly displayed.

http://4.bp.blogspot.com/_HA4XCmK8W8I/SJZ6dgchcAI/AAAAAAAAABk/0qUpkyIODY4/s1600/get-run.png

**Comment by alvillaflor** [comment]
Where can I get a compiled version of the latest code without needing to run maven?
