### ISSUE TITLE
IO Error: Execution of Get caused exception 'Http call failed for IO failure'

### ISSUE THREAD

**Issue by vinothsdev** [smartrics/RestFixture#94]
I am getting "Execution of Get caused exception 'Http call failed for IO failure'" error while trying to run api test with get request to my web server. 
Error log has exception - "sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target"
Can you please let me know how to bypass the certification validation in the source code?

**Comment by vipinksahu** [comment]
Does Rest fixture supports https now?

**Comment by srinivasmmdl** [comment]
Does Rest fixture supports https now?

**Comment by smartrics** [comment]
RestFixture doesn't support https. Likely it will never do as I don't have time nor need to do so. But I will consider merging pull requests from other contributors

**Comment by srinivasmmdl** [comment]
We are referring the below procedure to setup 2way(mutual authentication) SSL between Fitnesse test system and SUT(System Under Testing).

http://www.fitnesse.org/FitNesse.FullReferenceGuide.UserGuide.AdministeringFitNesse.NetworkSecurity

Will this support SSL with Fitnesse RestFixture calling rest apis with https?

Thanks.

**Comment by smartrics** [comment]
No it won't. That tutorial explains how to enable ssl in fitnesse.   To
support ssl in RestFixture (ie to communicate with a SUT over ssl) you must
enhance RestClient to enabe pki.

**Comment by srinivasmmdl** [comment]
Hi,
Thank you for the response.

I wanted to load test data from spreadsheet for restfixture to test rest api calls.
I tried to load spreadsheet but it's not working.

Can you please provide some documents to do this.
